/* 词库数据 1/12 · A */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"a|art.一（个）；每一（个）",
"abandon|v.放弃；抛弃；放纵",
"abdomen|n.腹部",
"abide|v.遵守；忍受；容忍",
"ability|n.能力；才能",
"able|a.能够的；有能力的",
"abnormal|a.反常的；异常的",
"aboard|ad./prep.在船（飞机、车）上",
"abolish|v.废除；取消",
"abound|v.大量存在；充满",
"about|ad.大约；周围 prep.关于",
"above|a.上述的 ad.在上面 prep.高于",
"abroad|ad.在国外；到处",
"absence|n.缺席；缺乏",
"absent|a.缺席的；心不在焉的",
"absolute|a.绝对的；完全的",
"absorb|v.吸收；使专心",
"abstract|a.抽象的 n.摘要 v.提取",
"absurd|a.荒谬的；荒唐的",
"abundance|n.丰富；充裕",
"abundant|a.丰富的；充裕的",
"abuse|v./n.滥用；虐待；辱骂",
"academic|a.学术的；学业的 n.大学教师",
"academy|n.学院；研究院；学会",
"accelerate|v.加速；促进",
"accent|n.口音；重音；重音符号",
"accept|v.接受；认可",
"acceptance|n.接受；接纳；赞同",
"access|n.进入；使用权 v.存取；访问",
"accessory|n.附件；配件；同谋",
"accident|n.事故；意外的事",
"accidental|a.偶然的；意外的",
"acclaim|v./n.欢呼；称赞",
"accommodate|v.容纳；向…提供住处；使适应",
"accompany|v.陪伴；伴随；伴奏",
"accomplish|v.完成；实现；达到",
"accord|n./v.一致；符合；协议",
"accordance|n.一致；和谐",
"accordingly|ad.因此；相应地",
"account|n.账户；描述；理由 v.说明；占",
"accountant|n.会计师",
"accumulate|v.积累；积聚",
"accuracy|n.准确（性）；精确（性）",
"accurate|a.准确的；精确的",
"accuse|v.指责；控告",
"accustom|v.使习惯于",
"ache|v./n.疼痛",
"achieve|v.实现；达到；完成",
"achievement|n.成就；成绩；实现",
"acid|n.酸 a.酸的；酸性的",
"acknowledge|v.承认；致谢；告知收到",
"acquaint|v.使熟悉；使认识",
"acquaintance|n.熟人；相识；了解",
"acquire|v.获得；取得；学到",
"acquisition|n.获得；收购",
"acre|n.英亩",
"acrobat|n.杂技演员",
"act|v.行动；表演 n.行为；法案",
"action|n.行动；行为；作用",
"activate|v.激活；使活动",
"active|a.积极的；活跃的；主动的",
"activity|n.活动；活性",
"actor|n.男演员",
"actress|n.女演员",
"actual|a.实际的；真实的",
"acute|a.敏锐的；急性的；严重的",
"adapt|v.适应；改编",
"adaptation|n.适应；改编（本）",
"add|v.增加；添加；补充说",
"addition|n.加法；增加；附加物",
"additional|a.附加的；额外的",
"address|n.地址；演讲 v.写地址；处理；向…讲话",
"adequate|a.足够的；适当的",
"adhere|v.粘附；坚持；遵循",
"adjacent|a.邻近的；毗邻的",
"adjective|n.形容词",
"adjoin|v.邻近；毗连",
"adjust|v.调整；调节；适应",
"administer|v.管理；执行；施行",
"administration|n.管理；行政；政府",
"admirable|a.令人钦佩的；极好的",
"admire|v.钦佩；羡慕；赞赏",
"admission|n.准许进入；入场费；承认",
"admit|v.承认；准许进入",
"adolescent|n.青少年 a.青春期的",
"adopt|v.采用；采取；收养",
"adore|v.崇拜；喜爱",
"adult|n.成年人 a.成年的",
"advance|v./n.前进；提前；进展",
"advanced|a.先进的；高级的",
"advantage|n.优点；好处；优势",
"advent|n.出现；到来",
"adventure|n.冒险；奇遇",
"adverb|n.副词",
"adverse|a.不利的；相反的",
"advertise|v.做广告；宣传",
"advice|n.劝告；建议",
"advisable|a.明智的；可取的",
"advise|v.建议；劝告",
"advocate|v.提倡；主张 n.拥护者",
"aerial|a.空中的 n.天线",
"aerospace|n.航空航天（工业）",
"affair|n.事；事务；事情",
"affect|v.影响；感动；假装",
"affection|n.喜爱；感情",
"affiliate|v.使隶属；附属 n.附属机构",
"affirm|v.断言；肯定",
"affluent|a.富裕的；丰富的",
"afford|v.买得起；负担得起；提供",
"afraid|a.害怕的；担心的",
"after|prep./conj.在…之后",
"afternoon|n.下午",
"afterward|ad.后来；以后",
"again|ad.又；再；再一次",
"against|prep.反对；靠着；违反",
"age|n.年龄；时代 v.变老",
"agency|n.代理（处）；机构",
"agenda|n.议程；议事日程",
"agent|n.代理人；特工；剂",
"aggravate|v.加重；恶化",
"aggressive|a.侵略的；好斗的；有进取心的",
"agitate|v.鼓动；使不安；搅动",
"agony|n.极度痛苦",
"agree|v.同意；一致；适合",
"agreeable|a.令人愉快的；同意的",
"agreement|n.协议；同意；一致",
"agricultural|a.农业的",
"agriculture|n.农业；农艺",
"ahead|ad.在前；向前；提前",
"aid|n./v.帮助；援助",
"aim|v.目的在于；瞄准 n.目标",
"air|n.空气；天空 v.通风；播送",
"aircraft|n.飞机；航空器",
"airline|n.航空公司；航线",
"airplane|n.飞机",
"airport|n.机场",
"aisle|n.过道；通道",
"alarm|n.警报；惊慌 v.使惊恐；警告",
"album|n.相册；集邮册；专辑",
"alcohol|n.酒精；酒",
"alert|a.警惕的 n.警报 v.使警觉",
"alien|a.外国的；陌生的 n.外星人；外人",
"alike|a.相同的 ad.同样地",
"alive|a.活着的；有活力的",
"allege|v.宣称；断言",
"alleviate|v.减轻；缓解",
"alliance|n.联盟；结盟",
"allocate|v.分配；拨给",
"allow|v.允许；准许；给予",
"allowance|n.津贴；零用钱；体谅",
"alloy|n.合金",
"ally|n.同盟者 v.结盟",
"almost|ad.几乎；差不多",
"alone|a.单独的 ad.仅仅；单独地",
"along|ad.向前 prep.沿着",
"alongside|prep.在…旁边 ad.并排地",
"aloud|ad.大声地；出声地",
"alphabet|n.字母表",
"already|ad.已经；早已",
"also|ad.也；还；而且",
"alter|v.改变；变更",
"alternate|v.交替 a.交替的；间隔的",
"alternative|n.可供选择的事物 a.可供替代的",
"although|conj.虽然；尽管",
"altitude|n.高度；海拔",
"altogether|ad.总共；完全；总而言之",
"aluminium|n.铝",
"always|ad.总是；一直；永远",
"amass|v.积聚；收集",
"amaze|v.使惊奇；使惊愕",
"ambition|n.雄心；抱负；野心",
"ambitious|a.有雄心的；有野心的",
"ambulance|n.救护车",
"amend|v.修改；修订",
"amid|prep.在…之中",
"ammunition|n.弹药；军火",
"among|prep.在…之中；…之一",
"amount|n.数量；总额 v.总计；等于",
"ample|a.充足的；宽敞的",
"amplify|v.放大；增强；详述",
"amuse|v.逗乐；给…娱乐",
"analog|n.类似物 a.模拟的",
"analogy|n.类比；类似",
"analyse|v.分析；分解",
"analysis|n.分析；分解",
"analytic|a.分析的；解析的",
"ancestor|n.祖先；先驱",
"anchor|n.锚 v.抛锚；使固定",
"ancient|a.古代的；古老的",
"and|conj.和；而且；那么",
"anecdote|n.轶事；趣闻",
"anger|n.怒；愤怒 v.使发怒",
"angle|n.角；角度；观点",
"angry|a.愤怒的；生气的",
"anguish|n.极度痛苦；苦恼",
"animal|n.动物 a.动物的",
"animate|v.使有活力 a.有生命的",
"ankle|n.踝；踝关节",
"anniversary|n.周年纪念（日）",
"announce|v.宣布；宣告",
"annoy|v.使烦恼；惹恼",
"annual|a.每年的 n.年刊",
"anonymous|a.匿名的；无名的",
"another|a.另一个的 pron.另一个",
"answer|v./n.回答；答案；回应",
"ant|n.蚂蚁",
"antenna|n.天线；触角",
"anticipate|v.预期；期望；先于…行动",
"antique|n.古董 a.古董的",
"anxiety|n.焦虑；渴望",
"anxious|a.焦虑的；渴望的",
"any|a.任何的 pron.任何一个",
"anybody|pron.任何人；无论谁",
"anyhow|ad.无论如何；不管怎样",
"anyone|pron.任何人",
"anything|pron.任何事物；什么事",
"anyway|ad.无论如何；反正",
"anywhere|ad.任何地方",
"apart|ad.分开；相隔；成碎片",
"apartment|n.公寓；房间",
"apologize|v.道歉；认错",
"appall|v.使惊骇；使震惊",
"apparatus|n.器械；设备；装置",
"apparent|a.明显的；表面上的",
"appeal|v./n.呼吁；上诉；吸引力",
"appear|v.出现；似乎；出版",
"appearance|n.出现；外貌；外观",
"appendix|n.附录；阑尾",
"appetite|n.食欲；胃口；欲望",
"applaud|v.鼓掌；称赞",
"applause|n.掌声；喝彩",
"appliance|n.（家用）电器；器具",
"applicable|a.适用的；合适的",
"applicant|n.申请人",
"application|n.申请；应用；应用程序",
"apply|v.申请；应用；涂抹",
"appoint|v.任命；约定；指定",
"appointment|n.约会；任命",
"appraisal|n.评价；估价",
"appreciate|v.感激；欣赏；理解",
"apprehension|n.忧虑；理解；逮捕",
"apprentice|n.学徒；徒弟",
"approach|v.接近 n.方法；途径",
"appropriate|a.适当的 v.挪用；拨出",
"approve|v.批准；赞成",
"approximate|a.近似的 v.近似",
"April|n.四月",
"apt|a.易于…的；恰当的；聪明的",
"arbitrary|a.任意的；武断的",
"arch|n.拱门 v.使成弓形",
"architect|n.建筑师；设计师",
"architecture|n.建筑学；建筑风格",
"archive|n.档案；档案馆 v.存档",
"arctic|a.北极的 n.北极",
"area|n.地区；面积；领域",
"argue|v.争论；辩论；主张",
"argument|n.争论；论点；理由",
"arise|v.出现；产生；起身",
"arithmetic|n.算术 a.算术的",
"arm|n.手臂；武器 v.武装",
"army|n.军队；陆军；大群",
"around|ad.周围 prep.围绕；大约",
"arouse|v.唤醒；激起；引起",
"arrange|v.安排；整理；筹备",
"array|n.一系列；排列 v.排列",
"arrest|v./n.逮捕；阻止",
"arrival|n.到达；到达者",
"arrive|v.到达；达成",
"arrogant|a.傲慢的；自大的",
"arrow|n.箭；箭头",
"art|n.艺术；美术；技艺",
"artery|n.动脉；干线",
"article|n.文章；物品；条款；冠词",
"articulate|a.善于表达的 v.清晰表达",
"artificial|a.人工的；人造的；虚假的",
"artist|n.艺术家；画家",
"artistic|a.艺术的；有艺术天赋的",
"ascend|v.上升；攀登",
"ascertain|v.查明；确定",
"ascribe|v.归因于；归功于",
"ash|n.灰；灰烬",
"ashamed|a.羞愧的；惭愧的",
"aside|ad.在旁边；到一边",
"ask|v.问；请求；邀请",
"asleep|a.睡着的",
"aspect|n.方面；外观；方位",
"aspire|v.渴望；追求",
"assassinate|v.暗杀；行刺",
"assault|n./v.攻击；袭击",
"assemble|v.集合；装配",
"assembly|n.集合；议会；装配",
"assert|v.断言；维护；声称",
"assess|v.评估；评定",
"asset|n.资产；宝贵的人（物）；优点",
"assign|v.分配；指派；指定",
"assignment|n.任务；作业；分配",
"assimilate|v.吸收；同化",
"assist|v.帮助；协助",
"assistance|n.帮助；援助",
"assistant|n.助手；助理 a.辅助的",
"associate|v.交往；联想 n.伙伴 a.副的",
"association|n.协会；联合；联想",
"assume|v.假定；承担；呈现",
"assumption|n.假设；承担",
"assurance|n.保证；确信；保险",
"assure|v.保证；确保；使确信",
"astonish|v.使惊讶",
"astronomy|n.天文学",
"athlete|n.运动员",
"athletic|a.运动的；运动员的",
"atmosphere|n.大气；气氛；环境",
"atom|n.原子；微粒",
"atomic|a.原子的；原子能的",
"attach|v.附上；系上；依恋",
"attack|v./n.攻击；进攻；抨击",
"attain|v.达到；获得；实现",
"attempt|v./n.尝试；试图",
"attend|v.出席；照料；注意",
"attendance|n.出席；出勤",
"attention|n.注意；关心",
"attentive|a.注意的；关心的；殷勤的",
"attitude|n.态度；看法；姿态",
"attorney|n.律师；代理人",
"attract|v.吸引；招引",
"attractive|a.有吸引力的；迷人的",
"attribute|v.把…归因于 n.属性；特征",
"auction|n./v.拍卖",
"audience|n.观众；听众；读者",
"audio|a.音频的；声音的",
"audit|n./v.审计；查账",
"August|n.八月",
"aunt|n.姑母；姨母；伯母；婶母",
"aura|n.气氛；光环；气质",
"authentic|a.真正的；可靠的；真迹的",
"author|n.作者；作家",
"authority|n.权威；当局；权力",
"automobile|n.汽车",
"automatic|a.自动的；无意识的",
"automation|n.自动化",
"autonomy|n.自治；自主；自治权",
"autumn|n.秋；秋季",
"available|a.可获得的；可用的；有空的",
"avenue|n.林荫道；大街；途径",
"average|n.平均数 a.平均的；普通的",
"avert|v.避免；转移；防止",
"aviation|n.航空；航空学",
"avoid|v.避免；躲开",
"await|v.等候；期待",
"awake|a.醒着的 v.唤醒；觉醒",
"award|n.奖；奖品 v.授予",
"aware|a.意识到的；知道的",
"away|ad.离开；远离",
"awe|n.敬畏 v.使敬畏",
"awesome|a.令人敬畏的；极好的",
"awful|a.极坏的；可怕的",
"awkward|a.尴尬的；笨拙的；难使用的",
"ax|n.斧子"
);
