/* 词库数据 2/12 · B */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"baby|n.婴儿；幼小的动物",
"bachelor|n.单身汉；学士",
"back|ad.向后 n.背部；后面 a.后面的 v.支持",
"background|n.背景；经历；后台",
"backward|a.向后的；落后的 ad.向后",
"bacon|n.熏肉；培根",
"bacteria|n.细菌",
"bad|a.坏的；严重的；腐败的",
"badge|n.徽章；标记",
"badly|ad.严重地；坏地；非常",
"badminton|n.羽毛球运动",
"baffle|v.使困惑；难住",
"bag|n.袋；包 v.装入袋中",
"baggage|n.行李",
"bail|n.保释；保释金 v.保释",
"bait|n.诱饵 v.引诱",
"bake|v.烤；烘焙",
"balance|n.平衡；余额 v.使平衡；权衡",
"balcony|n.阳台；楼厅",
"bald|a.秃头的；单调的",
"ball|n.球；舞会",
"ballet|n.芭蕾舞",
"balloon|n.气球",
"ballot|n.投票；选票 v.投票",
"ban|v./n.禁止；禁令",
"banana|n.香蕉",
"band|n.乐队；带子；一群 v.联合",
"bandage|n.绷带 v.用绷带包扎",
"bang|v.猛敲；砰地关上 n.巨响",
"bank|n.银行；岸；堆 v.存入银行",
"bankrupt|a.破产的 n.破产者 v.使破产",
"banner|n.横幅；旗帜",
"banquet|n.宴会；盛宴",
"bar|n.酒吧；条；栅栏 v.禁止；阻挡",
"barbecue|n.烧烤；烤肉野餐",
"bare|a.赤裸的；空的；仅有的",
"barely|ad.仅仅；几乎不",
"bargain|n.交易；便宜货 v.讨价还价",
"bark|v.吠叫 n.狗叫声；树皮",
"barn|n.谷仓；牲口棚",
"barometer|n.气压计；晴雨表",
"barrel|n.桶；枪管",
"barren|a.贫瘠的；不育的；无益的",
"barrier|n.障碍（物）；屏障",
"base|n.基础；基地 v.以…为基础",
"baseball|n.棒球",
"basement|n.地下室",
"basic|a.基本的；基础的",
"basically|ad.基本上；从根本上说",
"basis|n.基础；根据",
"basket|n.篮子；筐",
"basketball|n.篮球",
"bat|n.蝙蝠；球棒 v.用球棒击球",
"batch|n.一批；一组",
"bath|n.洗澡；浴缸",
"bathe|v.洗澡；沐浴；浸",
"bathroom|n.浴室；卫生间",
"battery|n.电池；一系列",
"battle|n.战役；斗争 v.作战",
"bay|n.海湾",
"beach|n.海滩；沙滩",
"beam|n.横梁；光束 v.微笑；发射",
"bean|n.豆；豆子",
"bear|v.忍受；承担；生育 n.熊",
"beard|n.胡须",
"bearing|n.举止；方位；轴承；关系",
"beast|n.野兽；凶残的人",
"beat|v.打；击败；跳动 n.节拍",
"beautiful|a.美丽的；美好的",
"beauty|n.美；美丽；美人",
"because|conj.因为",
"become|v.变成；变得",
"bed|n.床；河床；花坛",
"bee|n.蜜蜂",
"beef|n.牛肉",
"beer|n.啤酒",
"before|prep./conj.在…之前 ad.以前",
"beforehand|ad.预先；事先",
"beg|v.乞求；请求",
"begin|v.开始",
"behalf|n.利益；代表",
"behave|v.表现；举止；运转",
"behavior|n.行为；举止；性能",
"behind|prep.在…后面 ad.在后；落后",
"being|n.存在；生物；人",
"belief|n.信念；信仰；相信",
"believe|v.相信；认为",
"bell|n.铃；钟",
"belly|n.肚子；腹部",
"belong|v.属于；应归入",
"beloved|a.深爱的 n.心爱的人",
"below|prep.在…下面 ad.在下",
"belt|n.腰带；地带",
"bench|n.长凳；工作台",
"bend|v.使弯曲 n.弯；弯道",
"beneath|prep.在…之下 ad.在下方",
"beneficial|a.有益的；有利的",
"benefit|n.利益；好处 v.有益于；得益",
"benevolent|a.仁慈的；善意的",
"benign|a.良性的；和善的",
"beside|prep.在…旁边；与…相比",
"besides|ad.此外 prep.除…之外（还）",
"best|a.最好的 ad.最好地 n.最佳者",
"bet|v./n.打赌；赌注",
"betray|v.背叛；出卖；泄露",
"better|a.更好的 ad.更好地 v.改善",
"between|prep.在…之间 ad.在中间",
"beware|v.当心；谨防",
"beyond|prep.超过；在…之外 ad.在远处",
"bias|n.偏见；偏向 v.使有偏见",
"bible|n.圣经；权威典籍",
"bibliography|n.参考书目；文献目录",
"bicycle|n.自行车",
"bid|v./n.出价；投标；努力争取",
"big|a.大的；重要的",
"bill|n.账单；法案；纸币；海报",
"billion|num.十亿",
"bin|n.垃圾箱；箱柜",
"bind|v.捆绑；约束；装订",
"biography|n.传记",
"biology|n.生物学",
"bird|n.鸟",
"birth|n.出生；诞生；出身",
"birthday|n.生日",
"biscuit|n.饼干；软烤饼",
"bit|n.一点；一些；比特",
"bite|v./n.咬；叮；一口",
"bitter|a.苦的；痛苦的；严寒的",
"black|a.黑色的 n.黑色；黑人",
"blackboard|n.黑板",
"blackmail|n./v.敲诈；勒索",
"blade|n.刀刃；叶片",
"blame|v.责备 n.责任；责备",
"blank|a.空白的 n.空白（处）",
"blanket|n.毛毯；覆盖层",
"blast|n.爆炸；一阵 v.炸毁；爆破",
"blaze|n.火焰；火灾 v.燃烧；闪耀",
"bleak|a.荒凉的；黯淡的；寒冷的",
"bleed|v.流血；榨取",
"blend|v./n.混合；掺和",
"bless|v.祝福；保佑",
"blind|a.失明的；盲目的 v.使失明",
"block|n.街区；大块；阻塞 v.阻塞；阻挡",
"blood|n.血；血统",
"bloody|a.血腥的；嗜杀的",
"bloom|n./v.开花；繁荣",
"blossom|n.花 v.开花；发展",
"blouse|n.女衬衫",
"blow|v.吹；打击；爆炸 n.吹；打击",
"blue|a.蓝色的；忧郁的 n.蓝色",
"blueprint|n.蓝图；行动计划",
"blunder|n.大错 v.犯大错；跌跌撞撞",
"blunt|a.钝的；直率的 v.使钝",
"blur|v.使模糊 n.模糊不清的事物",
"blush|v./n.脸红；羞愧",
"board|n.木板；董事会 v.上（船、车、飞机）",
"boast|v./n.自夸；夸耀",
"boat|n.小船；艇",
"body|n.身体；主体；团体；物体",
"boil|v.煮沸；沸腾；激动",
"bold|a.大胆的；粗体的；醒目的",
"bolt|n.螺栓；闪电；门闩 v.用螺栓固定；逃跑",
"bomb|n.炸弹 v.轰炸",
"bond|n.纽带；债券；联结",
"bone|n.骨；骨头",
"bonus|n.奖金；红利；额外好处",
"book|n.书 v.预订",
"boom|n.繁荣；隆隆声 v.激增；迅速发展",
"boost|v.提高；推动；宣传 n.促进",
"boot|n.靴子；行李箱",
"booth|n.电话亭；货摊；小间",
"border|n.边界；边缘 v.与…接界",
"bore|v.使厌烦；钻孔 n.讨厌的人（事）",
"boring|a.无聊的；令人厌烦的",
"born|a.天生的；出生的",
"borrow|v.借；借用",
"boss|n.老板；上司 v.指挥",
"bother|v.打扰；烦扰 n.麻烦",
"bottle|n.瓶子 v.装瓶",
"bottom|n.底部；末端 a.最低的",
"bounce|v./n.弹跳；反弹",
"bound|a.一定的；有义务的 n.界限 v.跳跃",
"boundary|n.边界；分界线",
"bow|v.鞠躬 n.弓；蝴蝶结",
"bowel|n.肠；内部",
"bowl|n.碗；钵",
"box|n.箱；盒；包厢",
"boy|n.男孩",
"boycott|v./n.联合抵制；拒绝参加",
"brace|n.支架 v.使防备；支撑",
"bracket|n.括号；支架；等级",
"brain|n.大脑；脑力",
"brake|n.刹车；制动器 v.刹车",
"branch|n.树枝；分支；分部",
"brand|n.品牌；烙印 v.加烙印于",
"brandy|n.白兰地酒",
"brass|n.黄铜；铜器",
"brave|a.勇敢的",
"breach|n.违反；破裂 v.违反；突破",
"bread|n.面包",
"break|v.打破；中断；违反 n.休息；间断",
"breakdown|n.崩溃；故障；分解",
"breakfast|n.早餐",
"breast|n.胸部；乳房",
"breath|n.呼吸；气息",
"breathe|v.呼吸；轻声说",
"breed|v.繁殖；饲养 n.品种",
"breeze|n.微风；轻而易举的事",
"bribe|n./v.贿赂",
"brick|n.砖",
"bride|n.新娘",
"bridge|n.桥；桥梁 v.架桥；弥合",
"brief|a.简短的 n.摘要 v.简报",
"briefcase|n.公文包",
"bright|a.明亮的；聪明的；欢快的",
"brilliant|a.杰出的；明亮的；灿烂的",
"brim|n.边缘；帽檐 v.充满",
"bring|v.带来；引起；促使",
"brisk|a.轻快的；兴隆的；凉爽的",
"broad|a.宽的；广泛的；宽宏的",
"broadcast|v./n.广播；播放",
"broaden|v.放宽；扩大",
"brochure|n.小册子",
"bronze|n.青铜；铜牌 a.青铜色的",
"brook|n.小溪",
"broom|n.扫帚",
"brother|n.兄弟；同胞",
"brow|n.眉毛；额头",
"brown|a.棕色的 n.棕色",
"browse|v.浏览；吃草",
"bruise|n.瘀伤 v.挫伤；打伤",
"brush|n.刷子；画笔 v.刷；轻触",
"brutal|a.残忍的；野蛮的",
"bubble|n.气泡；泡 v.冒泡",
"bucket|n.水桶；吊桶",
"budget|n.预算 v.编预算 a.廉价的",
"buffet|n.自助餐；餐具柜 v.打击",
"bug|n.臭虫；小虫；故障；窃听器 v.窃听",
"build|v.建造；建立 n.体格",
"building|n.建筑物；建造",
"bulb|n.电灯泡；球茎",
"bulk|n.体积；大批；大部分",
"bull|n.公牛",
"bullet|n.子弹",
"bulletin|n.公告；新闻快报",
"bump|v.碰撞 n.碰撞；肿块",
"bunch|n.一束；一群",
"bundle|n.捆；包；一批",
"burden|n.负担；重担 v.使负担",
"bureau|n.局；处；办公署",
"bureaucracy|n.官僚主义；官僚机构",
"burglar|n.窃贼；夜盗",
"burn|v.燃烧；烧毁 n.烧伤",
"burst|v.爆裂；突然发作 n.爆发",
"bury|v.埋葬；掩埋；隐藏",
"bus|n.公共汽车",
"bush|n.灌木；灌木丛",
"business|n.商业；生意；事务；公司",
"busy|a.忙的；繁忙的",
"but|conj.但是 prep.除…以外",
"butcher|n.屠夫；肉商 v.屠宰；残杀",
"butter|n.黄油 v.涂黄油",
"butterfly|n.蝴蝶",
"button|n.纽扣；按钮 v.扣紧",
"buy|v.买；购买；相信",
"buzz|v.发出嗡嗡声 n.嗡嗡声；兴奋",
"by|prep.通过；被；截至 ad.经过",
"bypass|n.旁路 v.绕过；回避"
);
