/* 词库数据 15/16 · U + V + W + XYZ */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"ugly|a.丑陋的；难看的",
"ultimate|a.最终的；根本的",
"umbrella|n.雨伞；保护",
"unable|a.不能的；不会的",
"unanimous|a.一致的；无异议的",
"unbearable|a.难以忍受的",
"uncertain|a.不确定的；无常的",
"uncle|n.叔叔；伯父；舅父",
"uncover|v.揭露；发现",
"under|prep.在…下面 ad.在下",
"undergo|v.经历；承受",
"undergraduate|n.本科生",
"underground|a.地下的 ad.在地下 n.地铁",
"underline|v.强调；在…下画线",
"underlie|v.构成…的基础；位于…之下",
"undermine|v.削弱；暗中破坏",
"understand|v.理解；听说",
"understanding|n.理解；谅解 a.通情达理的",
"undertake|v.承担；从事；承诺",
"undo|v.解开；取消；使失败",
"undoubtedly|ad.无疑；肯定",
"uneasy|a.不安的；担心的",
"unemployment|n.失业；失业率",
"unexpected|a.意外的；想不到的",
"unfair|a.不公平的",
"unfold|v.展开；呈现",
"unfortunate|a.不幸的；遗憾的",
"unfortunately|ad.不幸地；遗憾地",
"uniform|n.制服 a.统一的",
"unify|v.统一；使一致",
"union|n.联盟；工会；结合",
"unique|a.独特的；唯一的",
"unit|n.单位；单元",
"unite|v.联合；团结",
"universal|a.普遍的；全世界的",
"universe|n.宇宙；天地万物",
"university|n.大学",
"unless|conj.除非",
"unlike|a.不同的 prep.不像",
"unlikely|a.不太可能的",
"until|prep./conj.直到",
"unusual|a.不寻常的；罕见的",
"up|ad.向上 prep.沿…向上",
"update|v.更新 n.更新；最新消息",
"upgrade|v.升级；提升",
"uphold|v.维护；支持",
"upon|prep.在…之上；一…就",
"upper|a.上面的；较高的",
"upset|v.使心烦；打翻 a.难过的",
"upside|n.上面；好处",
"upstairs|ad.在楼上 a.楼上的",
"up-to-date|a.最新的；时髦的",
"upward|a.向上的 ad.向上",
"urban|a.城市的；都市的",
"urge|v.催促；力劝 n.强烈欲望",
"urgent|a.紧急的；急迫的",
"us|pron.我们（宾格）",
"usage|n.用法；使用",
"use|v.使用 n.用途；使用权",
"used|a.用过的；习惯于…的",
"useful|a.有用的；有益的",
"useless|a.无用的；无效的",
"user|n.用户；使用者",
"usual|a.通常的；惯常的",
"usually|ad.通常；平常",
"utility|n.效用；公用事业",
"utilize|v.利用；使用",
"utmost|a.极度的 n.极限",
"utter|v.说出 a.完全的",
"vacant|a.空着的；茫然的",
"vacation|n.假期；休假",
"vaccine|n.疫苗",
"vacuum|n.真空；真空吸尘器",
"vague|a.模糊的；含糊的",
"vain|a.徒劳的；自负的",
"valid|a.有效的；有根据的",
"valley|n.山谷；流域",
"valuable|a.贵重的；有价值的 n.贵重物品",
"value|n.价值；价值观 v.重视",
"van|n.厢式货车",
"vanish|v.消失；突然不见",
"vapor|n.蒸气；水汽",
"variable|n.变量 a.多变的",
"variation|n.变化；变异",
"variety|n.种类；多样化",
"various|a.各种各样的",
"vary|v.变化；不同",
"vast|a.巨大的；辽阔的",
"vegetable|n.蔬菜",
"vehicle|n.交通工具；车辆",
"veil|n.面纱；遮盖物",
"venture|n.冒险；企业 v.敢于",
"verb|n.动词",
"verbal|a.口头的；言语的",
"verdict|n.裁决；判决",
"verify|v.核实；证明",
"verse|n.诗句；诗",
"version|n.版本；说法",
"versus|prep.对；对抗",
"vertical|a.垂直的；纵向的",
"very|ad.很；非常 a.正是的",
"vessel|n.船；容器；血管",
"veteran|n.老兵；老手",
"veto|n./v.否决；否决权",
"via|prep.经由；通过",
"vibrate|v.振动；颤动",
"vice|n.恶习；缺点 a.副的",
"victim|n.受害者；牺牲品",
"victory|n.胜利",
"video|n.视频；录像",
"view|n.观点；景色 v.观看",
"viewpoint|n.观点；视角",
"vigorous|a.有力的；精力充沛的",
"village|n.村庄",
"violence|n.暴力；猛烈",
"violent|a.暴力的；猛烈的",
"virtual|a.虚拟的；实际上的",
"virtue|n.美德；优点",
"virus|n.病毒",
"visa|n.签证",
"visible|a.看得见的；明显的",
"vision|n.视力；视野；远见",
"visit|v./n.参观；访问",
"visitor|n.参观者；游客",
"visual|a.视觉的",
"vital|a.至关重要的；生命的",
"vitamin|n.维生素",
"vivid|a.生动的；鲜艳的",
"voice|n.声音；意见 v.表达",
"volcano|n.火山",
"volleyball|n.排球",
"volume|n.体积；音量；卷；量",
"voluntary|a.自愿的；志愿的",
"volunteer|n.志愿者 v.自愿做",
"vote|v./n.投票；表决",
"voyage|n.航行；航海",
"wage|n.工资 v.发动（战争）",
"wagon|n.四轮马车；货车",
"waist|n.腰；腰部",
"wait|v.等待；等候 n.等待",
"waiter|n.服务员；侍者",
"waitress|n.女服务员",
"wake|v.醒来；唤醒",
"walk|v.走 n.步行；散步",
"wall|n.墙；墙壁",
"wallet|n.钱包",
"wander|v.漫步；走神",
"want|v.想要；需要 n.缺乏",
"war|n.战争；斗争",
"warehouse|n.仓库；货栈",
"warfare|n.战争；冲突",
"warm|a.温暖的 v.使变暖",
"warmth|n.温暖；热情",
"warn|v.警告；提醒",
"warning|n.警告；预兆",
"wash|v.洗 n.洗；洗涤",
"waste|v.浪费 n.浪费；废弃物",
"watch|v.观看；注意 n.手表",
"water|n.水 v.浇水",
"waterfall|n.瀑布",
"waterproof|a.防水的",
"wave|n.波浪；挥手 v.挥手",
"way|n.方法；路；方面",
"we|pron.我们",
"weak|a.虚弱的；弱的",
"weakness|n.虚弱；弱点",
"wealth|n.财富；丰富",
"wealthy|a.富有的",
"weapon|n.武器",
"wear|v.穿着；磨损",
"weather|n.天气",
"weave|v.编织；编造",
"web|n.网络；蛛网",
"wedding|n.婚礼",
"wednesday|n.星期三",
"weed|n.杂草 v.除草",
"week|n.星期；周",
"weekday|n.工作日",
"weekend|n.周末",
"weigh|v.称重量；权衡",
"weight|n.重量；重担",
"weird|a.奇怪的；怪异的",
"welcome|v./n.欢迎 a.受欢迎的",
"welfare|n.福利；幸福",
"well|ad.好 a.健康的 n.井",
"well-known|a.著名的",
"west|n.西方 a.西方的",
"western|a.西方的；西部的",
"wet|a.湿的；多雨的",
"whale|n.鲸",
"what|pron.什么 a.什么的",
"whatever|pron.无论什么",
"wheat|n.小麦",
"wheel|n.轮子；方向盘",
"when|ad.什么时候 conj.当…时",
"whenever|conj.无论何时",
"where|ad.在哪里 conj.在…的地方",
"whereas|conj.然而；鉴于",
"wherever|conj.无论在哪里",
"whether|conj.是否；不管",
"which|pron.哪一个",
"while|conj.当…时；然而 n.一会儿",
"whisper|v./n.低语；耳语",
"whistle|n.哨子；哨声 v.吹哨",
"white|a.白色的 n.白色",
"who|pron.谁",
"whoever|pron.无论谁",
"whole|a.全部的 n.全部",
"wholly|ad.完全地；全部",
"whom|pron.谁（宾格）",
"whose|pron.谁的",
"why|ad.为什么",
"wicked|a.邪恶的；淘气的",
"wide|a.宽的；广泛的",
"widely|ad.广泛地；大大地",
"widen|v.加宽；扩大",
"widespread|a.普遍的；广泛的",
"widow|n.寡妇",
"width|n.宽度；广度",
"wife|n.妻子",
"wild|a.野生的；狂热的",
"wildlife|n.野生动物",
"will|v.aux.将 n.意志；遗嘱",
"willing|a.愿意的；乐意的",
"win|v.赢；获得 n.胜利",
"wind|n.风 v.蜿蜒；上发条",
"window|n.窗户；窗口",
"wine|n.葡萄酒；酒",
"wing|n.翅膀；侧楼",
"winter|n.冬天；冬季",
"wipe|v.擦；抹",
"wire|n.电线；金属丝",
"wisdom|n.智慧；才智",
"wise|a.明智的；聪明的",
"wish|v.希望 n.愿望",
"with|prep.和…一起；用；带有",
"withdraw|v.撤回；取款；退出",
"within|prep.在…之内 ad.在内",
"without|prep.没有；不带",
"withstand|v.承受；抵御",
"witness|n.目击者；证据 v.目击",
"wolf|n.狼",
"woman|n.女人；妇女",
"wonder|v.想知道；惊讶 n.惊奇；奇迹",
"wonderful|a.极好的；精彩的",
"wood|n.木材；树林",
"wooden|a.木制的；呆板的",
"wool|n.羊毛；毛线",
"word|n.单词；话；消息",
"work|v.工作；起作用 n.工作；作品",
"worker|n.工人；工作者",
"workshop|n.车间；研讨会",
"world|n.世界；领域",
"worldwide|a.全世界的 ad.在世界各地",
"worm|n.虫；蠕虫",
"worry|v./n.担心；烦恼",
"worse|a.更坏的 ad.更糟",
"worship|n./v.崇拜；敬仰",
"worst|a.最坏的 ad.最糟",
"worth|a.值得…的 n.价值",
"worthwhile|a.值得做的",
"worthy|a.值得的；配得上的",
"would|v.aux.将；会；愿意",
"wound|n.伤口 v.使受伤",
"wrap|v.包；裹 n.披肩",
"wreck|n.失事；残骸 v.破坏",
"wrist|n.手腕",
"write|v.写；写作",
"writer|n.作家；作者",
"writing|n.写作；文章",
"wrong|a.错误的；不道德的 n.错误",
"x-ray|n.X射线；X光",
"yacht|n.游艇；快艇",
"yard|n.院子；码",
"yawn|v./n.打哈欠",
"year|n.年；年份",
"yearly|a.每年的 ad.每年",
"yell|v./n.大叫；叫喊",
"yellow|a.黄色的 n.黄色",
"yes|ad.是；是的",
"yesterday|ad./n.昨天",
"yet|ad.还；仍然 conj.然而",
"yield|v.出产；屈服 n.产量",
"you|pron.你；你们",
"young|a.年轻的 n.年轻人",
"your|pron.你的；你们的",
"yours|pron.你的（东西）",
"yourself|pron.你自己",
"youth|n.青春；青年时期；年轻人",
"zero|num.零 n.零",
"zone|n.地区；区域",
"zoo|n.动物园"
);
