/* 词库数据 11/12 · O + P */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"oak|n.橡树；橡木",
"oar|n.桨；橹",
"obedience|n.服从；顺从",
"obedient|a.服从的；顺从的",
"obey|v.服从；听从",
"object|n.物体；对象 v.反对",
"objection|n.反对；异议",
"objective|n.目标 a.客观的",
"obligation|n.义务；责任",
"oblige|v.迫使；施恩于",
"obscure|a.模糊的；不出名的 v.使模糊",
"observation|n.观察；评论",
"observe|v.观察；遵守；庆祝",
"obsession|n.痴迷；念念不忘",
"obsolete|a.过时的；废弃的",
"obstacle|n.障碍（物）",
"obtain|v.获得；得到",
"obvious|a.明显的；显然的",
"occasion|n.场合；时机",
"occasional|a.偶尔的；临时的",
"occupation|n.职业；占领；消遣",
"occupy|v.占据；占领；使忙于",
"occur|v.发生；出现；想起",
"occurrence|n.发生的事；事件",
"ocean|n.海洋；大海",
"october|n.十月",
"odd|a.奇数的；奇怪的；单只的",
"odds|n.可能性；几率",
"of|prep.…的；关于",
"off|ad.离开 prep.从…离开",
"offend|v.冒犯；违犯",
"offense|n.冒犯；犯规；进攻",
"offensive|a.冒犯的；进攻性的 n.攻势",
"offer|v.提供；提出 n.出价",
"office|n.办公室；职务",
"officer|n.军官；警官；官员",
"official|a.官方的 n.官员",
"offset|v.抵消；补偿",
"often|ad.经常；常常",
"oil|n.油；石油 v.加油",
"okay|a.好的 ad.可以",
"old|a.旧的；年老的；…岁的",
"omit|v.省略；遗漏",
"on|prep.在…上；关于 ad.继续",
"once|ad.一次；曾经 conj.一旦",
"one|num.一 pron.一个人",
"oneself|pron.自己；亲自",
"onion|n.洋葱",
"only|ad.只 a.唯一的 conj.但是",
"onto|prep.到…上面",
"open|a.开的；开放的 v.打开",
"opening|n.开口；开始；空缺",
"opera|n.歌剧",
"operate|v.操作；运转；做手术",
"operation|n.操作；手术；运转",
"operational|a.运转的；操作上的",
"operator|n.操作员；经营者",
"opinion|n.意见；看法",
"opponent|n.对手；反对者",
"opportunity|n.机会；良机",
"oppose|v.反对；反抗",
"opposite|a.相反的 prep.在…对面",
"oppress|v.压迫；压抑",
"opt|v.选择",
"optical|a.光学的；视觉的",
"optimistic|a.乐观的",
"option|n.选择；选项",
"optional|a.可选择的；选修的",
"or|conj.或者；否则",
"oral|a.口头的；口部的",
"orange|n.橙；橘 a.橙色的",
"orbit|n.轨道 v.沿轨道运行",
"orchard|n.果园",
"orchestra|n.管弦乐队",
"order|n.命令；秩序；订单 v.命令",
"orderly|a.整齐的；有秩序的",
"ordinary|a.普通的；平凡的",
"organ|n.器官；管风琴；机构",
"organic|a.有机的；器官的",
"organism|n.生物体；有机体",
"organization|n.组织；机构",
"organize|v.组织；整理",
"orient|v.使适应；定向 n.东方",
"orientation|n.方向；定向；迎新",
"origin|n.起源；出身",
"original|a.最初的；原创的 n.原作",
"originate|v.起源于；发起",
"ornament|n.装饰品 v.装饰",
"orphan|n.孤儿",
"other|a.其他的 pron.另一个",
"otherwise|ad.否则；另外 conj.要不然",
"ought|v.aux.应当；应该",
"ounce|n.盎司",
"our|pron.我们的",
"ours|pron.我们的（东西）",
"ourselves|pron.我们自己",
"out|ad.出去；在外",
"outbreak|n.爆发；突然发生",
"outcome|n.结果；结局",
"outdoor|a.户外的；野外的",
"outer|a.外面的；外层的",
"outfit|n.全套服装；装备",
"outlet|n.出口；经销店；发泄途径",
"outline|n.大纲；轮廓 v.概述",
"outlook|n.观点；前景；景色",
"output|n.产量；输出",
"outrage|n.愤怒；暴行 v.激怒",
"outset|n.开始；开端",
"outside|ad.在外面 prep.在…外面",
"outstanding|a.杰出的；未解决的",
"outward|a.向外的 ad.向外",
"oval|a.椭圆的 n.椭圆形",
"oven|n.烤箱；炉",
"over|prep.超过；在…上方 ad.结束",
"overall|a.全面的 ad.总的来说",
"overcome|v.克服；战胜",
"overflow|v.溢出；泛滥",
"overhead|ad.在头顶上 a.头顶上的",
"overhear|v.无意听到；偷听",
"overlap|v./n.重叠；交叠",
"overlook|v.忽视；俯视",
"oversee|v.监督；监管",
"overwhelm|v.压倒；淹没；使不知所措",
"overwhelming|a.压倒性的；势不可挡的",
"owe|v.欠；把…归功于",
"owing|a.应付的；未付的",
"owl|n.猫头鹰",
"own|a.自己的 v.拥有",
"owner|n.所有者；主人",
"oxide|n.氧化物",
"oxygen|n.氧；氧气",
"pace|n.步伐；速度 v.踱步",
"pack|v.打包；挤满 n.包；一群",
"package|n.包裹；包 v.包装",
"packet|n.小包；小袋",
"pact|n.协定；条约",
"pad|n.垫子；便笺本",
"paddle|n.桨 v.划桨",
"page|n.页；网页",
"pain|n.疼痛；痛苦",
"painful|a.疼痛的；痛苦的",
"paint|n.油漆；颜料 v.油漆；绘画",
"painter|n.画家；油漆匠",
"painting|n.绘画；油画",
"pair|n.一对；一双 v.配对",
"palace|n.宫殿；王宫",
"pale|a.苍白的；浅色的",
"palm|n.手掌；棕榈树",
"pan|n.平底锅",
"panda|n.熊猫",
"panel|n.面板；专门小组",
"panic|n./v.恐慌；惊慌",
"panorama|n.全景；概述",
"paper|n.纸；论文；报纸",
"paperback|n.平装本",
"parade|n.游行；检阅 v.游行",
"paradise|n.天堂；乐园",
"paradox|n.悖论；自相矛盾",
"paragraph|n.段落",
"parallel|a.平行的；类似的 n.相似处",
"parcel|n.包裹；小包",
"pardon|v./n.原谅；赦免",
"parent|n.父亲（母亲）；父母",
"park|n.公园 v.停车",
"parliament|n.议会；国会",
"part|n.部分；角色；零件 v.分开",
"partial|a.部分的；偏袒的",
"participate|v.参与；参加",
"participation|n.参与；参加",
"particle|n.颗粒；粒子",
"particular|a.特别的；挑剔的 n.细节",
"particularly|ad.特别；尤其",
"partner|n.伙伴；搭档；配偶",
"partnership|n.合伙关系；伙伴关系",
"party|n.聚会；政党；一方",
"pass|v.通过；传递 n.通行证",
"passage|n.段落；通道；通过",
"passenger|n.乘客；旅客",
"passion|n.激情；热情",
"passive|a.被动的；消极的",
"passport|n.护照",
"past|a.过去的 n.过去 prep.经过",
"paste|n.糊；酱 v.粘贴",
"pastime|n.消遣；娱乐",
"pat|v./n.轻拍",
"patch|n.补丁；小块土地 v.修补",
"patent|n.专利 a.明显的",
"path|n.小路；路径",
"pathetic|a.可怜的；悲哀的",
"patience|n.耐心；忍耐",
"patient|a.耐心的 n.病人",
"patriotic|a.爱国的",
"patrol|v./n.巡逻",
"patron|n.赞助人；老主顾",
"pattern|n.模式；图案 v.模仿",
"pause|v./n.暂停；中止",
"pave|v.铺（路）；为…作准备",
"pavement|n.人行道",
"paw|n.爪子",
"pay|v.支付；付费 n.工资",
"payment|n.支付；付款",
"peace|n.和平；平静",
"peaceful|a.和平的；平静的",
"peach|n.桃子",
"peak|n.顶峰 a.高峰的 v.达到高峰",
"peanut|n.花生",
"pear|n.梨",
"pearl|n.珍珠",
"peasant|n.农民；小农",
"peculiar|a.奇怪的；特有的",
"pedal|n.踏板 v.踩踏板",
"pedestrian|n.行人 a.行人的",
"peel|v.剥皮 n.果皮",
"peer|n.同龄人 v.凝视",
"pen|n.钢笔",
"penalty|n.处罚；点球",
"pencil|n.铅笔",
"pendulum|n.钟摆；摇摆不定的事",
"penetrate|v.渗透；看穿",
"penny|n.便士；分",
"pension|n.养老金；退休金",
"people|n.人们；民族",
"pepper|n.胡椒；辣椒",
"per|prep.每；经",
"perceive|v.察觉；感知；理解",
"percent|n.百分之…",
"percentage|n.百分比；百分率",
"perception|n.感知；看法",
"perfect|a.完美的 v.使完美",
"perfection|n.完美；完善",
"perform|v.执行；表演",
"performance|n.表现；演出；性能",
"perfume|n.香水；芳香",
"perhaps|ad.也许；可能",
"period|n.时期；周期；句号",
"periodic|a.周期的；定期的",
"perish|v.死亡；毁灭；腐朽",
"permanent|a.永久的；长期的",
"permission|n.许可；允许",
"permit|v.允许 n.许可证",
"perpetual|a.永久的；不断的",
"perplex|v.使困惑",
"persist|v.坚持；持续",
"persistence|n.坚持；持续",
"person|n.人；本人",
"personal|a.个人的；私人的",
"personality|n.个性；名人",
"personnel|n.人员；人事部门",
"perspective|n.观点；前景；透视",
"persuade|v.说服；劝服",
"persuasion|n.说服；信念",
"pessimistic|a.悲观的",
"pet|n.宠物 a.宠爱的",
"petition|n.请愿书；诉状 v.请愿",
"petrol|n.汽油",
"petroleum|n.石油",
"phase|n.阶段；时期；相位",
"phenomenon|n.现象；奇才",
"philosophy|n.哲学；人生观",
"phone|n.电话 v.打电话",
"photograph|n.照片 v.拍照",
"phrase|n.短语；措辞",
"physical|a.身体的；物质的；物理的",
"physician|n.内科医生",
"physicist|n.物理学家",
"physics|n.物理学",
"piano|n.钢琴",
"pick|v.挑选；采摘",
"pickup|n.小型货车；接人；拾起",
"picnic|n.野餐 v.去野餐",
"picture|n.图画；照片 v.想象",
"pie|n.馅饼",
"piece|n.块；件；篇",
"pier|n.码头；防波堤",
"pigeon|n.鸽子",
"pile|n.堆 v.堆积",
"pilgrim|n.朝圣者",
"pill|n.药丸",
"pillar|n.柱子；支柱",
"pillow|n.枕头",
"pilot|n.飞行员 a.试验性的",
"pin|n.别针 v.钉住",
"pinch|v.捏；掐 n.捏；一撮",
"pine|n.松树",
"pink|a.粉红色的 n.粉红色",
"pint|n.品脱",
"pioneer|n.先驱；开拓者 v.开创",
"pipeline|n.管道；管线",
"pirate|n.海盗；盗版者 v.盗版",
"pistol|n.手枪",
"pit|n.坑；矿井",
"pitch|v.投掷；搭（帐篷）n.球场；音高",
"pity|n.怜悯；遗憾 v.同情",
"pizza|n.比萨饼",
"place|n.地方；名次 v.放置",
"plague|n.瘟疫；灾害 v.困扰",
"plain|a.简单的；朴素的 n.平原",
"plan|n.计划 v.计划；打算",
"plane|n.飞机；平面",
"planet|n.行星",
"plant|n.植物；工厂 v.种植",
"plantation|n.种植园",
"plaster|n.石膏；灰泥",
"plastic|n.塑料 a.塑料的",
"plate|n.盘子；板 v.电镀",
"plateau|n.高原；稳定期",
"platform|n.平台；站台；讲台",
"plausible|a.貌似合理的；可信的",
"play|v.玩；播放；扮演 n.戏剧",
"player|n.运动员；播放器",
"playground|n.操场；游乐场",
"plea|n.恳求；答辩",
"plead|v.恳求；辩护",
"pleasant|a.令人愉快的",
"please|v.使高兴 int.请",
"pleasure|n.快乐；乐事",
"pledge|n./v.保证；誓言",
"plentiful|a.丰富的；充足的",
"plenty|n.丰富；大量",
"plight|n.困境；苦境",
"plot|n.情节；阴谋；小块地 v.密谋",
"plow|n.犁 v.犁地",
"plug|n.插头；塞子 v.堵住",
"plunge|v.跳入；骤降 n.跳入",
"plural|a.复数的 n.复数",
"plus|prep.加上 a.正的 n.加号",
"pneumonia|n.肺炎",
"pocket|n.口袋 a.袖珍的",
"poem|n.诗",
"poet|n.诗人",
"poetry|n.诗歌；诗集",
"point|n.点；观点 v.指向",
"poison|n.毒药 v.毒害",
"poisonous|a.有毒的；恶毒的",
"polar|a.极地的；完全相反的",
"pole|n.极；杆",
"police|n.警察；警方",
"policeman|n.男警察",
"policy|n.政策；方针；保险单",
"polish|v.擦亮；润色 n.上光剂",
"polite|a.有礼貌的；客气的",
"political|a.政治的",
"politician|n.政治家；政客",
"politics|n.政治；政治学",
"poll|n.民意测验 v.投票",
"pollute|v.污染；弄脏",
"pollution|n.污染",
"pond|n.池塘",
"ponder|v.思考；沉思",
"pool|n.水池；共用资源 v.汇集",
"poor|a.贫穷的；差的；可怜的",
"pop|a.流行的 n.流行音乐 v.突然出现",
"popular|a.受欢迎的；流行的",
"popularity|n.受欢迎；普及",
"population|n.人口；群体",
"porch|n.门廊",
"pork|n.猪肉",
"port|n.港口；端口",
"portable|a.便携的；手提的",
"porter|n.搬运工；门卫",
"portion|n.一部分；一份",
"portrait|n.肖像；描写",
"portray|v.描绘；扮演",
"pose|v.摆姿势；提出 n.姿势",
"position|n.位置；职位；立场",
"positive|a.积极的；肯定的；正的",
"possess|v.拥有；具有",
"possession|n.拥有；财产",
"possibility|n.可能性",
"possible|a.可能的",
"postage|n.邮资；邮费",
"poster|n.海报；招贴",
"postpone|v.推迟；延期",
"potential|a.潜在的 n.潜力",
"poultry|n.家禽；禽肉",
"pound|n.磅；英镑 v.猛击",
"pour|v.倒；灌；倾泻",
"poverty|n.贫穷；缺乏",
"powder|n.粉末；火药",
"power|n.力量；权力；动力",
"powerful|a.强大的；有权力的",
"practical|a.实际的；实用的",
"practically|ad.几乎；实际上",
"practice|n.实践；练习；惯例",
"praise|v./n.赞扬；称赞",
"pray|v.祈祷；祈求",
"prayer|n.祈祷；祷告",
"preach|v.布道；宣扬",
"precede|v.先于；在…之前",
"precedent|n.先例；惯例",
"precious|a.宝贵的；珍贵的",
"precise|a.精确的；确切的",
"precision|n.精确；精密度",
"predict|v.预测；预言",
"prediction|n.预测；预言",
"predominant|a.占主导的；显著的",
"preface|n.序言；前言",
"prefer|v.更喜欢；宁愿",
"preference|n.偏爱；优先",
"pregnant|a.怀孕的；意味深长的",
"prejudice|n.偏见 v.使有偏见",
"preliminary|a.初步的 n.准备工作",
"premier|n.总理 a.首要的",
"premise|n.前提；假设",
"premium|n.保险费；奖金 a.优质的",
"prepare|v.准备；配制",
"preposition|n.介词",
"prescribe|v.开药方；规定",
"presence|n.出席；存在",
"present|a.现在的 n.礼物；现在 v.呈现",
"preserve|v.保护；保存；保鲜",
"preside|v.主持；主管",
"president|n.总统；校长；主席",
"press|v.压；按；催促 n.新闻界",
"pressure|n.压力 v.施压",
"prestige|n.威望；声望",
"pretend|v.假装；装扮",
"pretty|ad.相当 a.漂亮的",
"prevail|v.盛行；获胜",
"prevent|v.防止；阻止",
"previous|a.以前的；先前的",
"prey|n.猎物 v.捕食",
"price|n.价格；代价 v.定价",
"pride|n.自豪；骄傲",
"priest|n.牧师；神父",
"primary|a.首要的；初级的",
"prime|a.主要的；最好的 n.全盛时期",
"primitive|a.原始的；简陋的",
"prince|n.王子；亲王",
"princess|n.公主；王妃",
"principal|a.主要的 n.校长",
"principle|n.原则；原理",
"print|v.印刷；打印 n.字体",
"prior|a.优先的；在先的",
"priority|n.优先；优先事项",
"prison|n.监狱",
"prisoner|n.囚犯；俘虏",
"privacy|n.隐私；独处",
"private|a.私人的；私下的",
"privilege|n.特权；优惠",
"prize|n.奖赏 v.珍惜",
"probability|n.可能性；概率",
"probable|a.很可能的",
"problem|n.问题；难题",
"procedure|n.程序；手续",
"proceed|v.继续进行；开始",
"process|n.过程；工序 v.加工",
"procession|n.队伍；行列",
"proclaim|v.宣布；声明",
"produce|v.生产；引起 n.农产品",
"product|n.产品；产物",
"production|n.生产；产量；作品",
"productive|a.多产的；富有成效的",
"profession|n.职业；同行",
"professional|a.专业的 n.专业人员",
"professor|n.教授",
"proficiency|n.熟练；精通",
"profile|n.侧面；简介；轮廓",
"profit|n.利润；收益 v.获利",
"profitable|a.有利可图的；有益的",
"profound|a.深刻的；渊博的",
"program|n.程序；节目；计划",
"progress|n./v.进步；前进",
"prohibit|v.禁止；阻止",
"project|n.项目；工程 v.投掷；预计",
"prolong|v.延长；拖延",
"prominent|a.著名的；显著的",
"promise|v./n.承诺；有前途",
"promising|a.有前途的；有希望的",
"promote|v.促进；提升；推销",
"prompt|a.迅速的 v.促使；提示",
"prone|a.易于…的；俯卧的",
"pronoun|n.代词",
"pronounce|v.发音；宣布",
"pronunciation|n.发音",
"proof|n.证明；证据 a.耐…的",
"propaganda|n.宣传；鼓吹",
"propel|v.推进；推动",
"proper|a.适当的；正确的",
"property|n.财产；房产；性质",
"proportion|n.比例；部分",
"proposal|n.建议；求婚",
"propose|v.提议；打算；求婚",
"prospect|n.前景；可能性",
"prosper|v.繁荣；成功",
"prosperity|n.繁荣；昌盛",
"protect|v.保护；防护",
"protein|n.蛋白质",
"protest|v./n.抗议；反对",
"proud|a.自豪的；骄傲的",
"prove|v.证明；证实",
"provide|v.提供；规定",
"provided|conj.假如；只要",
"province|n.省；领域",
"provision|n.提供；条款；准备",
"provoke|v.激怒；引起",
"prudent|a.谨慎的；精明的",
"psychology|n.心理学；心理",
"public|a.公共的；公开的 n.公众",
"publication|n.出版；出版物",
"publicity|n.宣传；公众的关注",
"publish|v.出版；发表",
"pudding|n.布丁",
"pull|v.拉；拖 n.拉；引力",
"pulse|n.脉搏；脉冲",
"pump|n.泵 v.抽水；打气",
"punch|v.用拳猛击 n.拳打；感染力",
"punctual|a.准时的；守时的",
"punish|v.惩罚；处罚",
"punishment|n.惩罚；处罚",
"pupil|n.学生；瞳孔",
"purchase|v.购买 n.购买；购买物",
"pure|a.纯的；纯洁的；完全的",
"purify|v.净化；提纯",
"purple|a.紫色的 n.紫色",
"purpose|n.目的；用途",
"purse|n.钱包",
"pursue|v.追求；追赶；从事",
"pursuit|n.追求；追赶；事业",
"push|v.推；催促 n.推",
"put|v.放；表达；使处于",
"puzzle|n.谜；难题 v.使困惑",
"pyramid|n.金字塔；锥形"
);
