/* 词库数据 4/12 · C (o–z) */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"clerk|n.职员；办事员",
"clever|a.聪明的；机敏的",
"click|v./n.点击；发出咔嗒声",
"client|n.客户；委托人",
"cliff|n.悬崖；峭壁",
"climate|n.气候；风气",
"climax|n.高潮；顶点",
"climb|v./n.攀登；爬",
"cling|v.紧紧抓住；依附；坚持",
"clinic|n.诊所；门诊部",
"clip|n.夹子；剪辑 v.夹住；修剪",
"cloak|n.斗篷；掩盖 v.遮掩",
"clock|n.钟；时钟",
"clockwise|a./ad.顺时针方向的（地）",
"clone|n./v.克隆；无性繁殖",
"close|v.关闭 a.近的；亲密的 ad.接近",
"closely|ad.紧密地；仔细地",
"cloth|n.布；织物",
"clothe|v.给…穿衣；覆盖",
"clothes|n.衣服；服装",
"clothing|n.服装；衣着",
"cloud|n.云；云状物；阴影",
"cloudy|a.多云的；模糊的",
"club|n.俱乐部；棍棒",
"clue|n.线索；提示",
"clumsy|a.笨拙的；不灵巧的",
"cluster|n.簇；群 v.聚集",
"clutch|v.抓住 n.离合器；紧握",
"coach|n.教练；长途汽车 v.训练",
"coal|n.煤",
"coalition|n.联盟；联合",
"coarse|a.粗糙的；粗俗的",
"coast|n.海岸；海滨",
"coat|n.外套；表皮；涂层 v.涂上",
"cocaine|n.可卡因",
"code|n.代码；法典；密码",
"coffee|n.咖啡",
"cognitive|a.认知的；认识的",
"coherent|a.连贯的；一致的",
"cohesive|a.有凝聚力的；结合的",
"coil|v.盘绕 n.线圈",
"coin|n.硬币 v.创造（新词）",
"coincide|v.相符；同时发生",
"coincidence|n.巧合；一致",
"collaboration|n.合作；协作",
"collapse|v./n.倒塌；崩溃；暴跌",
"collar|n.衣领",
"colleague|n.同事；同僚",
"collect|v.收集；聚集；接走",
"collection|n.收藏品；收集",
"collective|a.集体的 n.集体",
"college|n.学院；大学",
"collide|v.碰撞；冲突",
"collision|n.碰撞；冲突",
"colonial|a.殖民的；殖民地的",
"colony|n.殖民地；聚居地",
"color|n.颜色；颜料 v.给…着色",
"column|n.圆柱；专栏；列",
"comb|n.梳子 v.梳理；搜寻",
"combat|n./v.战斗；搏斗",
"combination|n.结合；组合",
"combine|v.结合；联合",
"come|v.来；变成；达到",
"comedy|n.喜剧；喜剧性",
"comet|n.彗星",
"comfort|n.舒适；安慰 v.安慰",
"comfortable|a.舒适的；宽裕的",
"comic|a.喜剧的；滑稽的 n.连环画",
"command|v./n.命令；指挥；掌握",
"commemorate|v.纪念；庆祝",
"commend|v.称赞；推荐",
"comment|n./v.评论；意见",
"commerce|n.商业；贸易",
"commercial|a.商业的 n.商业广告",
"commission|n.委员会；佣金；委托 v.委托",
"commit|v.犯（罪）；承诺；投入",
"commitment|n.承诺；投入；奉献",
"committee|n.委员会",
"commodity|n.商品；日用品",
"common|a.常见的；共同的；普通的",
"commonplace|a.平凡的 n.老生常谈",
"commonwealth|n.联邦；共和国",
"communicate|v.交流；传达；相通",
"communication|n.交流；通信；交通",
"communism|n.共产主义",
"community|n.社区；社会；群体",
"commute|v.通勤；减刑 n.通勤路程",
"compact|a.紧凑的 n.合同；小汽车 v.压实",
"companion|n.同伴；伴侣",
"company|n.公司；陪伴；同伴",
"comparable|a.可比较的；类似的",
"comparative|a.比较的；相对的",
"compare|v.比较；比喻",
"comparison|n.比较；比喻",
"compartment|n.隔间；车厢",
"compass|n.罗盘；圆规",
"compassion|n.同情；怜悯",
"compatible|a.兼容的；合得来的",
"compel|v.强迫；驱使",
"compensate|v.补偿；赔偿",
"compete|v.竞争；比赛",
"competence|n.能力；胜任",
"competent|a.有能力的；胜任的",
"competition|n.竞争；比赛",
"competitive|a.竞争的；有竞争力的",
"competitor|n.竞争者；对手",
"compile|v.汇编；编制",
"complain|v.抱怨；投诉",
"complaint|n.抱怨；投诉；疾病",
"complement|v./n.补充；补足",
"complete|a.完整的 v.完成",
"complex|a.复杂的 n.综合体",
"complexity|n.复杂性；复杂的事物",
"complicate|v.使复杂化",
"comply|v.遵从；服从",
"component|n.组成部分；部件",
"compose|v.组成；创作；使镇静",
"composite|a.合成的 n.合成物",
"composition|n.构成；作文；作曲",
"compound|n.化合物；大院 a.复合的",
"comprehend|v.理解；领会",
"comprehension|n.理解（力）",
"comprehensive|a.全面的；综合的",
"compress|v.压缩；浓缩",
"comprise|v.包含；由…组成",
"compromise|n./v.妥协；折中",
"compulsory|a.强制的；义务的",
"compute|v.计算；估算",
"computer|n.计算机；电脑",
"comrade|n.同志；同伴",
"conceal|v.隐藏；隐瞒",
"concede|v.承认；让步",
"conceive|v.构想；怀孕；设想",
"concentrate|v.集中；专心 n.浓缩物",
"concept|n.概念；观念",
"conception|n.概念；构想；怀孕",
"concern|v.涉及；使担忧 n.关心；忧虑",
"concerning|prep.关于",
"concert|n.音乐会；一致",
"concession|n.让步；特许权",
"concise|a.简明的；简洁的",
"conclude|v.得出结论；结束",
"conclusion|n.结论；结束",
"concrete|a.具体的 n.混凝土",
"condemn|v.谴责；判刑",
"condense|v.浓缩；凝结；缩写",
"condition|n.条件；状况 v.决定；训练",
"conduct|v.引导；实施；指挥 n.行为",
"confer|v.商讨；授予",
"conference|n.会议；讨论会",
"confess|v.承认；坦白；忏悔",
"confidence|n.信心；信任；秘密",
"confident|a.自信的；确信的",
"confidential|a.机密的；表示信任的",
"confine|v.限制；禁闭",
"confirm|v.确认；证实；批准",
"conflict|n./v.冲突；矛盾",
"conform|v.遵守；符合",
"confront|v.面对；遭遇；对抗",
"confuse|v.使困惑；混淆",
"confusion|n.困惑；混乱；混淆",
"congratulate|v.祝贺；庆贺",
"congress|n.国会；代表大会",
"conjunction|n.结合；连词",
"connect|v.连接；联系",
"connection|n.联系；连接；关系",
"conquer|v.征服；克服",
"conquest|n.征服；攻克",
"conscience|n.良心；良知",
"conscious|a.意识到的；有意的",
"consecutive|a.连续的；连贯的",
"consensus|n.共识；一致",
"consent|v./n.同意；许可",
"consequence|n.结果；后果；重要性",
"consequently|ad.因此；所以",
"conservation|n.保护；节约",
"conservative|a.保守的 n.保守者",
"conserve|v.保存；节约；保护",
"consider|v.考虑；认为；体谅",
"considerable|a.相当大（多）的",
"considerate|a.体贴的；考虑周到的",
"consideration|n.考虑；体贴；报酬",
"consist|v.由…组成；在于",
"consistent|a.一致的；始终如一的",
"consolidate|v.巩固；合并",
"conspiracy|n.阴谋；共谋",
"constant|a.不断的；恒定的 n.常数",
"constituent|n.成分；选民 a.构成的",
"constitute|v.构成；组成；设立",
"constitution|n.宪法；体质；组成",
"constrain|v.限制；约束；强迫",
"construct|v.建造；构造 n.构想",
"consult|v.咨询；商量；查阅",
"consultant|n.顾问；会诊医生",
"consume|v.消耗；消费；吃喝",
"consumer|n.消费者；用户",
"consumption|n.消费；消耗；消耗量",
"contact|n./v.接触；联系",
"contain|v.包含；容纳；抑制",
"container|n.容器；集装箱",
"contaminate|v.污染；弄脏",
"contemplate|v.沉思；打算",
"contemporary|a.当代的；同时代的 n.同代人",
"contempt|n.轻蔑；藐视",
"contend|v.竞争；主张",
"content|n.内容 a.满足的 v.使满足",
"contest|n.竞赛 v.竞争；质疑",
"context|n.上下文；背景；环境",
"continent|n.大陆；洲",
"continual|a.不断的；频繁的",
"continue|v.继续；持续",
"continuous|a.连续的；不断的",
"contract|n.合同 v.收缩；订合同；感染",
"contradict|v.反驳；与…矛盾",
"contradiction|n.矛盾；反驳",
"contrary|a.相反的 n.相反",
"contrast|n./v.对比；对照",
"contribute|v.贡献；捐助；投稿；促成",
"contribution|n.贡献；捐款；稿件",
"contrive|v.设法做到；谋划",
"control|v./n.控制；管理；抑制",
"controversial|a.有争议的",
"controversy|n.争论；论战",
"convenience|n.便利；方便",
"convenient|a.方便的；便利的",
"convention|n.惯例；公约；大会",
"conventional|a.常规的；传统的",
"conversation|n.交谈；谈话",
"conversely|ad.相反地",
"conversion|n.转变；转换；皈依",
"convert|v.转变；改造；改变信仰",
"convey|v.传达；运送；转让",
"convict|v.定罪 n.囚犯",
"conviction|n.定罪；确信；信念",
"convince|v.使确信；说服",
"cook|v.烹调 n.厨师",
"cookie|n.曲奇饼",
"cool|a.凉爽的；冷静的 v.冷却",
"cooperate|v.合作；协作",
"cooperation|n.合作；协作",
"cooperative|a.合作的 n.合作社",
"coordinate|v.协调 n.坐标 a.同等的",
"cop|n.警察",
"cope|v.应付；处理",
"copper|n.铜；铜币",
"copy|n.副本 v.复制；抄袭",
"copyright|n.版权",
"cord|n.细绳；电线",
"core|n.核心；果核",
"corn|n.玉米；谷物",
"corner|n.角落；困境",
"corporate|a.公司的；法人的；共同的",
"corporation|n.公司；企业",
"correct|a.正确的 v.改正",
"correlate|v.使相互关联 n.相关物",
"correspond|v.符合；相当于；通信",
"correspondence|n.通信；信件；对应",
"correspondent|n.记者；通信者",
"corridor|n.走廊；通道",
"corrode|v.腐蚀；侵蚀",
"corrupt|a.腐败的 v.使腐败；腐蚀",
"cosmic|a.宇宙的",
"cost|n.成本；费用 v.花费",
"costly|a.昂贵的；代价高的",
"costume|n.服装；戏装",
"cottage|n.小屋；村舍",
"cotton|n.棉花；棉布",
"couch|n.长沙发",
"cough|v./n.咳嗽",
"could|v.aux.能；可以",
"council|n.委员会；理事会",
"counsel|n.忠告；律师 v.劝告",
"count|v.数；计算；重要 n.计数",
"counter|n.柜台 ad.相反地 v.反击",
"counterpart|n.对应的人（物）",
"country|n.国家；乡村",
"countryside|n.乡村；农村",
"county|n.郡；县",
"couple|n.一对；夫妇 v.连接",
"coupon|n.优惠券；票证",
"courage|n.勇气；胆量",
"course|n.课程；过程；航线；一道菜",
"court|n.法院；球场；宫廷；庭院",
"courtesy|n.礼貌；好意",
"courtyard|n.庭院；院子",
"cousin|n.堂（表）兄弟姊妹",
"cover|v.覆盖；包括；报道 n.封面",
"coverage|n.新闻报道；覆盖范围",
"cow|n.母牛；奶牛",
"coward|n.懦夫；胆怯者",
"cowboy|n.牛仔",
"crab|n.螃蟹",
"crack|n.裂缝 v.破裂；发出爆裂声",
"cradle|n.摇篮；发源地",
"craft|n.工艺；手艺；船；诡计",
"crane|n.起重机；鹤",
"crash|v.碰撞；坠毁 n.失事；崩溃",
"crawl|v./n.爬行；缓慢行进",
"crazy|a.疯狂的；着迷的",
"cream|n.奶油；乳霜",
"create|v.创造；创作；引起",
"creation|n.创造；创作；作品",
"creative|a.有创造力的",
"creature|n.生物；动物；人",
"credential|n.资格证书；国书",
"credible|a.可信的；可靠的",
"credit|n.信用；学分；赞扬 v.相信",
"creep|v.爬行；蔓延",
"crew|n.全体船员；工作人员",
"cricket|n.板球；蟋蟀",
"crime|n.罪行；犯罪",
"criminal|n.罪犯 a.刑事的",
"crisis|n.危机；危急时刻",
"crisp|a.脆的；清新的；干脆的",
"criterion|n.标准；准则",
"critic|n.批评家；评论家",
"critical|a.批判的；关键的；危急的",
"criticism|n.批评；评论",
"criticize|v.批评；评论",
"crop|n.庄稼；作物；收成",
"cross|v.穿过；交叉 n.十字 a.生气的",
"crow|n.乌鸦 v.啼叫",
"crowd|n.人群 v.拥挤；挤满",
"crown|n.王冠；桂冠 v.加冕",
"crucial|a.至关重要的",
"crude|a.天然的；粗糙的；粗鲁的",
"cruel|a.残忍的；残酷的",
"cruise|v./n.巡航；游弋",
"crumble|v.弄碎；崩塌",
"crush|v.压碎；镇压 n.迷恋",
"cry|v.哭；喊叫 n.叫声",
"crystal|n.水晶；结晶 a.透明的",
"cube|n.立方体；立方",
"cucumber|n.黄瓜",
"cue|n.提示；暗示；信号",
"cultivate|v.耕作；培养；陶冶",
"culture|n.文化；教养；栽培",
"cupboard|n.橱柜",
"curb|v.控制；约束 n.路边；抑制",
"cure|v./n.治愈；治疗",
"curiosity|n.好奇心；珍品",
"curious|a.好奇的；奇怪的",
"curl|v.卷曲 n.卷发",
"currency|n.货币；通货",
"current|a.当前的 n.水流；电流；趋势",
"currently|ad.当前；现在",
"curriculum|n.课程（体系）",
"curse|n./v.诅咒；咒骂",
"curtain|n.窗帘；幕布",
"curve|n.曲线 v.弯曲",
"cushion|n.垫子 v.缓冲",
"custom|n.习俗；惯例；海关",
"customary|a.习惯的；惯例的",
"customer|n.顾客；客户",
"cut|v.切；割；削减 n.切口；削减",
"cyberspace|n.网络空间",
"cycle|n.循环；周期；自行车 v.骑车；循环",
"cyclist|n.骑自行车的人"
);
