/* 词库数据 6/12 · E */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"each|a./pron.每个的；每个",
"eager|a.渴望的；热切的",
"eagle|n.鹰",
"earn|v.赚得；挣得；获得",
"earnest|a.认真的；诚挚的",
"earth|n.地球；土地；泥土",
"earthquake|n.地震",
"ease|n.容易；安逸 v.减轻；缓和",
"easily|ad.容易地；无疑地",
"east|n.东方 a.东方的",
"easter|n.复活节",
"eastern|a.东方的；东部的",
"easy|a.容易的；舒适的；随和的",
"eat|v.吃；喝；侵蚀",
"eccentric|a.古怪的 n.古怪的人",
"echo|n.回声 v.重复；回响",
"eclipse|n.日食；月食 v.使黯然失色",
"ecology|n.生态学；生态",
"economic|a.经济的；经济学的",
"economical|a.节约的；实惠的",
"economics|n.经济学；经济状况",
"economy|n.经济；节约",
"edge|n.边缘；刀刃 v.徐徐移动",
"edible|a.可食用的",
"edit|v.编辑；剪辑",
"edition|n.版本；版次",
"editor|n.编辑；主编",
"editorial|n.社论 a.编辑的",
"educate|v.教育；培养",
"education|n.教育；培养",
"effect|n.效果；影响 v.实现",
"effective|a.有效的；生效的",
"efficiency|n.效率；功效",
"efficient|a.高效的；有能力的",
"effort|n.努力；成就",
"egg|n.蛋；鸡蛋；卵",
"ego|n.自我；自负",
"either|a./pron.（两者中）任一的 ad.也",
"eject|v.弹出；驱逐；喷出",
"elaborate|a.精心制作的 v.详细阐述",
"elbow|n.肘 v.用肘推",
"elder|a.年长的 n.长者",
"elderly|a.上了年纪的",
"elect|v.选举；选择",
"election|n.选举；当选",
"electric|a.电的；用电的",
"electrical|a.与电有关的",
"electricity|n.电；电学",
"electronic|a.电子的",
"elegant|a.优雅的；精美的",
"element|n.元素；要素；成分",
"elementary|a.基本的；初级的",
"elevate|v.提升；抬高",
"elevator|n.电梯；升降机",
"eligible|a.有资格的；合格的",
"eliminate|v.消除；淘汰",
"elite|n.精英 a.精英的",
"eloquent|a.雄辩的；传神的",
"elsewhere|ad.在别处",
"embark|v.上船；从事；着手",
"embarrass|v.使尴尬；使窘迫",
"embassy|n.大使馆",
"embody|v.体现；包含",
"embrace|v.拥抱；欣然接受；包含",
"emerge|v.出现；浮现；显露",
"emergency|n.紧急情况；突发事件",
"emigrate|v.移居国外",
"eminent|a.杰出的；著名的",
"emotion|n.情感；情绪",
"emotional|a.情感的；情绪的",
"emperor|n.皇帝",
"emphasis|n.强调；重点",
"emphasize|v.强调；着重",
"empire|n.帝国",
"empirical|a.经验主义的；实证的",
"employ|v.雇用；使用",
"employee|n.雇员；员工",
"employer|n.雇主；老板",
"employment|n.就业；雇用；职业",
"empty|a.空的；空洞的 v.倒空",
"enable|v.使能够；使可能",
"enact|v.制定（法律）；上演",
"enclose|v.围住；附上",
"encounter|v./n.遭遇；偶遇",
"encourage|v.鼓励；促进",
"encyclopedia|n.百科全书",
"endanger|v.危及；危害",
"endeavor|n./v.努力；尝试",
"ending|n.结局；结尾",
"endless|a.无止境的；没完没了的",
"endow|v.捐赠；赋予",
"endure|v.忍受；持久",
"enemy|n.敌人；敌军",
"energetic|a.精力充沛的",
"energy|n.能量；精力；能源",
"enforce|v.实施；强制执行",
"engage|v.从事；雇用；吸引；订婚",
"engagement|n.约会；婚约；交战",
"engine|n.发动机；引擎；机车",
"engineer|n.工程师 v.设计；策划",
"engineering|n.工程（学）",
"enhance|v.提高；增强",
"enjoy|v.享受；喜爱",
"enlarge|v.扩大；放大",
"enlighten|v.启发；开导",
"enormous|a.巨大的；庞大的",
"enough|a./ad.足够的（地） n.足够",
"enrich|v.使丰富；使富裕",
"enroll|v.注册；登记；招收",
"ensure|v.保证；确保",
"entail|v.牵涉；需要",
"enter|v.进入；参加；输入",
"enterprise|n.企业；事业心",
"entertain|v.娱乐；款待；怀有",
"enthusiasm|n.热情；热心",
"enthusiastic|a.热情的；热心的",
"entitle|v.使有权；给…题名",
"entity|n.实体；独立存在体",
"entrance|n.入口；进入",
"entrepreneur|n.企业家；创业者",
"entry|n.进入；入口；条目",
"envelope|n.信封",
"environment|n.环境；周围状况",
"envisage|v.设想；展望",
"envy|n./v.羡慕；嫉妒",
"epidemic|n.流行病；蔓延 a.流行性的",
"episode|n.一段经历；（剧）一集",
"epoch|n.时代；纪元",
"equal|a.相等的 v.等于 n.相等者",
"equality|n.平等；相等",
"equation|n.方程式；等式",
"equator|n.赤道",
"equip|v.装备；配备",
"equipment|n.设备；装备",
"equivalent|a.相等的 n.等价物",
"era|n.时代；年代",
"erase|v.擦掉；清除",
"erect|v.建造；竖立 a.直立的",
"erosion|n.侵蚀；腐蚀",
"error|n.错误；差错",
"erupt|v.爆发；喷发",
"escalate|v.升级；加剧",
"escape|v./n.逃跑；逃脱；避免",
"especially|ad.尤其；特别",
"essay|n.散文；论文",
"essence|n.本质；精华",
"essential|a.必不可少的；本质的 n.要素",
"establish|v.建立；确立；安置",
"establishment|n.机构；建立",
"estate|n.地产；财产；庄园",
"esteem|n./v.尊重；尊敬",
"estimate|v./n.估计；估算",
"eternal|a.永恒的；永久的",
"ethnic|a.民族的；种族的",
"evaluate|v.评估；评价",
"evaluation|n.评估；评价",
"evaporate|v.蒸发；消失",
"eve|n.前夜；前夕",
"even|ad.甚至 a.平的；偶数的 v.使平坦",
"evening|n.晚上；傍晚",
"event|n.事件；大事；比赛项目",
"eventually|ad.最终；终于",
"ever|ad.曾经；从来；究竟",
"everlasting|a.永久的；永恒的",
"every|a.每一的；每隔…的",
"everybody|pron.每人；人人",
"everyday|a.每天的；日常的",
"everyone|pron.每个人",
"everything|pron.每件事；一切",
"everywhere|ad.到处；处处",
"evidence|n.证据；迹象",
"evident|a.明显的；显然的",
"evil|a.邪恶的 n.邪恶；罪恶",
"evoke|v.唤起；引起",
"evolve|v.演变；进化",
"exact|a.确切的；精确的",
"exactly|ad.确切地；正是",
"exaggerate|v.夸大；夸张",
"exam|n.考试；检查",
"examination|n.考试；检查；审查",
"examine|v.检查；审查；测验",
"example|n.例子；榜样",
"exceed|v.超过；超出",
"exceedingly|ad.极其；非常",
"excel|v.胜过；擅长",
"excellent|a.优秀的；卓越的",
"except|prep.除…之外",
"exception|n.例外；异议",
"exceptional|a.异常的；杰出的",
"excerpt|n.摘录；节选",
"excess|n.过量 a.过量的",
"excessive|a.过多的；过度的",
"exchange|v./n.交换；兑换；交流",
"excite|v.使兴奋；激起",
"excitement|n.兴奋；激动",
"exciting|a.令人兴奋的",
"exclaim|v.呼喊；惊叫",
"exclude|v.排除；不包括",
"exclusive|a.独有的；高级的；排斥的",
"excursion|n.远足；短途旅行",
"excuse|n.借口 v.原谅；为…辩解",
"execute|v.执行；实施；处死",
"executive|n.主管 a.行政的；经营的",
"exemplify|v.例证；是…的典型",
"exempt|v.免除 a.被免除的",
"exercise|n.运动；练习 v.锻炼；运用",
"exert|v.施加；运用",
"exhaust|v.使精疲力尽；耗尽 n.废气",
"exhibit|v.展览；显示 n.展品",
"exhibition|n.展览（会）",
"exile|n./v.流放；流亡",
"exist|v.存在；生存",
"existence|n.存在；生存",
"exit|n.出口；退场 v.退出",
"exotic|a.奇异的；异国的",
"expand|v.扩大；膨胀；扩展",
"expansion|n.扩张；膨胀",
"expect|v.预期；期待；要求",
"expectation|n.期望；预期",
"expedition|n.远征；探险队",
"expel|v.驱逐；开除",
"expenditure|n.支出；花费",
"expense|n.费用；代价",
"expensive|a.昂贵的",
"experience|n.经验；经历 v.经历",
"experiment|n./v.实验；试验",
"experimental|a.实验的；试验性的",
"expert|n.专家 a.熟练的",
"expertise|n.专门知识；专长",
"expire|v.到期；逝世",
"explain|v.解释；说明",
"explanation|n.解释；说明",
"explicit|a.明确的；清楚的",
"explode|v.爆炸；爆发；激增",
"exploit|v.剥削；利用；开发 n.功绩",
"explore|v.探索；勘探",
"explosion|n.爆炸；激增",
"explosive|a.爆炸性的 n.炸药",
"export|v./n.出口；输出",
"expose|v.暴露；揭发；使接触",
"exposure|n.暴露；揭露；曝光",
"express|v.表达 a.快速的 n.快车",
"expression|n.表达；表情；词语",
"exquisite|a.精美的；精致的",
"extend|v.延伸；扩展；给予",
"extension|n.延伸；扩展部分；分机",
"extensive|a.广泛的；大量的",
"extent|n.程度；范围",
"exterior|a.外部的 n.外部；外观",
"external|a.外部的；外界的",
"extinct|a.灭绝的；熄灭的",
"extinguish|v.熄灭；扑灭；使消亡",
"extra|a.额外的 n.额外的事物",
"extract|v.提取；摘录 n.提取物",
"extraordinary|a.非凡的；特别的",
"extravagant|a.奢侈的；过度的",
"extreme|a.极端的；极度的 n.极端",
"eye|n.眼睛；眼光 v.注视",
"eyebrow|n.眉毛"
);
