/* 词库数据 8/12 · H + I */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"habit|n.习惯；习性",
"habitat|n.栖息地；生活环境",
"hail|v.招呼；下冰雹 n.冰雹",
"hair|n.头发；毛发",
"half|n./a.一半（的）",
"hall|n.大厅；礼堂",
"halt|v./n.停止；中止",
"hamburger|n.汉堡包",
"hammer|n.锤 v.锤打",
"hamper|v.妨碍；阻碍 n.洗衣篮",
"hand|n.手；指针 v.交；递",
"handbook|n.手册；指南",
"handful|n.一把；少数",
"handicap|n.缺陷；障碍 v.妨碍",
"handkerchief|n.手帕",
"handle|v.处理；操作 n.把手",
"handsome|a.英俊的；可观的",
"handwriting|n.书写；笔迹",
"handy|a.方便的；手巧的；附近的",
"hang|v.悬挂；绞死",
"happen|v.发生；碰巧",
"happiness|n.幸福；快乐",
"happy|a.快乐的；幸福的",
"harassment|n.骚扰；烦恼",
"harbor|n.港口 v.怀有；庇护",
"hard|a.硬的；困难的 ad.努力地",
"harden|v.使变硬；使坚强",
"hardly|ad.几乎不；仅仅",
"hardship|n.艰难；困苦",
"hardware|n.硬件；五金制品",
"harm|n./v.伤害；损害",
"harmful|a.有害的",
"harmonious|a.和谐的；协调的",
"harmony|n.和谐；融洽",
"harness|v.利用；给…上挽具 n.马具",
"harsh|a.严厉的；恶劣的；刺耳的",
"harvest|n./v.收获；收割",
"haste|n.匆忙；草率",
"hasty|a.匆忙的；草率的",
"hat|n.帽子",
"hatch|v.孵化；策划 n.舱口",
"hate|v./n.憎恨；讨厌",
"hatred|n.憎恨；仇恨",
"haul|v.拖；拉 n.大批赃物",
"have|v.有；吃；使 aux.已经",
"hawk|n.鹰；鹰派人物",
"hay|n.干草",
"hazard|n.危险；危害",
"he|pron.他",
"head|n.头；领导；顶端 v.领导；前往",
"headache|n.头痛；令人头痛的事",
"heading|n.标题",
"headline|n.头条新闻；标题",
"headquarters|n.总部；司令部",
"heal|v.治愈；愈合",
"health|n.健康；卫生",
"healthy|a.健康的；有益健康的",
"heap|n.堆；许多 v.堆起",
"hear|v.听见；听说；审讯",
"hearing|n.听力；听证会",
"heart|n.心脏；内心；中心",
"heat|n.热度 v.加热",
"heater|n.加热器；暖气",
"heaven|n.天堂；天空",
"heavy|a.重的；大量的；繁重的",
"hedge|n.树篱；防备 v.避免正面回答",
"heel|n.脚后跟；鞋跟",
"height|n.高度；身高；顶点",
"heighten|v.提高；加强",
"heir|n.继承人",
"helicopter|n.直升机",
"hell|n.地狱；苦境",
"hello|int.你好 n.问候",
"helmet|n.头盔",
"help|v./n.帮助；有助于",
"helpful|a.有帮助的；有益的",
"hemisphere|n.半球",
"hen|n.母鸡",
"hence|ad.因此；从此",
"her|pron.她的；她",
"herb|n.药草；草本植物",
"herd|n.兽群；牧群 v.放牧",
"here|ad.这里；在这时",
"heritage|n.遗产；传统",
"hero|n.英雄；男主角",
"heroic|a.英雄的；英勇的",
"heroine|n.女英雄；女主角",
"hers|pron.她的（东西）",
"herself|pron.她自己",
"hesitate|v.犹豫；踌躇",
"hide|v.隐藏；躲避 n.兽皮",
"high|a.高的；高级的 ad.高",
"highland|n.高地；高原",
"highlight|v.强调；突出 n.最精彩的部分",
"highly|ad.高度地；非常",
"highway|n.公路；大道",
"hike|n./v.徒步旅行；（价格）猛增",
"hill|n.小山；斜坡",
"him|pron.他",
"himself|pron.他自己",
"hinder|v.阻碍；妨碍",
"hint|n.暗示；提示 v.暗示",
"hip|n.臀部；髋部",
"hire|v./n.租用；雇用",
"his|pron.他的",
"historian|n.历史学家",
"historic|a.有历史意义的",
"historical|a.历史的；史学的",
"history|n.历史；来历",
"hit|v.打击；碰撞；到达 n.击；成功之作",
"hitherto|ad.到目前为止",
"hobby|n.爱好；嗜好",
"hockey|n.曲棍球；冰球",
"hold|v.拿着；持有；举行 n.把握",
"holder|n.持有者；支架",
"hole|n.洞；孔；漏洞",
"holiday|n.假日；节日",
"hollow|a.空的；空洞的 n.洞",
"holy|a.神圣的；圣洁的",
"home|n.家 ad.在家；回家",
"homework|n.作业；功课",
"homogeneous|a.同质的；同类的",
"honest|a.诚实的；正直的",
"honey|n.蜂蜜；亲爱的人",
"honor|n.荣誉；尊敬 v.尊敬；信守",
"honorable|a.光荣的；可敬的",
"hook|n.钩 v.钩住",
"hop|v.单足跳 n.跳跃",
"hope|v./n.希望；期望",
"hopeful|a.充满希望的",
"hopeless|a.绝望的；无可救药的",
"horizon|n.地平线；眼界",
"horizontal|a.水平的；横向的",
"hormone|n.激素；荷尔蒙",
"horn|n.角；号角；喇叭",
"horrible|a.可怕的；糟透的",
"horror|n.恐怖；震惊",
"horse|n.马",
"horsepower|n.马力",
"hose|n.软管；水龙带",
"hospital|n.医院",
"hospitality|n.好客；款待",
"host|n.主人；主持人；大量 v.主办",
"hostage|n.人质",
"hostess|n.女主人；女主持人",
"hostile|a.敌对的；敌意的",
"hot|a.热的；辣的；热门的",
"hotel|n.旅馆；饭店",
"hound|n.猎犬 v.纠缠；追逼",
"hour|n.小时；钟点",
"house|n.房子 v.给…房子住",
"household|n.家庭 a.家用的",
"housewife|n.家庭主妇",
"housework|n.家务劳动",
"housing|n.住房；住房供给",
"hover|v.盘旋；徘徊；踌躇",
"how|ad.怎样；多么",
"however|ad.然而 conj.无论如何",
"howl|v./n.嚎叫；怒吼",
"hug|v./n.拥抱",
"huge|a.巨大的；庞大的",
"human|a.人的 n.人",
"humanity|n.人类；人性；人文",
"humble|a.谦逊的；卑微的 v.贬低",
"humid|a.潮湿的",
"humor|n.幽默；心情",
"humorous|a.幽默的；滑稽的",
"hundred|num.一百",
"hunger|n.饥饿；渴望",
"hungry|a.饥饿的；渴望的",
"hunt|v./n.打猎；搜寻",
"hunter|n.猎人；搜寻者",
"hurl|v.猛投；大声叫骂",
"hurricane|n.飓风",
"hurry|v./n.匆忙；赶快",
"hurt|v.伤害；疼痛 n.伤害",
"husband|n.丈夫",
"hut|n.小屋；棚屋",
"hydrogen|n.氢",
"hypothesis|n.假说；前提",
"ice|n.冰 v.冰镇",
"idea|n.想法；主意；概念",
"ideal|a.理想的 n.理想",
"identical|a.完全相同的",
"identification|n.鉴定；身份证明",
"identify|v.识别；确定；认同",
"identity|n.身份；同一性；特性",
"ideology|n.意识形态；思想体系",
"idiom|n.习语；成语",
"idle|a.闲置的；无所事事的 v.虚度",
"if|conj.如果；是否",
"ignite|v.点燃；引发",
"ignorance|n.无知；愚昧",
"ignorant|a.无知的；不知道的",
"ignore|v.忽视；不理",
"ill|a.有病的；坏的 ad.恶劣地",
"illegal|a.非法的",
"illness|n.疾病",
"illuminate|v.照亮；阐明",
"illusion|n.错觉；幻觉",
"illustrate|v.说明；图解",
"illustration|n.插图；例证",
"image|n.形象；图像；影像",
"imaginary|a.想象中的；虚构的",
"imagination|n.想象力；想象",
"imaginative|a.富有想象力的",
"imagine|v.想象；设想",
"imitate|v.模仿；仿制",
"imitation|n.模仿；仿制品",
"immediate|a.立即的；直接的",
"immediately|ad.立即；直接地",
"immense|a.巨大的；极大的",
"immerse|v.使浸没；使沉浸",
"immigrant|n.移民",
"immigrate|v.移入；移居",
"immune|a.免疫的；不受影响的",
"impact|n./v.影响；冲击",
"impair|v.损害；削弱",
"impartial|a.公正的；不偏不倚的",
"impatience|n.不耐烦；急切",
"impatient|a.不耐烦的；急切的",
"imperative|a.必要的；紧急的 n.命令",
"imperial|a.帝国的；皇帝的",
"implement|v.实施 n.工具",
"implication|n.含意；暗示；牵连",
"implicit|a.含蓄的；内含的",
"imply|v.暗示；意味着",
"import|v./n.进口；输入",
"importance|n.重要性",
"important|a.重要的；有影响的",
"impose|v.强加；征收（税）",
"impossible|a.不可能的",
"impress|v.使印象深刻",
"impression|n.印象；感想",
"impressive|a.令人印象深刻的",
"improve|v.改善；提高",
"improvement|n.改进；改善",
"impulse|n.冲动；脉冲",
"in|prep.在…里 ad.进入",
"incentive|n.激励；刺激",
"inch|n.英寸 v.缓慢移动",
"incidence|n.发生率",
"incident|n.事件；事变",
"incidentally|ad.顺便说；偶然地",
"incline|v.倾斜；倾向于 n.斜坡",
"include|v.包括；包含",
"inclusive|a.包含的；包容的",
"income|n.收入；所得",
"incorporate|v.合并；包含",
"increase|v./n.增加；增长",
"increasingly|ad.日益；越来越多地",
"incredible|a.难以置信的；惊人的",
"incur|v.招致；引起",
"indeed|ad.确实；其实",
"independence|n.独立；自主",
"independent|a.独立的；自主的",
"index|n.索引；指数",
"indicate|v.表明；指示",
"indication|n.指示；迹象",
"indifferent|a.冷漠的；不感兴趣的",
"indignant|a.愤慨的",
"indignation|n.愤慨；义愤",
"indispensable|a.必不可少的",
"individual|a.个人的；独特的 n.个人",
"indoor|a.室内的",
"induce|v.诱导；引起；诱发",
"indulge|v.放纵；沉溺",
"industrial|a.工业的；产业的",
"industrialize|v.工业化",
"industry|n.工业；行业；勤奋",
"inevitable|a.不可避免的",
"infant|n.婴儿 a.婴儿的",
"infect|v.感染；传染",
"infectious|a.传染的；有感染力的",
"infer|v.推断；推论",
"inference|n.推断；结论",
"inferior|a.较差的；下级的 n.下级",
"infinite|a.无限的；无穷的",
"inflation|n.通货膨胀",
"influence|n./v.影响；势力",
"influential|a.有影响力的",
"inform|v.通知；告知；检举",
"information|n.信息；情报",
"ingredient|n.成分；原料；因素",
"inhabit|v.居住于；栖息于",
"inhabitant|n.居民；栖息动物",
"inherit|v.继承；遗传",
"inhibit|v.抑制；阻碍",
"initial|a.最初的 n.首字母",
"initiate|v.开始；发起",
"initiative|n.主动性；倡议",
"inject|v.注射；注入",
"injure|v.伤害；损害",
"injury|n.伤害；损伤",
"ink|n.墨水；油墨",
"inland|a./ad.内地的（地）；国内的（地）",
"inlet|n.小湾；入口",
"inn|n.小旅馆；客栈",
"inner|a.内部的；内心的",
"innocent|a.无辜的；天真的",
"innovation|n.创新；革新",
"innovative|a.创新的；新颖的",
"input|n./v.输入；投入",
"inquiry|n.询问；调查",
"insect|n.昆虫",
"insert|v.插入；嵌入",
"inside|prep.在…里面 ad.在里面 n.内部",
"insight|n.洞察力；深刻见解",
"insist|v.坚持；坚决要求",
"inspect|v.检查；视察",
"inspiration|n.灵感；鼓舞",
"inspire|v.鼓舞；启发",
"install|v.安装；设置",
"installation|n.安装；设施",
"instance|n.例子；实例",
"instant|a.立即的；速食的 n.瞬间",
"instantly|ad.立即；马上",
"instead|ad.代替；反而",
"instinct|n.本能；直觉",
"institute|n.学院；研究所 v.建立",
"institution|n.机构；制度",
"instruct|v.指示；教导",
"instruction|n.指示；教学；说明书",
"instrument|n.仪器；乐器；手段",
"instrumental|a.有帮助的；乐器的",
"insufficient|a.不足的；不够的",
"insulate|v.使绝缘；隔离",
"insult|v./n.侮辱；辱骂",
"insurance|n.保险；保险费",
"insure|v.保险；确保",
"intact|a.完好无损的",
"intake|n.摄入量；吸入",
"integrate|v.使成整体；融合",
"integrity|n.正直；完整",
"intellectual|a.智力的 n.知识分子",
"intelligence|n.智力；情报",
"intelligent|a.聪明的；智能的",
"intelligible|a.可理解的；明白易懂的",
"intend|v.打算；意图",
"intense|a.强烈的；紧张的",
"intensity|n.强度；强烈",
"intensive|a.强化的；密集的",
"intention|n.意图；目的",
"interact|v.相互作用；互动",
"interaction|n.相互作用；互动",
"intercept|v./n.拦截；截住",
"interchange|v./n.交换；互换",
"interest|n.兴趣；利益；利息 v.使感兴趣",
"interesting|a.有趣的",
"interface|n.界面；接口",
"interfere|v.干涉；干扰",
"interference|n.干涉；干扰",
"interim|n.过渡时期 a.临时的",
"interior|a.内部的 n.内部；内地",
"intermediate|a.中间的；中级的",
"intermittent|a.间歇的；断断续续的",
"internal|a.内部的；国内的",
"international|a.国际的",
"internet|n.互联网",
"interpret|v.解释；口译",
"interpretation|n.解释；口译",
"interrupt|v.打断；中断",
"intersection|n.十字路口；交叉点",
"interval|n.间隔；幕间休息",
"intervene|v.干预；介入",
"interview|n./v.面试；采访",
"intimate|a.亲密的；私人的",
"intimidate|v.恐吓；威胁",
"into|prep.到…里；进入",
"intricate|a.复杂精细的",
"intrigue|v.激起兴趣；密谋 n.阴谋",
"introduce|v.介绍；引进；提出",
"introduction|n.介绍；引言；引进",
"intuition|n.直觉",
"invade|v.侵入；侵略",
"invalid|a.无效的 n.病弱者",
"invaluable|a.非常宝贵的",
"invasion|n.入侵；侵略",
"invent|v.发明；编造",
"invention|n.发明；创造；编造",
"inventory|n.库存；清单",
"inverse|a.相反的；倒转的 n.反面",
"invert|v.使倒转；颠倒",
"invest|v.投资；投入",
"investigate|v.调查；研究",
"investigation|n.调查；研究",
"investment|n.投资；投入",
"invisible|a.看不见的；无形的",
"invite|v.邀请；招致",
"invoke|v.援引；唤起",
"involve|v.涉及；包含；使参与",
"inward|a.内部的 ad.向内",
"iron|n.铁；熨斗 v.熨烫",
"ironic|a.讽刺的；反语的",
"irony|n.反语；讽刺",
"island|n.岛；岛屿",
"isolate|v.使隔离；使孤立",
"issue|n.问题；期号 v.发行；发布",
"it|pron.它",
"item|n.项目；条款；物品",
"itself|pron.它本身",
"ivory|n.象牙；乳白色"
);
