/* 词库数据 5/12 · D */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"daily|a.每日的 ad.每天 n.日报",
"dairy|n.乳制品；牛奶场",
"dam|n.水坝；堤",
"damage|v./n.损害；毁坏",
"damn|v.诅咒 int.该死",
"damp|a.潮湿的 n.湿气",
"dance|v./n.跳舞；舞蹈",
"danger|n.危险；危险物",
"dangerous|a.危险的",
"dare|v.敢；敢于 aux.敢",
"dark|a.黑暗的；深色的 n.黑暗",
"darling|n.心爱的人 a.可爱的",
"dash|v.猛冲；猛掷 n.破折号；冲刺",
"data|n.数据；资料",
"database|n.数据库",
"date|n.日期；约会 v.注明日期；约会",
"daughter|n.女儿",
"dawn|n.黎明；开端 v.破晓",
"day|n.天；白天",
"daylight|n.日光；白昼",
"dazzle|v.使目眩；使眼花缭乱",
"dead|a.死的；废弃的 ad.完全地",
"deadline|n.截止期限",
"deadly|a.致命的；非常的",
"deaf|a.聋的；不愿听的",
"deal|v.处理；发牌 n.交易；协议",
"dealer|n.商人；经销商",
"dear|a.亲爱的；昂贵的 int.哎呀",
"death|n.死亡；死神",
"debate|n./v.辩论；争论",
"debt|n.债务；欠款",
"debut|n.首次亮相；初次演出",
"decade|n.十年",
"decay|v./n.腐烂；衰退",
"deceive|v.欺骗；蒙骗",
"December|n.十二月",
"decent|a.正派的；体面的；像样的",
"decide|v.决定；判决",
"decidedly|ad.果断地；确实",
"decimal|a.十进制的 n.小数",
"decisive|a.决定性的；果断的",
"deck|n.甲板；一副（纸牌）",
"declaration|n.宣言；宣布；申报",
"declare|v.宣布；声明；申报",
"decline|v.下降；婉拒 n.衰退",
"decorate|v.装饰；装修",
"decrease|v./n.减少；降低",
"dedicate|v.奉献；献给",
"deduce|v.演绎；推断",
"deed|n.行为；契约",
"deem|v.认为；视为",
"deep|a.深的；深刻的 ad.深深地",
"deer|n.鹿",
"defeat|v./n.击败；失败",
"defect|n.缺陷；缺点 v.叛逃",
"defend|v.保卫；为…辩护",
"defense|n.防御；辩护；国防",
"defer|v.推迟；服从",
"deficiency|n.缺乏；不足",
"deficit|n.赤字；亏损；不足",
"define|v.下定义；限定",
"definite|a.明确的；一定的",
"definitely|ad.肯定地；明确地",
"definition|n.定义；清晰度",
"deform|v.使变形",
"defy|v.违抗；使成为不可能",
"degree|n.程度；度；学位",
"delay|v./n.延迟；耽搁",
"delegate|n.代表 v.委派；授权",
"delete|v.删除",
"deliberate|a.故意的；深思熟虑的 v.仔细考虑",
"delicate|a.精致的；微妙的；脆弱的",
"delicious|a.美味的；怡人的",
"delight|n.快乐 v.使高兴",
"deliver|v.递送；发表；生（孩子）；履行",
"delivery|n.投递；分娩；演讲方式",
"demand|v./n.要求；需求",
"democracy|n.民主；民主制",
"democratic|a.民主的",
"demonstrate|v.证明；演示；示威",
"denial|n.否认；拒绝",
"denote|v.表示；意味着",
"denounce|v.谴责；告发",
"dense|a.密集的；浓密的",
"density|n.密度；浓度",
"dental|a.牙齿的",
"dentist|n.牙医",
"deny|v.否认；拒绝给予",
"depart|v.离开；出发；背离",
"department|n.部门；系",
"departure|n.出发；背离",
"depend|v.依赖；取决于",
"dependent|a.依赖的；取决于…的",
"depict|v.描绘；描述",
"deploy|v.部署；调动；有效利用",
"deport|v.驱逐出境",
"deposit|n.存款；押金；沉积物 v.存放",
"depress|v.使沮丧；使萧条；压下",
"deprive|v.剥夺；使丧失",
"depth|n.深度；深奥；深处",
"deputy|n.副手；代理人",
"derive|v.源于；得到",
"descend|v.下降；遗传；突然访问",
"descendant|n.后代；后裔",
"descent|n.下降；血统；坡道",
"describe|v.描述；形容",
"description|n.描写；种类",
"desert|n.沙漠 v.抛弃；擅离",
"deserve|v.应得；值得",
"design|v./n.设计；图案；意图",
"designate|v.指定；指派 a.候任的",
"desirable|a.可取的；令人满意的",
"desire|n./v.愿望；欲望",
"desk|n.书桌；服务台",
"desolate|a.荒凉的；孤独的",
"despair|n./v.绝望",
"desperate|a.绝望的；不顾一切的",
"despise|v.鄙视；蔑视",
"despite|prep.尽管；不管",
"dessert|n.甜点",
"destination|n.目的地；终点",
"destiny|n.命运；天命",
"destroy|v.破坏；消灭",
"destruction|n.破坏；毁灭",
"destructive|a.破坏性的；毁灭性的",
"detach|v.拆下；使分离",
"detail|n.细节；详情 v.详述",
"detain|v.拘留；留住",
"detect|v.察觉；探测",
"detective|n.侦探",
"deteriorate|v.恶化；变坏",
"determine|v.决定；确定；下决心",
"detour|n.绕行路线 v.绕道",
"detrimental|a.有害的；不利的",
"devastate|v.毁坏；使震惊",
"develop|v.发展；开发；冲洗（照片）；患（病）",
"development|n.发展；开发；进展",
"deviate|v.背离；偏离",
"device|n.装置；设备；手段",
"devil|n.魔鬼；家伙",
"devise|v.设计；想出",
"devote|v.奉献；致力于",
"dew|n.露水",
"diagnose|v.诊断；判断",
"diagram|n.图表；图解",
"dial|n.刻度盘；拨号盘 v.拨号",
"dialect|n.方言；土话",
"dialogue|n.对话；对白",
"diameter|n.直径",
"diamond|n.钻石；菱形",
"diary|n.日记；日记簿",
"dictate|v.口述；命令 n.指令",
"dictation|n.听写；口述",
"dictator|n.独裁者",
"dictionary|n.词典",
"die|v.死亡；消失",
"diet|n.饮食；节食",
"differ|v.不同；相异",
"difference|n.差别；差额",
"different|a.不同的；各种的",
"differentiate|v.区分；区别",
"difficult|a.困难的；难相处的",
"difficulty|n.困难；难题",
"diffuse|v.扩散；散布 a.弥漫的",
"dig|v.挖；掘",
"digital|a.数字的；数码的",
"dignity|n.尊严；高贵",
"dilemma|n.困境；进退两难",
"diligent|a.勤奋的；用功的",
"dilute|v.稀释；冲淡 a.稀释的",
"dim|a.昏暗的；模糊的 v.变暗淡",
"dimension|n.尺寸；维度；方面",
"diminish|v.减少；降低",
"dine|v.进餐；用餐",
"dinner|n.正餐；晚餐",
"dip|v.浸；蘸；下降 n.浸泡",
"diploma|n.文凭；毕业证书",
"diplomat|n.外交官",
"diplomatic|a.外交的；圆滑的",
"direct|a.直接的 v.指导；指向 ad.直接地",
"direction|n.方向；指导；说明书",
"directly|ad.直接地；立刻 conj.一…就",
"director|n.导演；主管；董事",
"directory|n.姓名地址录；目录",
"dirt|n.污物；泥土",
"dirty|a.脏的；卑鄙的 v.弄脏",
"disable|v.使残疾；使无效",
"disagree|v.不同意；不一致",
"disappear|v.消失；失踪",
"disappoint|v.使失望；使落空",
"disaster|n.灾难；灾祸",
"discard|v.丢弃；抛弃",
"discern|v.看出；识别",
"discharge|v./n.释放；排出；解雇；履行",
"discipline|n.纪律；学科 v.训练；惩罚",
"disclose|v.透露；揭露",
"discount|n.折扣 v.打折；不重视",
"discourage|v.使泄气；阻止",
"discourse|n.论文；话语；谈话",
"discover|v.发现；找到",
"discovery|n.发现；被发现的事物",
"discreet|a.谨慎的；考虑周到的",
"discrepancy|n.差异；不符",
"discuss|v.讨论；论述",
"discussion|n.讨论；商议",
"disease|n.疾病；弊端",
"disgrace|n.耻辱 v.使丢脸",
"disguise|v./n.伪装；掩饰",
"disgust|n./v.厌恶；反感",
"dish|n.盘；菜肴",
"dislike|v./n.不喜欢；厌恶",
"dismay|n./v.惊愕；使沮丧",
"dismiss|v.解雇；解散；不予理会",
"disorder|n.混乱；失调；疾病",
"dispatch|v.派遣；发送 n.派遣",
"disperse|v.分散；驱散",
"displace|v.取代；转移；迫使离开家园",
"display|v./n.展示；陈列；显示",
"displease|v.使不高兴；触怒",
"dispose|v.处理；倾向于",
"disposition|n.性格；倾向；处置",
"dispute|v./n.争论；争执",
"disregard|v./n.忽视；漠视",
"disrupt|v.扰乱；使中断",
"dissolve|v.溶解；解散；消失",
"distance|n.距离；远处",
"distant|a.遥远的；疏远的",
"distill|v.蒸馏；提炼",
"distinct|a.明显的；不同的",
"distinction|n.差别；卓越；荣誉",
"distinguish|v.区分；辨别；使突出",
"distort|v.歪曲；扭曲",
"distract|v.分散注意力；使分心",
"distress|n.痛苦；贫困 v.使痛苦",
"distribute|v.分配；分布；分销",
"district|n.地区；区域",
"disturb|v.打扰；扰乱",
"ditch|n.沟；沟渠",
"dive|v./n.跳水；潜水；俯冲",
"diverse|a.多样的；不同的",
"diversion|n.转移；消遣；改道",
"divert|v.使转向；转移…的注意力",
"divide|v.划分；除；使对立 n.分歧",
"dividend|n.红利；股息；回报",
"divine|a.神的；神圣的",
"division|n.分开；部门；除法；分歧",
"divorce|n./v.离婚；分离",
"dizzy|a.头晕的；眼花缭乱的",
"do|v.做；干 aux.助动词",
"dock|n.码头；船坞 v.对接；扣工资",
"doctor|n.医生；博士",
"doctrine|n.学说；教义",
"document|n.文件；文献 v.记录",
"dodge|v.躲开；逃避 n.躲闪",
"dog|n.狗",
"doll|n.玩偶；洋娃娃",
"dollar|n.美元；元",
"dolphin|n.海豚",
"domain|n.领域；领土；域名",
"dome|n.圆屋顶",
"domestic|a.国内的；家庭的；驯养的",
"dominant|a.占优势的；显性的",
"dominate|v.支配；统治；耸立于",
"donate|v.捐赠；赠予",
"donkey|n.驴",
"donor|n.捐赠者；供体",
"door|n.门；门口",
"doorway|n.门口；出入口",
"dose|n.剂量；一剂",
"dot|n.点；圆点 v.加点于",
"double|a.两倍的；双的 v.加倍",
"doubt|n./v.怀疑；疑问",
"dough|n.生面团",
"dove|n.鸽子；温和派人物",
"down|ad.向下 prep.沿着 a.沮丧的",
"downstairs|ad.在楼下 a.楼下的",
"downtown|ad./n.在市区（商业区）",
"downward|a.向下的 ad.向下",
"dozen|n.一打；十二个",
"draft|n.草稿；汇票 v.起草；征兵",
"drag|v.拖；拉；拖沓",
"dragon|n.龙",
"drain|v.排走；耗尽 n.下水道；消耗",
"drama|n.戏剧；戏剧性事件",
"dramatic|a.戏剧性的；巨大的",
"drastic|a.激烈的；严厉的",
"draw|v.画；拖；吸引；提取 n.平局",
"drawback|n.缺点；不利条件",
"drawer|n.抽屉",
"drawing|n.图画；素描",
"dread|v./n.畏惧；担忧",
"dream|n.梦；梦想 v.做梦",
"dress|n.连衣裙；服装 v.穿衣",
"drift|v./n.漂流；漂移；趋势",
"drill|v./n.钻；训练；操练",
"drink|v.喝；饮 n.饮料",
"drip|v.滴下 n.水滴",
"drive|v.驾驶；驱使 n.干劲；驾车",
"driver|n.司机；驱动因素",
"drop|v.落下；下降；放弃 n.滴；下降",
"drought|n.旱灾；干旱",
"drown|v.淹死；淹没",
"drug|n.药物；毒品",
"drum|n.鼓；桶",
"drunk|a.醉的；陶醉的",
"dry|a.干的；干旱的 v.弄干",
"dubious|a.怀疑的；无把握的",
"duck|n.鸭 v.低头躲闪；回避",
"due|a.到期的；应得的；预定",
"dull|a.乏味的；阴沉的；迟钝的",
"dumb|a.哑的；沉默的；愚蠢的",
"dump|v.倾倒；抛弃 n.垃圾场",
"duplicate|n.复制品 v.复制 a.完全相同的",
"durable|a.耐用的；持久的",
"during|prep.在…期间",
"dusk|n.黄昏；傍晚",
"dust|n.灰尘 v.除尘",
"duty|n.责任；税；职责",
"dwarf|n.侏儒 v.使显得矮小",
"dwell|v.居住；详述",
"dwelling|n.住宅；住处",
"dye|n./v.染料；染色",
"dynamic|a.动态的；有活力的 n.动力学"
);
