/* 词库数据 13/16 · S (a–p) */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"sacred|a.神圣的；宗教的",
"sacrifice|n./v.牺牲；献祭",
"sad|a.悲伤的；令人难过的",
"saddle|n.马鞍；车座",
"safe|a.安全的 n.保险箱",
"safeguard|v.保护；维护 n.保护措施",
"safety|n.安全；安全性",
"sail|v.航行 n.帆；航行",
"sailor|n.水手；海员",
"sake|n.缘故；理由",
"salad|n.沙拉；凉拌菜",
"salary|n.薪水；薪金",
"sale|n.出售；销售额",
"salesman|n.推销员；售货员",
"salt|n.盐",
"same|a.相同的 pron.同样的事物",
"sample|n.样品；样本 v.抽样",
"sanction|n.制裁；批准 v.批准",
"sand|n.沙；沙滩",
"sandwich|n.三明治 v.夹入",
"satellite|n.卫星；人造卫星",
"satisfaction|n.满意；满足",
"satisfactory|a.令人满意的",
"satisfy|v.使满意；满足",
"saturday|n.星期六",
"sauce|n.调味汁；酱",
"sausage|n.香肠",
"saving|n.储蓄；节省",
"saw|v.锯 n.锯子",
"say|v.说 n.发言权",
"scale|n.规模；等级；天平；鳞",
"scan|v.扫描；浏览",
"scandal|n.丑闻；反感",
"scarce|a.稀缺的；不足的",
"scarcity|n.缺乏；不足",
"scare|v.惊吓 n.恐慌",
"scatter|v.散开；散布",
"scene|n.场景；景色；现场",
"scenery|n.风景；景色",
"scent|n.气味；香味",
"schedule|n.时间表 v.安排",
"scheme|n.计划；方案；阴谋",
"scholar|n.学者",
"scholarship|n.奖学金；学问",
"school|n.学校；学院；学派",
"science|n.科学",
"scientific|a.科学的",
"scientist|n.科学家",
"scissors|n.剪刀",
"scold|v.责骂；训斥",
"scope|n.范围；余地",
"score|n.分数；二十 v.得分",
"scout|n.侦察员；童子军 v.侦察",
"scratch|v.抓；划 n.抓痕",
"scream|v./n.尖叫",
"screen|n.屏幕；屏风 v.筛查",
"screw|n.螺丝 v.拧",
"script|n.剧本；笔迹；脚本",
"scrutiny|n.仔细审查",
"sculpture|n.雕塑；雕刻",
"sea|n.海；海洋",
"seal|n.海豹；印章 v.密封",
"search|v./n.搜索；寻找",
"seaside|n.海滨",
"season|n.季节 v.调味",
"seat|n.座位 v.使就座",
"second|num.第二 n.秒 a.次等的",
"secondary|a.次要的；中等的",
"secondly|ad.第二；其次",
"secret|a.秘密的 n.秘密",
"secretary|n.秘书；部长",
"section|n.部分；部门；截面",
"sector|n.部门；区域",
"secure|a.安全的 v.获得；保护",
"security|n.安全；保障；证券",
"see|v.看见；明白；会见",
"seed|n.种子；根源",
"seek|v.寻找；追求",
"seem|v.似乎；好像",
"seemingly|ad.表面上；看上去",
"segment|n.部分；段",
"seldom|ad.很少；不常",
"select|v.选择 a.精选的",
"selection|n.选择；选集",
"self|n.自我；自己",
"selfish|a.自私的",
"sell|v.卖；出售",
"semester|n.学期",
"seminar|n.研讨会",
"senate|n.参议院",
"senator|n.参议员",
"send|v.发送；派遣",
"senior|a.年长的；资深的 n.前辈",
"sensation|n.感觉；轰动",
"sense|n.感觉；意义 v.意识到",
"sensible|a.明智的；合理的",
"sensitive|a.敏感的；灵敏的",
"sentence|n.句子；判决 v.判刑",
"sentiment|n.情绪；观点",
"separate|v.分开 a.分离的",
"september|n.九月",
"sequence|n.顺序；序列",
"series|n.系列；连续",
"serious|a.严重的；认真的",
"servant|n.仆人；公务员",
"serve|v.服务；供应；任职",
"service|n.服务；服务业 v.检修",
"session|n.会议；一段时间",
"set|v.放置；设置 n.一套 a.固定的",
"settle|v.解决；定居；沉淀",
"settlement|n.解决；定居点",
"several|a.几个的 pron.几个",
"severe|a.严重的；严厉的",
"sew|v.缝；缝纫",
"sex|n.性别",
"shade|n.荫；阴凉处；色度",
"shadow|n.影子；阴影",
"shake|v.摇动；握手 n.摇动",
"shall|v.aux.将要；应该",
"shallow|a.浅的；浅薄的",
"shame|n.羞耻；遗憾 v.使羞愧",
"shape|n.形状 v.塑造",
"share|v.分享；分担 n.份额；股份",
"shareholder|n.股东",
"shark|n.鲨鱼",
"sharp|a.锋利的；敏锐的；急剧的",
"shatter|v.粉碎；使破灭",
"shave|v.剃；刮",
"she|pron.她",
"shed|v.流出；摆脱 n.棚屋",
"sheep|n.羊；绵羊",
"sheer|a.纯粹的；陡峭的",
"sheet|n.床单；一张；薄板",
"shelf|n.架子；搁板",
"shell|n.壳；贝壳；炮弹",
"shelter|n.庇护所 v.庇护",
"shield|n.盾；防护物 v.保护",
"shift|v.转移；改变 n.转变；轮班",
"shine|v.照耀；发光",
"ship|n.船 v.运送",
"shipment|n.装运；货物",
"shirt|n.衬衫",
"shiver|v./n.发抖",
"shock|n.震惊；电击 v.使震惊",
"shoe|n.鞋",
"shoot|v.射击；拍摄；发芽",
"shop|n.商店；车间 v.购物",
"shore|n.岸；海滨",
"short|a.短的；矮的；缺乏的",
"shortage|n.不足；短缺",
"shortcoming|n.缺点；短处",
"shortly|ad.立刻；不久",
"shot|n.射击；投篮；照片",
"should|v.aux.应该；万一",
"shoulder|n.肩膀 v.承担",
"shout|v./n.呼喊；喊叫",
"show|v.显示；表明 n.展览；节目",
"shower|n.淋浴；阵雨 v.淋浴",
"shrink|v.收缩；退缩",
"shrug|v./n.耸肩",
"shut|v.关闭",
"shuttle|n.航天飞机；穿梭班车",
"shy|a.害羞的；腼腆的",
"sick|a.生病的；厌倦的",
"sickness|n.疾病",
"side|n.边；方面；侧面",
"sidewalk|n.人行道",
"sideways|ad./a.向旁边（的）",
"sigh|v./n.叹气",
"sight|n.视力；景象；名胜",
"sightseeing|n.观光；游览",
"sign|n.符号；迹象 v.签名",
"signal|n.信号 v.发信号",
"signature|n.签名；署名",
"significance|n.重要性；意义",
"significant|a.重要的；显著的",
"silence|n.沉默；寂静",
"silent|a.沉默的；安静的",
"silicon|n.硅",
"silk|n.丝绸",
"silly|a.愚蠢的",
"silver|n.银；银器",
"similar|a.相似的",
"similarity|n.相似性",
"simple|a.简单的；朴素的",
"simplicity|n.简单；朴素",
"simplify|v.简化",
"simply|ad.仅仅；简单地；简直",
"simulate|v.模拟；模仿",
"simultaneous|a.同时发生的",
"sin|n.罪；罪孽",
"since|conj.自从；既然 prep.自从",
"sincere|a.真诚的；诚挚的",
"sing|v.唱歌",
"single|a.单一的；单身的 n.单曲",
"singular|a.单数的；非凡的",
"sink|v.下沉 n.水槽",
"sir|n.先生",
"sister|n.姐妹",
"sit|v.坐；位于",
"site|n.地点；网站",
"situation|n.情况；处境；位置",
"six|num.六",
"size|n.大小；尺码",
"skate|v.滑冰 n.冰鞋",
"skeptical|a.怀疑的",
"sketch|n.素描；草图；梗概",
"ski|v.滑雪 n.滑雪板",
"skill|n.技能；技巧",
"skilled|a.熟练的；有技能的",
"skillful|a.熟练的；巧妙的",
"skin|n.皮肤；皮",
"skirt|n.裙子",
"sky|n.天空",
"skyscraper|n.摩天大楼",
"slam|v.砰地关上；猛击",
"slave|n.奴隶",
"slavery|n.奴隶制",
"sleep|v./n.睡觉",
"sleeve|n.袖子",
"slender|a.苗条的；微薄的",
"slice|n.薄片；一份 v.切片",
"slide|v.滑动 n.滑梯；幻灯片",
"slight|a.轻微的；细小的",
"slim|a.苗条的；渺茫的 v.减肥",
"slip|v.滑倒；溜走 n.疏漏",
"slippery|a.滑的；狡猾的",
"slogan|n.口号；标语",
"slope|n.斜坡；斜度",
"slow|a.慢的 v.放慢",
"slowly|ad.慢慢地",
"small|a.小的；少的",
"smart|a.聪明的；智能的；时髦的",
"smash|v.粉碎；猛撞",
"smell|v.闻 n.气味",
"smile|v./n.微笑",
"smoke|n.烟 v.吸烟；冒烟",
"smooth|a.光滑的；顺利的",
"snack|n.小吃；点心",
"snake|n.蛇",
"snap|v.折断；猛咬；拍照",
"snow|n.雪 v.下雪",
"so|ad.如此 conj.因此",
"soak|v.浸泡；浸湿",
"soap|n.肥皂",
"soar|v.翱翔；猛涨",
"sober|a.清醒的；冷静的",
"so-called|a.所谓的",
"soccer|n.足球",
"social|a.社会的；社交的",
"socialism|n.社会主义",
"society|n.社会；社团",
"sociology|n.社会学",
"sock|n.短袜",
"soda|n.苏打；汽水",
"sofa|n.沙发",
"soft|a.柔软的；柔和的",
"software|n.软件",
"soil|n.土壤 v.弄脏",
"solar|a.太阳的；太阳能的",
"soldier|n.士兵；军人",
"sole|a.唯一的；独占的 n.鞋底",
"solemn|a.庄严的；严肃的",
"solid|a.固体的；结实的 n.固体",
"solo|n.独奏 a.单独的",
"solution|n.解决办法；溶液",
"solve|v.解决；解答",
"some|a.一些；某个 pron.一些",
"somebody|pron.某人 n.重要人物",
"somehow|ad.以某种方式；不知怎么地",
"someone|pron.某人",
"something|pron.某事；某物",
"sometime|ad.某个时候",
"sometimes|ad.有时",
"somewhat|ad.稍微；有点",
"somewhere|ad.在某处",
"son|n.儿子",
"song|n.歌曲",
"soon|ad.很快；不久",
"sophisticated|a.复杂的；精密的；老练的",
"sore|a.疼痛的 n.痛处",
"sorrow|n.悲伤；悲痛",
"sorry|a.抱歉的；难过的",
"sort|n.种类 v.分类",
"soul|n.灵魂；心灵",
"sound|n.声音 v.听起来 a.完好的",
"soup|n.汤",
"sour|a.酸的；刻薄的",
"source|n.来源；源泉",
"south|n.南方 a.南方的",
"southeast|n.东南 a.东南的",
"southern|a.南方的；南部的",
"southwest|n.西南 a.西南的",
"sow|v.播种",
"space|n.空间；太空；空隙",
"spacecraft|n.宇宙飞船",
"spaceship|n.宇宙飞船",
"spacious|a.宽敞的",
"spade|n.铲子；铁锹",
"span|n.跨度；一段时间 v.横跨",
"spare|a.备用的；空闲的 v.抽出；饶恕",
"spark|n.火花 v.引发",
"sparkle|v.闪耀 n.火花",
"speak|v.说话；演讲",
"speaker|n.说话者；演讲者；扬声器",
"special|a.特别的；专门的",
"specialist|n.专家",
"species|n.物种；种类",
"specific|a.具体的；特定的",
"specify|v.具体说明；指定",
"specimen|n.标本；样品",
"spectacular|a.壮观的 n.壮观的场面",
"spectator|n.观众；旁观者",
"spectrum|n.光谱；范围",
"speculate|v.推测；投机",
"speech|n.演讲；言语",
"speed|n.速度 v.加速",
"spell|v.拼写 n.一段时间；咒语",
"spelling|n.拼写；拼法",
"spend|v.花费；度过",
"sphere|n.球体；领域",
"spider|n.蜘蛛",
"spill|v.溢出；洒出",
"spin|v.旋转；纺纱 n.旋转",
"spirit|n.精神；心灵；情绪",
"spiritual|a.精神的；心灵的",
"splendid|a.壮丽的；极好的",
"split|v.分裂；分开 n.分裂",
"spoil|v.破坏；溺爱；变质",
"spokesman|n.发言人",
"sponsor|n.赞助者 v.赞助；发起",
"spontaneous|a.自发的；自然的",
"spoon|n.勺子；调羹",
"sport|n.体育运动",
"spot|n.地点；斑点 v.发现",
"spouse|n.配偶",
"spray|v.喷；喷涂 n.喷雾",
"spread|v.传播；展开 n.传播",
"spring|n.春天；泉；弹簧 v.跳跃",
"spur|v.刺激；激励 n.刺激物",
"spy|n.间谍 v.当间谍；发现"
);
