/* 词库数据 16/16 · 补遗(基础词+高频词) */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"all|a.全部的 pron.全部",
"both|a.两者的 pron.两者",
"never|ad.从未；决不",
"at|prep.在（几点/地点）；以",
"across|prep.穿过 ad.横过",
"new|a.新的；新鲜的",
"cold|a.冷的；冷淡的 n.寒冷；感冒",
"early|a.早的 ad.早",
"end|n.末端；结束 v.结束",
"center|n.中心；中央 v.集中",
"call|v.打电话；称呼；召唤 n.电话",
"tree|n.树",
"forest|n.森林",
"apple|n.苹果",
"potato|n.马铃薯；土豆",
"ear|n.耳朵；听力",
"pig|n.猪",
"elephant|n.象；大象",
"bike|n.自行车",
"friday|n.星期五",
"november|n.十一月",
"eight|num.八",
"eleven|num.十一",
"fourteen|num.十四",
"eighteen|num.十八",
"eighty|num.八十",
"sixty|num.六十",
"seventy|num.七十",
"grandson|n.孙子；外孙",
"granddaughter|n.孙女；外孙女",
"apology|n.道歉；认错",
"cheque|n.支票",
"pot|n.锅；壶；罐",
"rainy|a.下雨的；多雨的",
"windy|a.有风的；多风的",
"snowy|a.下雪的；多雪的",
"bamboo|n.竹；竹子",
"beverage|n.饮料",
"bishop|n.主教",
"blond|a.金发的",
"bud|n.芽；花蕾",
"burial|n.埋葬；葬礼",
"bully|v.欺负 n.恃强凌弱者",
"canteen|n.食堂；小卖部",
"chore|n.家务杂事；杂务",
"chunk|n.大块；相当大的部分",
"closet|n.壁橱；储藏室",
"commence|v.开始",
"compensation|n.补偿；赔偿金",
"culminate|v.达到顶点；告终",
"cynical|a.愤世嫉俗的；怀疑的",
"deceptive|a.欺骗性的",
"degrade|v.降低；使降解；贬低",
"demographic|a.人口统计的",
"deplete|v.耗尽；使枯竭",
"depression|n.抑郁；萧条；洼地",
"diplomacy|n.外交；手腕",
"doom|n.厄运 v.注定",
"dual|a.双重的；两的",
"ecosystem|n.生态系统",
"elicit|v.引出；诱出",
"endorse|v.赞同；背书",
"erode|v.侵蚀；削弱",
"erroneous|a.错误的",
"facet|n.方面；刻面",
"famine|n.饥荒",
"fantasy|n.幻想；想象",
"feat|n.功绩；壮举",
"feminist|n.女权主义者",
"fiscal|a.财政的",
"forge|v.锻造；伪造 n.铁匠铺",
"formidable|a.可怕的；强大的",
"fringe|n.边缘；次要的",
"genre|n.类型；体裁",
"gracious|a.亲切的；仁慈的",
"haunt|v.常去；萦绕 n.常去之处",
"impetus|n.推动力；刺激",
"indigenous|a.本土的；原住民的",
"inflict|v.使遭受；施加",
"ingenious|a.巧妙的；有独创性的",
"integral|a.不可缺少的；完整的",
"intellect|n.智力；才智",
"intent|n.意图 a.专注的",
"intrinsic|a.内在的；固有的",
"jargon|n.行话；术语",
"jeopardize|v.危及；损害",
"judicial|a.司法的",
"kidnap|v.绑架",
"landmark|n.地标；里程碑",
"latitude|n.纬度；余地",
"lawsuit|n.诉讼；官司",
"lethal|a.致命的",
"leverage|v.利用 n.杠杆作用",
"liability|n.责任；债务",
"literate|a.有读写能力的",
"livestock|n.牲畜；家畜",
"lucrative|a.有利可图的",
"lure|v.引诱 n.诱惑物",
"mandate|n.授权；命令 v.授权",
"marginal|a.边缘的；微小的",
"masculine|a.男性的；男子气的",
"mediocre|a.平庸的",
"mentor|n.导师",
"merger|n.合并；并购",
"methodology|n.方法论；方法",
"meticulous|a.一丝不苟的",
"mimic|v.模仿",
"minimal|a.最小的；极少的",
"misconception|n.误解；错误观念",
"mitigate|v.减轻；缓和",
"monotonous|a.单调乏味的",
"morale|n.士气；斗志",
"motion|n.运动；提议 v.示意",
"multitude|n.大量；人群",
"municipal|a.市政的",
"niche|n.合适的位置；利基",
"noble|a.高尚的；贵族的",
"nominate|v.提名；任命",
"nostalgia|n.怀旧；乡愁",
"novelty|n.新奇；新颖",
"nuance|n.细微差别",
"nutrient|n.营养物",
"oath|n.誓言；宣誓",
"onset|n.开始；发作",
"opaque|a.不透明的；难懂的",
"outdated|a.过时的",
"outsider|n.局外人",
"overturn|v.推翻；颠覆",
"pandemic|n.流行病 a.大规模流行的",
"paradigm|n.范例；范式",
"peninsula|n.半岛",
"peripheral|a.外围的；次要的",
"persevere|v.坚持不懈",
"persistent|a.坚持不懈的；持续的",
"pesticide|n.杀虫剂",
"posture|n.姿势；态度",
"pragmatic|a.务实的",
"predator|n.捕食者；掠夺者",
"predecessor|n.前任；前辈",
"premature|a.过早的；早产的",
"presume|v.推测；假定",
"prevalent|a.流行的；普遍的",
"probe|v.探测；调查 n.探针",
"proponent|n.支持者；倡导者",
"prototype|n.原型；雏形",
"quantify|v.量化；确定数量",
"quantitative|a.定量的",
"reassure|v.使安心",
"recipient|n.接受者",
"redundant|a.多余的；被裁减的",
"reliance|n.依赖；信赖",
"remnant|n.残余；剩余部分",
"renowned|a.著名的",
"reproach|v./n.责备",
"reptile|n.爬行动物",
"resemblance|n.相似；相似之处",
"resent|v.怨恨；愤恨",
"reside|v.居住；在于",
"resilient|a.有弹性的；能快速恢复的",
"respectable|a.可敬的；体面的",
"retrieve|v.取回；检索",
"revelation|n.揭露；启示",
"reversal|n.逆转；反转",
"revive|v.复兴；苏醒",
"rhetoric|n.修辞；花言巧语",
"rigorous|a.严格的；缜密的",
"ruthless|a.无情的；残忍的",
"salute|v./n.敬礼；致敬",
"scorn|n./v.轻蔑；嘲笑",
"scramble|v.攀爬；抢夺 n.争抢",
"scrap|n.碎片；废料 v.废弃",
"seize|v.抓住；夺取",
"shrewd|a.精明的",
"signify|v.表示；意味着",
"slum|n.贫民窟",
"stimulus|n.刺激（物）；促进因素",
"stun|v.使震惊；打晕",
"stumble|v.绊倒；偶然发现",
"sue|v.起诉；控告",
"summon|v.召唤；召集",
"superb|a.极佳的",
"superficial|a.肤浅的；表面的",
"surpass|v.超过；胜过",
"susceptible|a.易受影响的",
"syndrome|n.综合征；综合症状",
"tactic|n.策略；战术",
"tangible|a.有形的；切实的",
"tolerant|a.宽容的",
"tournament|n.锦标赛；联赛",
"toss|v.扔；抛",
"trivial|a.琐碎的；不重要的",
"underestimate|v.低估",
"unleash|v.释放；发动",
"unprecedented|a.空前的",
"unrest|n.动荡；不安",
"vegetarian|n.素食者",
"versatile|a.多才多艺的；多用途的",
"visualize|v.想象；使形象化",
"vocal|a.直言不讳的；声音的",
"vulnerable|a.脆弱的；易受伤害的",
"wary|a.谨慎的；警惕的",
"wholesale|n./a.批发（的）",
"withhold|v.拒绝给予；扣留"
);
