/* 词库数据 12/12 · Q + R */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"qualification|n.资格；资质；限定",
"qualify|v.（使）具有资格；限定",
"qualitative|a.定性的；质的",
"quality|n.质量；品质；特性",
"quantity|n.数量；量",
"quarrel|v./n.争吵；吵架",
"quart|n.夸脱",
"quarter|n.四分之一；一刻钟；季度",
"quarterly|a.每季的 ad.每季 n.季刊",
"queen|n.女王；王后",
"queer|a.奇怪的；异常的",
"quench|v.解渴；扑灭；抑制",
"quest|n.寻求；探索",
"question|n.问题 v.询问；怀疑",
"questionable|a.可疑的；有问题的",
"queue|n.行列 v.排队",
"quick|a.快的；敏捷的 ad.快",
"quiet|a.安静的 n.安静 v.使安静",
"quilt|n.被子",
"quit|v.停止；离开；辞职",
"quite|ad.相当；十分",
"quiver|v./n.颤抖；哆嗦",
"quiz|n.小测验；智力竞赛",
"quota|n.配额；定额",
"quotation|n.引语；报价",
"quote|v.引用；报价 n.引文",
"rabbit|n.兔子",
"race|n.种族；比赛 v.赛跑",
"racial|a.种族的",
"rack|n.架子；行李架",
"radar|n.雷达",
"radiate|v.辐射；散发",
"radical|a.根本的；激进的 n.激进分子",
"radioactive|a.放射性的",
"radius|n.半径；范围",
"rag|n.破布；碎布",
"rage|n.狂怒 v.发怒；肆虐",
"raid|n./v.袭击；突查",
"rail|n.栏杆；铁轨",
"railroad|n.铁路",
"railway|n.铁路；铁道",
"rain|n.雨 v.下雨",
"rainbow|n.彩虹",
"raise|v.举起；提高；筹集；养育",
"rally|n.集会 v.召集；恢复",
"random|a.随机的 n.随机",
"range|n.范围；山脉 v.（在一定范围内）变动",
"rank|n.军衔；等级 v.排列",
"rapid|a.迅速的；快的",
"rare|a.稀有的；罕见的",
"rarely|ad.很少；难得",
"rat|n.老鼠",
"rate|n.比率；速度 v.评价",
"rather|ad.相当；宁愿",
"ratio|n.比率；比例",
"rational|a.理性的；合理的",
"raw|a.生的；未加工的",
"ray|n.光线；射线",
"razor|n.剃刀",
"reach|v.到达；伸手 n.范围",
"react|v.反应；起作用",
"reaction|n.反应；反作用",
"read|v.读；理解；写明",
"reader|n.读者；读物",
"readily|ad.乐意地；容易地",
"reading|n.阅读；读物；读数",
"ready|a.准备好的；乐意的",
"real|a.真实的；真的",
"realistic|a.现实的；逼真的",
"reality|n.现实；真实",
"realize|v.意识到；实现",
"really|ad.真正地；确实",
"realm|n.领域；王国",
"reap|v.收割；收获",
"rear|n.后面 a.后面的 v.抚养",
"reason|n.原因；理性 v.推理",
"reasonable|a.合理的；通情达理的",
"rebel|n.反叛者 v.反叛",
"rebellion|n.反叛；起义",
"recall|v.回忆起；召回 n.回忆",
"receipt|n.收据；收到",
"receive|v.收到；接待",
"recent|a.最近的；近来的",
"recently|ad.最近；近来",
"reception|n.接待；招待会；接收",
"recipe|n.食谱；方法",
"recite|v.背诵；朗诵",
"reckless|a.鲁莽的；不计后果的",
"reckon|v.认为；估计；指望",
"recognition|n.认出；认可",
"recognize|v.认出；承认",
"recommend|v.推荐；建议",
"reconcile|v.调和；使和解",
"record|n.记录；唱片 v.记录",
"recover|v.恢复；找回",
"recovery|n.恢复；痊愈",
"recruit|v.招募 n.新兵；新成员",
"rectangle|n.长方形；矩形",
"rectangular|a.长方形的",
"recur|v.重现；复发",
"red|a.红色的 n.红色",
"reduce|v.减少；降低",
"reduction|n.减少；缩减",
"refer|v.提及；参考；查阅",
"reference|n.参考；提及；推荐信",
"refine|v.精炼；改进",
"reflect|v.反射；反映；深思",
"reflection|n.反射；倒影；深思",
"reform|v./n.改革；改造",
"refrain|v.抑制；忍住",
"refresh|v.使清新；刷新",
"refreshment|n.点心；恢复精力",
"refrigerator|n.冰箱",
"refuge|n.庇护；避难所",
"refugee|n.难民",
"refund|n./v.退款",
"refusal|n.拒绝",
"refuse|v.拒绝 n.垃圾",
"refute|v.驳斥；反驳",
"regard|v.看待 n.尊重；方面",
"regarding|prep.关于",
"regardless|ad.不管怎样",
"regime|n.政权；制度",
"region|n.地区；区域",
"regional|a.地区的；区域的",
"register|v.登记；注册 n.登记簿",
"regret|v./n.后悔；遗憾",
"regular|a.规则的；经常的；定期的",
"regulate|v.管理；调节",
"regulation|n.规章；管理",
"rehearsal|n.排练；演习",
"reign|v.统治 n.统治时期",
"reinforce|v.加强；加固",
"reject|v.拒绝；排斥",
"relate|v.有关；叙述",
"relation|n.关系；亲属",
"relationship|n.关系；恋爱关系",
"relative|n.亲属 a.相对的",
"relativity|n.相对论；相关性",
"relax|v.放松；松懈",
"relay|v.传送；接替 n.接力",
"release|v./n.释放；发布",
"relevant|a.相关的；切题的",
"reliable|a.可靠的；可信赖的",
"relief|n.宽慰；救济；减轻",
"relieve|v.缓解；救济；换班",
"religion|n.宗教；信仰",
"religious|a.宗教的；虔诚的",
"reluctant|a.不情愿的；勉强的",
"rely|v.依赖；信赖",
"remain|v.保持；剩下；仍然是",
"remainder|n.剩余物；余数",
"remark|n./v.评论；言辞",
"remarkable|a.非凡的；显著的",
"remedy|n.药物；补救办法 v.补救",
"remember|v.记得；想起",
"remind|v.提醒；使想起",
"remote|a.遥远的；偏远的；冷淡的",
"removal|n.移走；免除",
"remove|v.移开；去除；免职",
"render|v.使成为；给予；提供",
"renew|v.更新；续订；恢复",
"rent|v.租 n.租金",
"repair|v./n.修理；修补",
"repay|v.偿还；报答",
"repeat|v./n.重复；重说",
"repel|v.击退；排斥",
"repetition|n.重复；反复",
"replace|v.取代；更换",
"replacement|n.替换；替代者",
"reply|v./n.回答；答复",
"report|v.报告；报道 n.报告",
"reporter|n.记者",
"represent|v.代表；表示；描绘",
"representative|n.代表 a.典型的",
"reproduce|v.复制；繁殖",
"republic|n.共和国",
"reputation|n.名声；声誉",
"request|n./v.请求；要求",
"require|v.需要；要求",
"requirement|n.要求；必要条件",
"rescue|v./n.营救；救援",
"research|n./v.研究；调查",
"resemble|v.像；类似于",
"reservation|n.预订；保留",
"reserve|v.保留；预订 n.储备",
"reservoir|n.水库；蓄水池",
"residence|n.住宅；居住",
"resident|n.居民 a.定居的",
"resist|v.抵抗；抵制",
"resistance|n.抵抗；阻力；电阻",
"resolve|v.解决；决心 n.决心",
"resort|v.诉诸 n.度假地；手段",
"resource|n.资源；才智",
"respect|v./n.尊重；方面",
"respectful|a.恭敬的；有礼貌的",
"respective|a.各自的；分别的",
"respectively|ad.分别地；各自地",
"respond|v.回答；反应",
"response|n.回答；反应",
"responsibility|n.责任；职责",
"responsible|a.负责的；尽责的",
"rest|n.休息；其余 v.休息",
"restaurant|n.餐馆；饭店",
"restless|a.焦躁不安的；得不到休息的",
"restore|v.恢复；修复；归还",
"restrain|v.抑制；限制",
"restraint|n.抑制；约束",
"restrict|v.限制；约束",
"restriction|n.限制；约束",
"result|n.结果 v.导致；结果是",
"resume|v.恢复；重新开始 n.简历",
"retail|n./v.零售",
"retain|v.保留；保持",
"retire|v.退休；退出",
"retreat|v./n.撤退；退避",
"return|v.返回；归还 n.返回",
"reveal|v.揭示；透露",
"revenge|n./v.报复；报仇",
"revenue|n.收入；税收",
"reverse|v.颠倒；倒车 a.相反的",
"review|v./n.复习；评论",
"revise|v.修改；修订",
"revolt|v./n.反叛；反抗",
"revolution|n.革命；巨变；旋转",
"revolutionary|a.革命的 n.革命者",
"reward|n./v.报答；奖赏",
"rhythm|n.节奏；韵律",
"ribbon|n.丝带；带子",
"rice|n.米；米饭",
"rich|a.富有的；丰富的",
"rid|v.摆脱；去掉",
"riddle|n.谜；谜语",
"ride|v.骑；乘 n.乘车",
"ridge|n.山脊；屋脊",
"ridiculous|a.荒谬的；可笑的",
"rifle|n.步枪",
"right|a.正确的；右边的 n.权利 ad.正好",
"rigid|a.僵硬的；严格的",
"rim|n.边缘；（圆形物的）边",
"ring|n.戒指；铃声 v.打电话；（铃）响",
"riot|n.暴乱；骚乱",
"rip|v.撕；扯 n.裂口",
"ripe|a.成熟的",
"rise|v.上升；起立 n.增加",
"risk|n.风险 v.冒险",
"ritual|n.仪式；例行程序 a.仪式的",
"rival|n.竞争者 v.与…竞争",
"river|n.河；江",
"road|n.路；道路",
"roar|v.咆哮；轰鸣 n.吼声",
"roast|v.烤；烘烤",
"rob|v.抢劫；盗取",
"robot|n.机器人",
"robust|a.强健的；坚固的",
"rock|n.岩石 v.摇动",
"rocket|n.火箭 v.猛涨",
"rod|n.杆；棒",
"role|n.角色；作用",
"roll|v.滚动；卷 n.卷；名册",
"romance|n.浪漫；爱情故事",
"romantic|a.浪漫的；不切实际的",
"roof|n.屋顶；顶部",
"room|n.房间；空间",
"root|n.根；根源 v.生根",
"rope|n.绳；索",
"rose|n.玫瑰",
"rot|v.腐烂；腐朽",
"rotate|v.旋转；轮流",
"rotten|a.腐烂的；糟糕的",
"rough|a.粗糙的；粗略的；艰难的",
"round|a.圆的 prep.围绕 n.一轮",
"rouse|v.唤醒；激起",
"route|n.路线；路途",
"routine|n.常规 a.日常的",
"row|n.排；划船 v.划船",
"royal|a.王室的；皇家的",
"royalty|n.王室成员；版税",
"rub|v.擦；摩擦",
"rubber|n.橡胶；橡皮",
"rubbish|n.垃圾；废话",
"rude|a.粗鲁的；无礼的",
"rug|n.小地毯",
"ruin|v.毁坏 n.毁灭；废墟",
"rule|n.规则；统治 v.统治",
"ruler|n.统治者；尺子",
"rumor|n.谣言；传闻",
"run|v.跑；经营；运转 n.奔跑",
"rural|a.农村的；乡村的",
"rush|v.冲；仓促 n.匆忙",
"rust|n.锈 v.生锈"
);
