/* 词库数据 9/12 · J + K + L */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"jacket|n.夹克；外套",
"jail|n.监狱 v.监禁",
"jam|n.果酱；拥挤；堵塞",
"january|n.一月",
"jar|n.罐子；广口瓶",
"jaw|n.颌；下巴",
"jazz|n.爵士乐",
"jealous|a.嫉妒的；猜疑的",
"jealousy|n.嫉妒；猜忌",
"jeans|n.牛仔裤",
"jeep|n.吉普车",
"jet|n.喷气式飞机；喷射 v.乘喷气机",
"jewel|n.宝石；珠宝",
"jewelry|n.珠宝；首饰",
"job|n.工作；职业；职责",
"jog|v.慢跑；轻推",
"join|v.加入；连接",
"joint|a.共同的 n.关节；接头",
"joke|n.笑话 v.开玩笑",
"journal|n.杂志；日报；日志",
"journalist|n.记者；新闻工作者",
"journey|n.旅行；旅程",
"joy|n.欢乐；乐趣",
"judge|n.法官；裁判 v.判断",
"judgment|n.判断；判决；判断力",
"juice|n.果汁；汁",
"juicy|a.多汁的；生动有趣的",
"july|n.七月",
"jump|v.跳；暴涨 n.跳跃；猛增",
"june|n.六月",
"jungle|n.丛林；密林",
"junior|a.年少的；初级的 n.晚辈",
"junk|n.废旧物品；垃圾",
"jury|n.陪审团；评奖团",
"just|ad.刚才；只是；正好 a.公正的",
"justice|n.正义；公正；司法",
"justify|v.证明…正当；为…辩护",
"juvenile|a.青少年的；幼稚的",
"keen|a.热衷的；敏锐的；强烈的",
"keep|v.保持；保存；饲养",
"kettle|n.水壶",
"key|n.钥匙；答案；关键 a.关键的",
"keyboard|n.键盘",
"kick|v./n.踢",
"kid|n.小孩 v.开玩笑",
"kidney|n.肾脏",
"kill|v.杀死；消磨（时间）",
"kilogram|n.千克",
"kilometer|n.千米；公里",
"kind|n.种类 a.善良的",
"kindergarten|n.幼儿园",
"kindness|n.仁慈；好意",
"king|n.国王",
"kingdom|n.王国；界；领域",
"kiss|v./n.吻",
"kit|n.成套工具；成套用品",
"kitchen|n.厨房",
"kite|n.风筝",
"knee|n.膝盖",
"kneel|v.跪下",
"knife|n.刀",
"knit|v.编织；紧密结合",
"knock|v./n.敲；碰撞",
"knot|n.结；节 v.打结",
"know|v.知道；了解；认识",
"knowledge|n.知识；学问",
"lab|n.实验室",
"label|n.标签 v.贴标签于；把…称为",
"labor|n.劳动；劳动力；分娩",
"laboratory|n.实验室",
"lace|n.花边；鞋带",
"lack|n./v.缺乏；不足",
"ladder|n.梯子；途径",
"lady|n.女士；夫人",
"lag|v.落后 n.滞后；时间间隔",
"lake|n.湖",
"lamb|n.羔羊；羊羔肉",
"lame|a.跛的；站不住脚的",
"lamp|n.灯；油灯",
"land|n.陆地；土地 v.着陆",
"landlady|n.女房东；女地主",
"landlord|n.房东；地主",
"landscape|n.风景；景色；形势",
"lane|n.小巷；车道；跑道",
"language|n.语言；措辞",
"lantern|n.灯笼；提灯",
"lap|n.大腿面；一圈",
"laptop|n.笔记本电脑",
"large|a.大的；大量的",
"largely|ad.主要地；大部分",
"laser|n.激光",
"last|a.最后的 v.持续 ad.最后",
"late|a.晚的；已故的 ad.晚",
"lately|ad.最近；不久前",
"latent|a.潜在的；潜伏的",
"later|ad.后来 a.后来的",
"latter|a.后者的；后面的",
"laugh|v.笑 n.笑声",
"laughter|n.笑；笑声",
"launch|v.发射；发起；推出 n.发射",
"laundry|n.洗衣店；要洗的衣物",
"lavatory|n.厕所；盥洗室",
"law|n.法律；定律；规律",
"lawn|n.草坪；草地",
"lawyer|n.律师",
"lay|v.放置；产卵；铺设",
"layer|n.层；阶层",
"layoff|n.裁员；暂时解雇",
"layout|n.布局；版面设计",
"lazy|a.懒惰的；懒散的",
"lead|v.引导；领先 n.领先；主角",
"leader|n.领导者；领袖",
"leadership|n.领导；领导层",
"leading|a.领先的；主要的",
"leaf|n.叶；一页",
"leaflet|n.传单；散页印刷品",
"league|n.联盟；同盟",
"leak|v.漏；泄露 n.漏洞；泄露",
"lean|v.倾斜；倚靠 a.瘦的；精干的",
"leap|v./n.跳跃；激增",
"learn|v.学习；得知",
"learned|a.博学的；学术性的",
"learning|n.学习；学问",
"lease|n.租约 v.出租",
"least|a.最少的 ad.最少",
"leather|n.皮革；皮制品",
"leave|v.离开；留下 n.休假",
"lecture|n.讲座；训诫 v.讲课",
"left|a.左边的 n.左边",
"leg|n.腿；支柱",
"legacy|n.遗产；遗留问题",
"legal|a.合法的；法律的",
"legend|n.传说；传奇人物",
"legislation|n.立法；法律",
"legitimate|a.合法的；正当的",
"leisure|n.闲暇；休闲",
"lemon|n.柠檬",
"lend|v.借出；贷（款）",
"length|n.长度；期间",
"lengthy|a.漫长的；冗长的",
"lens|n.透镜；镜片；镜头",
"less|a./ad.更少的（地）",
"lesson|n.课；教训",
"lest|conj.唯恐；以免",
"let|v.让；允许；出租",
"letter|n.信；字母",
"level|n.水平面；水平；级别 a.平的",
"liable|a.易于…的；有义务的",
"liberal|a.自由的；开明的 n.自由主义者",
"liberate|v.解放；释放",
"liberty|n.自由；释放",
"librarian|n.图书管理员",
"library|n.图书馆；藏书",
"license|n.执照；许可 v.发许可证",
"lid|n.盖子",
"lie|v.躺；位于；说谎 n.谎言",
"life|n.生命；生活；一生",
"lifetime|n.一生；终身",
"lift|v.提起；抬起 n.电梯；搭便车",
"light|n.光；灯 a.轻的；明亮的 v.点燃",
"lightning|n.闪电",
"like|v.喜欢 prep.像 conj.如同",
"likelihood|n.可能性",
"likely|a.可能的 ad.很可能",
"likewise|ad.同样地；也",
"limb|n.肢；臂；分支",
"lime|n.酸橙；石灰",
"limit|n.限度；限制 v.限制",
"limitation|n.限制；局限",
"limited|a.有限的",
"limp|a.柔软的；无力的 v.跛行",
"line|n.线；行；航线 v.排队",
"linear|a.线的；线性的",
"linen|n.亚麻布；亚麻织物",
"linger|v.逗留；继续存留",
"linguistic|a.语言的；语言学的",
"link|v.连接 n.联系；链接",
"lion|n.狮子",
"lip|n.嘴唇",
"liquid|n.液体 a.液体的",
"liquor|n.烈性酒",
"list|n.名单 v.列出",
"listen|v.听；听从",
"liter|n.升",
"literacy|n.读写能力；素养",
"literally|ad.字面上；真正地",
"literary|a.文学的；书面的",
"literature|n.文学；文献",
"litter|n.垃圾 v.乱扔杂物",
"little|a.小的；少的 ad.很少",
"live|v.生活；居住 a.活的；现场的",
"lively|a.活泼的；生动的",
"liver|n.肝脏",
"living|a.活着的 n.生计",
"load|n.负荷；装载 v.装载",
"loaf|n.一条（面包）",
"loan|n.贷款 v.借出",
"lobby|n.大堂；游说团体 v.游说",
"lobster|n.龙虾",
"local|a.当地的；局部的 n.当地人",
"locality|n.地点；地区",
"locate|v.找到位置；使坐落于",
"location|n.位置；地点",
"lock|v.锁上 n.锁",
"locker|n.寄物柜",
"locomotive|n.火车头 a.运动的",
"lodge|v.暂住；提出 n.小屋",
"lofty|a.崇高的；高耸的",
"log|n.原木；日志 v.记录",
"logic|n.逻辑；逻辑学",
"logical|a.合乎逻辑的",
"lonely|a.孤独的；偏僻的",
"long|a.长的；长久的 ad.长久 v.渴望",
"longing|n.渴望 a.渴望的",
"longitude|n.经度",
"look|v.看；显得 n.看；样子",
"loom|v.隐约出现；逼近 n.织布机",
"loop|n.圈；环 v.成环",
"loose|a.松的；宽松的",
"lord|n.勋爵；上帝",
"lorry|n.卡车",
"lose|v.丢失；输；迷失",
"loss|n.丧失；损失；亏损",
"lot|n.许多；一块地；命运",
"lottery|n.彩票；抽奖",
"loud|a.响亮的；喧闹的",
"loudspeaker|n.扬声器；喇叭",
"lounge|n.休息室 v.懒洋洋地坐",
"love|v.爱；喜爱 n.爱",
"lovely|a.可爱的；令人愉快的",
"lover|n.爱人；爱好者",
"low|a.低的；低下的 ad.低",
"lower|v.降低 a.较低的",
"loyal|a.忠诚的；忠心的",
"loyalty|n.忠诚；忠心",
"luck|n.运气；好运",
"lucky|a.幸运的",
"luggage|n.行李",
"lump|n.团；块；肿块",
"lunch|n.午餐",
"lung|n.肺",
"luxury|n.奢侈（品） a.奢华的"
);
