/* 词库数据 10/12 · M + N */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"machine|n.机器；机械",
"machinery|n.机械（总称）；机构",
"mad|a.疯狂的；狂热的；恼火的",
"magazine|n.杂志；弹仓",
"magic|n.魔法；魔术 a.有魔力的",
"magistrate|n.地方法官；治安官",
"magnet|n.磁铁；有吸引力的人（物）",
"magnetic|a.磁的；有吸引力的",
"magnificent|a.壮丽的；宏伟的",
"magnify|v.放大；夸大",
"maid|n.女仆；少女",
"mail|n.邮件 v.邮寄",
"mailbox|n.邮箱；信箱",
"main|a.主要的 n.总管道",
"mainland|n.大陆；本土",
"mainly|ad.主要地；大部分",
"maintain|v.维持；保养；主张",
"maintenance|n.维护；保养",
"major|a.主要的 n.专业 v.主修",
"majority|n.大多数",
"make|v.做；制造；使得 n.牌子",
"makeup|n.化妆品；组成；性格",
"male|a.雄的；男性的 n.男子",
"mall|n.购物中心",
"mammal|n.哺乳动物",
"man|n.男人；人；人类",
"manage|v.管理；设法做到",
"management|n.管理；管理层",
"manager|n.经理；管理人",
"maneuver|n.策略；演习 v.操纵",
"manifest|a.明显的 v.表明；显现",
"manipulate|v.操纵；控制；摆布",
"mankind|n.人类",
"manner|n.方式；举止；礼貌",
"manual|a.手工的 n.手册",
"manufacture|v.制造；编造 n.制造",
"manufacturer|n.制造商；厂商",
"manuscript|n.手稿；原稿",
"many|a.许多的 pron.许多",
"map|n.地图 v.绘制地图",
"marathon|n.马拉松赛跑",
"marble|n.大理石；弹珠",
"march|v.行军；游行 n.行进",
"margin|n.边缘；余地；利润",
"marine|a.海的；海生的 n.海军陆战队",
"mark|n.记号；分数 v.标记；打分",
"market|n.市场 v.销售",
"marketing|n.营销；销售",
"marriage|n.结婚；婚姻",
"married|a.已婚的",
"marry|v.结婚；娶；嫁",
"marvelous|a.了不起的；非凡的",
"mask|n.面具；口罩 v.掩饰",
"mass|n.大量；质量；群众 a.大规模的",
"massacre|n./v.大屠杀",
"massive|a.巨大的；大规模的",
"master|n.主人；硕士；大师 v.精通",
"masterpiece|n.杰作",
"mat|n.垫子；席子",
"match|n.比赛；对手；火柴 v.匹配",
"mate|n.伙伴；配偶 v.交配",
"material|n.材料 a.物质的",
"maternal|a.母亲的；母系的",
"mathematical|a.数学的",
"mathematics|n.数学",
"matter|n.事情；问题；物质 v.要紧",
"mature|a.成熟的 v.成熟",
"maximum|n.最大值 a.最大的",
"may|v.可以；可能 n.五月",
"maybe|ad.也许；大概",
"mayor|n.市长",
"meal|n.一餐；膳食",
"mean|v.意指；意味着 a.卑鄙的；吝啬的",
"meaning|n.意义；含义",
"means|n.手段；方法；财力",
"meantime|n.其间 ad.同时",
"meanwhile|ad.同时；其间",
"measure|v.测量 n.措施；尺寸",
"measurement|n.测量；尺寸",
"meat|n.肉",
"mechanic|n.技工；机械工",
"mechanical|a.机械的；呆板的",
"mechanism|n.机制；机械装置",
"medal|n.奖章；勋章",
"media|n.媒体",
"medical|a.医学的；医疗的",
"medicine|n.医学；药",
"medieval|a.中世纪的",
"medium|a.中等的 n.媒介；手段",
"meet|v.遇见；满足；开会",
"meeting|n.会议；相遇",
"melody|n.旋律；曲调",
"melt|v.融化；熔化；消融",
"member|n.成员；会员",
"membership|n.会员身份；成员资格",
"memo|n.备忘录",
"memorial|n.纪念碑 a.纪念的",
"memory|n.记忆；回忆；内存",
"menace|n.威胁 v.威胁",
"mend|v.修理；缝补；改善",
"mental|a.精神的；智力的",
"mention|v./n.提到；说起",
"menu|n.菜单",
"merchandise|n.商品；货物",
"merchant|n.商人",
"mercury|n.水银；汞",
"mercy|n.仁慈；宽恕",
"mere|a.仅仅的；只不过",
"merely|ad.仅仅；只不过",
"merge|v.合并；融合",
"merit|n.优点；价值 v.值得",
"merry|a.快乐的；愉快的",
"mess|n.混乱；脏乱 v.弄乱",
"message|n.消息；信息；启示",
"messenger|n.信使；送信人",
"metal|n.金属",
"metaphor|n.隐喻；暗喻",
"meter|n.米；计；表",
"method|n.方法；办法",
"metric|a.公制的；米制的",
"metropolitan|a.大都市的",
"microscope|n.显微镜",
"microwave|n.微波；微波炉",
"midday|n.正午",
"middle|n.中间 a.中间的",
"midnight|n.午夜",
"midst|n.中部；中间",
"might|v.aux.可能 n.力量",
"migrate|v.迁徙；移居",
"mild|a.温和的；轻微的",
"mile|n.英里",
"militant|a.激进的 n.激进分子",
"military|a.军事的 n.军队",
"milk|n.牛奶 v.挤奶",
"mill|n.磨坊；工厂",
"million|num.百万",
"millionaire|n.百万富翁",
"mind|n.头脑；想法 v.介意；注意",
"mine|pron.我的 n.矿 v.采矿",
"mineral|n.矿物 a.矿物的",
"mingle|v.混合；交往",
"miniature|a.微型的 n.缩微模型",
"minimize|v.使减到最少；最小化",
"minimum|n.最小值 a.最小的",
"minister|n.部长；大臣；牧师",
"ministry|n.（政府的）部",
"minor|a.较小的；次要的 n.未成年人",
"minority|n.少数；少数民族",
"minute|n.分钟；一会儿 a.微小的",
"miracle|n.奇迹",
"mirror|n.镜子 v.反映",
"mischief|n.恶作剧；危害",
"miserable|a.痛苦的；悲惨的",
"misery|n.痛苦；悲惨",
"misfortune|n.不幸；灾难",
"mislead|v.误导；引入歧途",
"missile|n.导弹；发射物",
"missing|a.丢失的；失踪的",
"mission|n.使命；任务；代表团",
"mist|n.薄雾",
"mistake|n.错误 v.弄错",
"mister|n.先生",
"mistress|n.女主人；情妇",
"misunderstand|v.误解；误会",
"mix|v.混合；配制 n.混合物",
"mixture|n.混合；混合物",
"moan|v./n.呻吟；抱怨",
"mobile|a.移动的 n.手机",
"mobilize|v.动员；调动",
"mock|v.嘲笑 a.模拟的",
"mode|n.方式；风格；模式",
"model|n.模型；模范；模特 v.模仿",
"moderate|a.温和的；适度的 v.缓和",
"modern|a.现代的；新式的",
"modest|a.谦虚的；适度的",
"modify|v.修改；修饰",
"module|n.模块；组件",
"moist|a.潮湿的",
"moisture|n.水分；湿气",
"molecule|n.分子",
"moment|n.时刻；瞬间",
"momentum|n.动量；势头",
"monarchy|n.君主制；君主政体",
"monday|n.星期一",
"monetary|a.货币的；金融的",
"money|n.钱；货币",
"monitor|v.监控 n.监视器；班长",
"monkey|n.猴子",
"monopoly|n.垄断；专卖",
"monster|n.怪物；巨兽",
"month|n.月；月份",
"monthly|a.每月的 n.月刊",
"monument|n.纪念碑；遗迹",
"mood|n.心情；语气；气氛",
"moon|n.月亮；月球",
"moral|a.道德的 n.寓意；道德",
"morality|n.道德；道德观",
"more|a./ad.更多的（地）",
"moreover|ad.而且；此外",
"morning|n.早晨；上午",
"mortal|a.终有一死的；致命的 n.凡人",
"mortgage|n.抵押贷款 v.抵押",
"mosquito|n.蚊子",
"most|a.最多的 ad.最；极其",
"mostly|ad.主要地；通常",
"motel|n.汽车旅馆",
"mother|n.母亲",
"motivate|v.激励；激发",
"motivation|n.动机；积极性",
"motive|n.动机；目的",
"motor|n.发动机；马达",
"motorcycle|n.摩托车",
"motorway|n.高速公路",
"mount|v.登上；安装 n.山",
"mountain|n.山；山脉",
"mourn|v.哀悼；悲伤",
"mouse|n.老鼠；鼠标",
"mouth|n.嘴；口；出口",
"move|v.移动；感动 n.行动；搬家",
"movement|n.运动；动作；乐章",
"movie|n.电影",
"much|ad.非常 a.许多的",
"mud|n.泥；泥浆",
"multiple|a.多样的；多重的 n.倍数",
"multiply|v.乘；增加；繁殖",
"murder|v./n.谋杀",
"muscle|n.肌肉；力量",
"museum|n.博物馆",
"mushroom|n.蘑菇 v.迅速增长",
"music|n.音乐；乐曲",
"musical|a.音乐的 n.音乐剧",
"musician|n.音乐家",
"must|v.aux.必须 n.必需品",
"mutual|a.相互的；共同的",
"my|pron.我的",
"myself|pron.我自己",
"mystery|n.神秘；谜",
"myth|n.神话；虚构的事",
"nail|n.钉子；指甲 v.钉",
"naive|a.天真的；幼稚的",
"naked|a.裸体的；无遮盖的",
"name|n.名字；名声 v.命名",
"namely|ad.即；也就是",
"nap|n.小睡；打盹",
"napkin|n.餐巾",
"narrative|n.叙述；故事 a.叙事的",
"narrow|a.狭窄的；狭隘的 v.变窄",
"nasty|a.恶劣的；讨厌的；下流的",
"nation|n.国家；民族",
"national|a.国家的；民族的 n.国民",
"nationality|n.国籍；民族",
"native|a.本地的；与生俱来的 n.本地人",
"natural|a.自然的；天生的",
"naturally|ad.自然地；天生地",
"nature|n.自然；本性；性质",
"naval|a.海军的",
"navigate|v.导航；航行",
"navy|n.海军",
"near|ad./prep.接近 a.近的",
"nearby|a.附近的 ad.在附近",
"nearly|ad.几乎；差不多",
"neat|a.整洁的；利索的",
"necessary|a.必要的 n.必需品",
"necessity|n.必要性；必需品",
"neck|n.颈；脖子",
"necklace|n.项链",
"need|v.需要 n.需要；贫困",
"needle|n.针；指针",
"negative|a.否定的；消极的；负的 n.底片",
"neglect|v./n.忽视；疏忽",
"negotiate|v.谈判；协商",
"negotiation|n.谈判；协商",
"neighbor|n.邻居；邻国",
"neighborhood|n.街区；邻近地区",
"neither|pron.两者都不 conj.也不",
"nephew|n.侄子；外甥",
"nerve|n.神经；勇气",
"nervous|a.紧张的；神经的",
"nest|n.巢；窝 v.筑巢",
"net|n.网；网络 a.净的",
"network|n.网络；网状系统",
"neutral|a.中立的；中性的",
"nevertheless|ad.然而；不过",
"news|n.新闻；消息",
"newspaper|n.报纸",
"next|a.下一个的 ad.随后",
"nice|a.好的；友好的",
"nickel|n.镍；五分硬币",
"nickname|n.绰号 v.给…起绰号",
"niece|n.侄女；外甥女",
"night|n.夜；夜晚",
"nightmare|n.噩梦；可怕的经历",
"nine|num.九",
"nineteen|num.十九",
"ninety|num.九十",
"nitrogen|n.氮",
"no|ad.不 a.没有的",
"nobody|pron.没有人 n.无名之辈",
"nod|v.点头；打盹 n.点头",
"noise|n.噪音；喧闹声",
"noisy|a.嘈杂的；喧闹的",
"none|pron.没有一个 ad.绝不",
"nonetheless|ad.然而；尽管如此",
"nonsense|n.胡说；废话",
"noodle|n.面条",
"noon|n.正午；中午",
"nor|conj.也不",
"norm|n.标准；规范",
"normal|a.正常的；标准的",
"normally|ad.通常；正常地",
"north|n.北方 a.北方的",
"northeast|n.东北 a.东北的",
"northern|a.北方的；北部的",
"northwest|n.西北 a.西北的",
"nose|n.鼻子；嗅觉",
"not|ad.不；没有",
"notable|a.值得注意的；显著的",
"notably|ad.尤其；显著地",
"note|n.笔记；纸币；音符 v.注意",
"notebook|n.笔记本",
"nothing|pron.什么也没有 n.无关紧要的事",
"notice|v.注意到 n.通知；预告",
"noticeable|a.明显的；引人注目的",
"notify|v.通知；报告",
"notion|n.观念；想法",
"notorious|a.臭名昭著的",
"notwithstanding|prep./ad.尽管；虽然",
"noun|n.名词",
"nourish|v.滋养；培育",
"novel|n.小说 a.新颖的",
"now|ad.现在；立刻",
"nowhere|ad.任何地方都不",
"nuclear|a.核的；原子核的",
"nucleus|n.核心；原子核",
"nuisance|n.讨厌的人（事）；麻烦",
"number|n.数字；号码 v.编号",
"numerical|a.数字的；用数字表示的",
"numerous|a.众多的；许多的",
"nurse|n.护士；保姆 v.护理",
"nursery|n.托儿所；苗圃",
"nurture|v.养育；培养 n.教养",
"nut|n.坚果；螺母",
"nutrition|n.营养；滋养",
"nylon|n.尼龙"
);
