/* 词库数据 14/16 · S (q–z) + T */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"square|n.正方形；广场 a.平方的；正方形的",
"squeeze|v.挤压；榨 n.挤压",
"stability|n.稳定（性）",
"stable|a.稳定的 n.马厩",
"stack|n.堆 v.堆放",
"stadium|n.体育场",
"staff|n.员工；全体人员",
"stage|n.阶段；舞台 v.上演",
"stain|n.污点 v.玷污",
"stair|n.楼梯",
"staircase|n.楼梯间",
"stake|n.桩；股份；赌注",
"stale|a.不新鲜的；陈腐的",
"stamp|n.邮票；印章 v.盖印",
"stand|v.站立；忍受 n.立场；看台",
"standard|n.标准 a.标准的",
"standpoint|n.立场；观点",
"star|n.星；明星 v.主演",
"stare|v./n.凝视；盯着看",
"start|v.开始；出发 n.开始",
"startle|v.使惊吓；使吃惊",
"starve|v.饿死；饥饿",
"state|n.状态；国家；州 v.陈述",
"statement|n.陈述；声明；报表",
"statesman|n.政治家",
"static|a.静态的；静止的",
"station|n.站；台；车站",
"statistics|n.统计学；统计数据",
"statue|n.雕像",
"status|n.地位；身份；状况",
"stay|v.停留；保持 n.逗留",
"steady|a.稳定的；平稳的 v.使稳定",
"steak|n.牛排；肉排",
"steal|v.偷；窃取",
"steam|n.蒸汽 v.蒸发",
"steel|n.钢；钢铁",
"steep|a.陡峭的；急剧的",
"steer|v.驾驶；引导",
"stem|n.茎；词干 v.起源于",
"step|n.步骤；脚步 v.踩；踏",
"stereotype|n.刻板印象；陈规",
"stick|n.棍；棒 v.粘住；坚持",
"sticky|a.粘的；棘手的",
"stiff|a.僵硬的；生硬的",
"still|ad.仍然 a.静止的 n.定格画面",
"stimulate|v.刺激；激励",
"sting|v.刺；叮 n.刺痛",
"stir|v.搅拌；激起",
"stock|n.股票；库存；血统 v.储备",
"stomach|n.胃；胃部",
"stone|n.石头",
"stop|v.停止；阻止 n.车站",
"storage|n.存储；保管",
"store|n.商店 v.储存",
"storm|n.暴风雨 v.猛攻",
"story|n.故事；报道；楼层",
"stove|n.炉子",
"straight|a.直的 ad.直接地",
"straightforward|a.直接的；坦率的；简单的",
"strain|n.压力；拉紧 v.拉紧；损伤",
"strange|a.奇怪的；陌生的",
"stranger|n.陌生人",
"strap|n.带子 v.捆绑",
"strategic|a.战略的",
"strategy|n.战略；策略",
"straw|n.稻草；吸管",
"stream|n.小溪；流 v.流出",
"street|n.街道",
"strength|n.力量；强度",
"strengthen|v.加强；增强",
"stress|n.压力；重音；强调 v.强调",
"stretch|v.伸展；延伸 n.一段时间",
"strict|a.严格的；严谨的",
"stride|v.大步走 n.大步；进展",
"strike|v.罢工；打击；给…印象 n.罢工",
"striking|a.显著的；惊人的",
"string|n.线；弦；一串",
"strip|v.剥离；脱去 n.条；带",
"stripe|n.条纹",
"strive|v.努力；奋斗",
"stroke|n.中风；击；笔画 v.抚摸",
"strong|a.强壮的；强烈的",
"structure|n.结构；建筑物 v.构建",
"struggle|v./n.斗争；奋斗",
"stubborn|a.顽固的；固执的",
"student|n.学生",
"studio|n.工作室；演播室",
"study|v.学习；研究 n.书房；研究",
"stuff|n.东西；材料 v.填满",
"stupid|a.愚蠢的；笨的",
"style|n.风格；款式 v.设计",
"subject|n.主题；科目；主语 a.易受…的",
"subjective|a.主观的",
"submerge|v.淹没；潜入水中",
"submit|v.提交；服从",
"subscribe|v.订阅；赞成",
"subsequent|a.随后的；后来的",
"subsidy|n.补贴；津贴",
"substance|n.物质；实质",
"substantial|a.大量的；实质的",
"substitute|n.代替者 v.代替",
"subtle|a.微妙的；精细的",
"subtract|v.减去",
"suburb|n.郊区",
"subway|n.地铁",
"succeed|v.成功；继承",
"success|n.成功；成功的人（事）",
"successful|a.成功的",
"succession|n.连续；继承",
"successive|a.连续的；相继的",
"successor|n.继承者；接任者",
"such|a.这样的 pron.这样的人（物）",
"suck|v.吸；吮",
"sudden|a.突然的",
"suffer|v.遭受；受苦",
"sufficient|a.足够的；充分的",
"sugar|n.糖",
"suggest|v.建议；暗示",
"suggestion|n.建议；暗示",
"suicide|n.自杀",
"suit|n.套装；诉讼 v.适合",
"suitable|a.合适的；适宜的",
"suitcase|n.手提箱",
"sum|n.总和；算术 v.总结",
"summarize|v.总结；概括",
"summary|n.摘要；总结",
"summer|n.夏天；夏季",
"summit|n.峰会；顶峰",
"sun|n.太阳",
"sunday|n.星期日",
"sunlight|n.日光；阳光",
"sunny|a.晴朗的；欢快的",
"sunrise|n.日出",
"sunset|n.日落",
"sunshine|n.阳光；晴天",
"supermarket|n.超市",
"supper|n.晚餐",
"supplement|n.补充；增刊 v.补充",
"supply|v.供应 n.供应；补给",
"support|v./n.支持；供养",
"suppose|v.假设；认为",
"suppress|v.压制；抑制",
"supreme|a.最高的；至高无上的",
"sure|a.确信的 ad.当然",
"surface|n.表面；外表 v.浮出水面",
"surgery|n.外科手术；诊所",
"surplus|n.过剩；顺差 a.过剩的",
"surprise|n./v.惊讶；使惊奇",
"surrender|v.投降；放弃",
"surround|v.包围；环绕",
"survey|n.调查 v.调查；眺望",
"survive|v.幸存；比…活得长",
"suspect|v.怀疑 n.嫌疑人",
"suspend|v.暂停；悬挂",
"suspicion|n.怀疑；疑心",
"suspicious|a.怀疑的；可疑的",
"sustain|v.维持；遭受；支撑",
"swallow|v.吞下；轻信 n.燕子",
"swear|v.发誓；咒骂",
"sweat|n.汗 v.出汗",
"sweater|n.毛衣",
"sweep|v.打扫；掠过",
"sweet|a.甜的；甜美的 n.糖果",
"swell|v.膨胀；增大",
"swift|a.迅速的；敏捷的",
"swim|v.游泳",
"swing|v.摇摆；摆动 n.秋千",
"switch|v.转换 n.开关；转变",
"sword|n.剑；刀",
"symbol|n.象征；符号",
"sympathetic|a.同情的；赞同的",
"sympathize|v.同情；赞同",
"sympathy|n.同情；赞同",
"symptom|n.症状；征兆",
"synthesis|n.综合；合成",
"synthetic|a.合成的；人造的",
"system|n.系统；制度",
"systematic|a.系统的；有条理的",
"table|n.桌子；表格",
"tablet|n.药片；平板电脑",
"tackle|v.处理；对付 n.用具",
"tag|n.标签",
"tail|n.尾巴；尾部",
"tailor|n.裁缝 v.调整；使适应",
"take|v.拿；带；花费；接受",
"tale|n.故事；传说",
"talent|n.天赋；人才",
"talk|v.谈话；讨论 n.谈话；演讲",
"tall|a.高的",
"tame|a.驯服的 v.驯化",
"tank|n.箱；罐；坦克",
"tap|v.轻敲；开发利用 n.水龙头",
"tape|n.磁带；胶带",
"target|n.目标；靶子 v.以…为目标",
"tariff|n.关税；收费表",
"task|n.任务；工作",
"taste|n.味道；品味 v.品尝",
"tax|n.税 v.征税",
"taxi|n.出租车",
"tea|n.茶；茶叶",
"teach|v.教；讲授",
"teacher|n.教师",
"team|n.队；组 v.合作",
"tear|v.撕 n.眼泪",
"technical|a.技术的；工艺的",
"technician|n.技术人员",
"technique|n.技术；技巧",
"technology|n.技术；工艺",
"tedious|a.乏味的；冗长的",
"teenager|n.青少年",
"telegram|n.电报",
"telephone|n.电话 v.打电话",
"telescope|n.望远镜",
"television|n.电视",
"tell|v.告诉；讲述；分辨",
"temper|n.脾气；心情",
"temperament|n.性格；气质",
"temperature|n.温度；体温",
"temple|n.庙宇；太阳穴",
"temporary|a.暂时的；临时的",
"tempt|v.诱惑；吸引",
"temptation|n.诱惑",
"ten|num.十",
"tenant|n.房客；租户",
"tend|v.倾向于；照料",
"tendency|n.趋势；倾向",
"tender|a.嫩的；温柔的 v.提出",
"tennis|n.网球",
"tense|a.紧张的 n.时态",
"tension|n.紧张；张力；拉力",
"tent|n.帐篷",
"tentative|a.试探性的；不确定的",
"term|n.学期；术语；条款；期限",
"terminal|n.终点站；终端 a.晚期的",
"terminate|v.终止；结束",
"terrible|a.可怕的；糟糕的",
"terrific|a.极好的；非常大的",
"terrify|v.使恐惧；使惊吓",
"territory|n.领土；领域",
"terror|n.恐怖；惊骇",
"test|n./v.测试；试验",
"testify|v.作证；证明",
"testimony|n.证词；证据",
"text|n.正文；课文；文本",
"textbook|n.教科书；课本",
"textile|n.纺织品 a.纺织的",
"texture|n.质地；纹理",
"than|conj.比 prep.比",
"thank|v.感谢 n.感谢",
"that|a./pron.那；那个 conj.引导从句",
"the|art.这；那",
"theater|n.剧院；戏剧",
"theft|n.偷窃；盗窃",
"their|pron.他们的",
"them|pron.他们（宾格）",
"theme|n.主题；题目",
"themselves|pron.他们自己",
"then|ad.那时；然后；那么",
"theory|n.理论；学说",
"therapy|n.治疗；疗法",
"there|ad.在那里；那里",
"therefore|ad.因此；所以",
"thermal|a.热的；保暖的",
"thermometer|n.温度计",
"these|pron.这些",
"thesis|n.论文；论点",
"they|pron.他们",
"thick|a.厚的；浓的",
"thief|n.小偷；贼",
"thin|a.薄的；瘦的；稀的",
"thing|n.东西；事情",
"think|v.想；认为；思考",
"third|num.第三 n.三分之一",
"thirst|n.渴；渴望",
"thirsty|a.渴的；渴望的",
"thirteen|num.十三",
"thirty|num.三十",
"this|a./pron.这；这个",
"thorough|a.彻底的；仔细的",
"those|pron.那些",
"though|conj.虽然 ad.然而",
"thought|n.思想；想法",
"thoughtful|a.深思的；体贴的",
"thousand|num.一千",
"thread|n.线；线索 v.穿线",
"threat|n.威胁；恐吓",
"threaten|v.威胁；预示",
"three|num.三",
"threshold|n.门槛；起点",
"thrill|n.兴奋；激动 v.使兴奋",
"thrive|v.兴旺；茁壮成长",
"throat|n.喉咙；嗓子",
"through|prep.穿过 ad.从头到尾",
"throughout|prep.遍及 ad.始终",
"throw|v.投；扔",
"thrust|v.猛推；刺 n.推力",
"thumb|n.拇指",
"thunder|n.雷 v.打雷",
"thursday|n.星期四",
"thus|ad.因此；这样",
"ticket|n.票；罚单",
"tide|n.潮汐；趋势",
"tidy|a.整洁的 v.整理",
"tie|v.系；捆绑 n.领带；联系",
"tiger|n.老虎",
"tight|a.紧的；牢固的 ad.紧紧地",
"till|prep./conj.直到",
"timber|n.木材；木料",
"time|n.时间；次数；时代 v.计时",
"timetable|n.时间表；课程表",
"timid|a.胆怯的；羞怯的",
"tin|n.锡；罐头",
"tiny|a.极小的",
"tip|n.小费；尖端；提示 v.倾斜",
"tire|v.疲劳 n.轮胎",
"tired|a.疲倦的；厌倦的",
"tissue|n.组织；纸巾",
"title|n.标题；头衔；冠军",
"to|prep.到；向；对于",
"toast|n.烤面包；祝酒 v.烘烤",
"tobacco|n.烟草",
"today|ad./n.今天；现今",
"toe|n.脚趾",
"together|ad.一起；共同",
"toilet|n.厕所；马桶",
"token|n.象征；代币 a.象征性的",
"tolerate|v.容忍；忍受",
"tomato|n.西红柿",
"tomb|n.坟墓",
"tomorrow|ad./n.明天",
"ton|n.吨",
"tone|n.语气；音调；色调",
"tongue|n.舌头；语言",
"tonight|ad./n.今晚",
"too|ad.也；太",
"tool|n.工具；手段",
"tooth|n.牙齿",
"top|n.顶部 a.最高的 v.高于",
"topic|n.话题；题目",
"torch|n.手电筒；火炬",
"torture|n./v.折磨；拷打",
"total|a.总的 n.总数 v.共计",
"touch|v.触摸；感动 n.触觉；联系",
"tough|a.坚韧的；困难的；强硬的",
"tour|n./v.旅行；巡回",
"tourist|n.旅游者",
"toward|prep.向；对于",
"towel|n.毛巾",
"tower|n.塔 v.高耸",
"town|n.城镇",
"toy|n.玩具",
"trace|n.痕迹 v.追踪",
"track|n.轨道；小路；踪迹 v.追踪",
"tractor|n.拖拉机",
"trade|n.贸易；行业 v.交易",
"trademark|n.商标",
"tradition|n.传统；惯例",
"traditional|a.传统的",
"traffic|n.交通；运输",
"tragedy|n.悲剧；惨事",
"tragic|a.悲惨的；悲剧的",
"trail|n.小径；踪迹 v.追踪",
"train|n.火车 v.训练",
"training|n.训练；培训",
"trait|n.特征；特点",
"transaction|n.交易；事务",
"transcend|v.超出；超越",
"transfer|v.转移；换乘 n.转移",
"transform|v.改变；改造",
"transformation|n.转变；改造",
"transient|a.短暂的；暂住的",
"transistor|n.晶体管",
"transit|n.运输；经过",
"translate|v.翻译；转化",
"translation|n.翻译；译文",
"transmission|n.传播；传送",
"transmit|v.传送；传播",
"transparent|a.透明的；明显的",
"transplant|v./n.移植",
"transport|v./n.运输；交通",
"transportation|n.运输；交通",
"trap|n.陷阱 v.使落入陷阱",
"trash|n.垃圾；废物",
"travel|v./n.旅行",
"tray|n.托盘",
"treasure|n.财富；珍宝 v.珍惜",
"treat|v.对待；治疗；款待 n.款待",
"treatment|n.治疗；对待",
"treaty|n.条约；协议",
"tremble|v.颤抖；摇晃",
"tremendous|a.巨大的；极好的",
"trend|n.趋势；倾向",
"trial|n.审判；试验",
"triangle|n.三角形",
"tribe|n.部落；族",
"tribute|n.贡品；颂词",
"trick|n.诡计；戏法 v.欺骗",
"trigger|v.引发；触发 n.扳机",
"trim|v.修剪；削减 a.整齐的",
"trip|n.旅行；绊倒 v.绊倒",
"triple|a.三倍的 v.增至三倍",
"triumph|n.胜利；成功 v.获胜",
"troop|n.军队；一群",
"tropical|a.热带的",
"trouble|n.麻烦 v.使烦恼",
"troublesome|a.麻烦的；令人烦恼的",
"trousers|n.裤子",
"truck|n.卡车",
"true|a.真实的；忠实的",
"truly|ad.真正地；确实",
"trumpet|n.小号；喇叭",
"trunk|n.树干；后备箱；躯干",
"trust|v./n.信任；信托",
"truth|n.真相；事实",
"try|v.尝试；努力 n.尝试",
"tube|n.管；地铁",
"Tuesday|n.星期二",
"tuition|n.学费；教学",
"tune|n.曲调 v.调音；调节",
"tunnel|n.隧道；地道",
"turbulent|a.动荡的；湍流的",
"turkey|n.火鸡",
"turn|v.转动；变成 n.轮流；转弯",
"turnover|n.营业额；人员流动率",
"tutor|n.导师；家庭教师 v.辅导",
"TV|n.电视",
"twelve|num.十二",
"twenty|num.二十",
"twice|ad.两次；两倍",
"twin|n.双胞胎之一 a.孪生的",
"twist|v.拧；扭转 n.转折",
"two|num.二",
"type|n.类型 v.打字",
"typewriter|n.打字机",
"typhoon|n.台风",
"typical|a.典型的；有代表性的",
"typist|n.打字员"
);
