/* 词库数据 3/12 · C (a–l) */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"cab|n.出租车；驾驶室",
"cabbage|n.卷心菜",
"cabin|n.小木屋；船舱；机舱",
"cabinet|n.内阁；橱柜",
"cable|n.电缆；有线电视；缆绳",
"cafe|n.咖啡馆；小餐馆",
"cafeteria|n.自助餐厅",
"cage|n.笼子；牢房",
"cake|n.蛋糕；饼",
"calcium|n.钙",
"calculate|v.计算；估计；预测",
"calendar|n.日历；历法",
"calm|a.平静的 v.（使）平静 n.平静",
"camel|n.骆驼",
"camera|n.照相机；摄影机",
"camp|n.营地 v.露营",
"campaign|n.运动；战役 v.参加运动",
"campus|n.校园",
"can|v.能；可以 n.罐头；容器",
"canal|n.运河；水道",
"cancel|v.取消；抵消；删去",
"cancer|n.癌；癌症",
"candidate|n.候选人；应试者",
"candle|n.蜡烛",
"candy|n.糖果",
"cannon|n.大炮；火炮",
"canoe|n.独木舟",
"canvas|n.帆布；画布",
"canyon|n.峡谷",
"cap|n.帽子；盖 v.覆盖；限额",
"capable|a.有能力的；能干的",
"capacity|n.容量；能力；生产能力",
"cape|n.海角；披肩",
"capital|n.首都；资本；大写字母 a.资本的",
"capitalism|n.资本主义",
"capsule|n.胶囊；太空舱",
"captain|n.船长；队长；上尉",
"captive|n.俘虏 a.被俘虏的",
"capture|v.捕获；夺得；引起 n.捕获",
"car|n.汽车；车厢",
"carbon|n.碳",
"card|n.卡片；纸牌；名片",
"cardinal|a.主要的；基本的 n.红衣主教",
"care|n.照料；小心 v.关心；在意",
"career|n.生涯；职业",
"careful|a.仔细的；小心的",
"caress|v./n.爱抚；抚摩",
"cargo|n.货物；船货",
"carpenter|n.木匠",
"carpet|n.地毯",
"carriage|n.马车；车厢；运输",
"carrier|n.运输公司；运载工具；带菌者",
"carrot|n.胡萝卜",
"carry|v.携带；运送；支撑；传播",
"cart|n.手推车",
"cartoon|n.卡通片；漫画",
"carve|v.雕刻；切开",
"case|n.情况；案例；箱子；病例",
"cash|n.现金 v.兑现",
"cashier|n.出纳员",
"cassette|n.盒式磁带",
"cast|v.投；铸；投掷 n.演员阵容；铸件",
"castle|n.城堡",
"casual|a.随便的；偶然的；临时的",
"casualty|n.伤亡人员；受害者",
"cat|n.猫",
"catalog|n.目录 v.编目录",
"catastrophe|n.大灾难；灾祸",
"catch|v.抓住；赶上；感染；理解",
"category|n.种类；类别",
"cater|v.提供饮食；迎合",
"cathedral|n.大教堂",
"catholic|a.天主教的 n.天主教徒",
"cattle|n.牛；牲畜",
"cause|n.原因；事业 v.引起",
"caution|n.谨慎；警告 v.警告",
"cautious|a.谨慎的；小心的",
"cave|n.洞穴",
"cease|v./n.停止；终止",
"ceiling|n.天花板；上限",
"celebrate|v.庆祝；颂扬",
"celebrity|n.名人；名声",
"cell|n.细胞；小房间；电池",
"cellar|n.地窖；酒窖",
"cement|n.水泥 v.巩固；胶合",
"cemetery|n.墓地；公墓",
"census|n.人口普查",
"cent|n.分；分币",
"centigrade|a.摄氏的；百分度的",
"centimeter|n.厘米",
"central|a.中心的；主要的",
"century|n.世纪；百年",
"cereal|n.谷类食物；谷物",
"ceremony|n.仪式；典礼",
"certain|a.确定的；某一 pron.某些",
"certainly|ad.当然；确实",
"certificate|n.证书；证明书",
"certify|v.证明；证实",
"chain|n.链条；一连串 v.用链条锁住",
"chair|n.椅子；主席 v.主持",
"chairman|n.主席；会长；董事长",
"chalk|n.粉笔",
"challenge|n.挑战 v.向…挑战；质疑",
"chamber|n.房间；议院；腔",
"champion|n.冠军；拥护者 v.捍卫",
"chance|n.机会；可能性；偶然",
"chancellor|n.总理；大臣；校长",
"change|v.改变；交换 n.变化；零钱",
"channel|n.频道；海峡；渠道",
"chaos|n.混乱；无秩序",
"chapel|n.小教堂",
"chapter|n.章节；时期",
"character|n.性格；角色；汉字；品质",
"characteristic|n.特征 a.典型的",
"characterize|v.描绘…的特征；以…为特征",
"charge|v.收费；控告；充电 n.费用；指控",
"charity|n.慈善（机构）；施舍",
"charm|n.魅力 v.使陶醉",
"chart|n.图表；海图 v.制图",
"charter|n.宪章；租凭 v.包租",
"chase|v./n.追逐；追赶",
"chat|v./n.闲聊；聊天",
"cheap|a.便宜的；廉价的；劣质的",
"cheat|v.欺骗；作弊 n.骗子",
"check|v.检查；核对；阻止 n.检查；账单",
"cheek|n.脸颊",
"cheer|v.欢呼；使高兴 n.欢呼",
"cheerful|a.快乐的；愉快的",
"cheese|n.奶酪",
"chemical|a.化学的 n.化学品",
"chemist|n.化学家；药剂师",
"chemistry|n.化学",
"cherish|v.珍惜；怀有；爱护",
"chess|n.国际象棋",
"chest|n.胸部；箱子",
"chew|v.咀嚼；深思",
"chicken|n.鸡；鸡肉",
"chief|a.主要的；首席的 n.首领",
"chiefly|ad.主要地；首要地",
"child|n.儿童；孩子",
"childhood|n.童年；幼年时代",
"chill|n.寒冷 v.使变冷",
"chimney|n.烟囱",
"chin|n.下巴",
"china|n.瓷器",
"chip|n.芯片；碎片；薯条 v.削；凿",
"chocolate|n.巧克力",
"choice|n.选择；选择权 a.上等的",
"choke|v.窒息；堵塞；抑制",
"choose|v.选择；决定",
"chop|v.砍；剁碎 n.排骨",
"chorus|n.合唱队；副歌 v.合唱",
"christian|n.基督徒 a.基督教的",
"christmas|n.圣诞节",
"chronic|a.慢性的；长期的",
"church|n.教堂；教会",
"cigar|n.雪茄烟",
"cigarette|n.香烟",
"cinema|n.电影院；电影",
"circle|n.圆；圈子 v.环绕",
"circuit|n.电路；环行；巡回",
"circular|a.圆形的；循环的 n.通知",
"circulate|v.循环；流通；传播",
"circumstance|n.环境；情况；境遇",
"circus|n.马戏团；喧闹场面",
"cite|v.引用；举例；传唤",
"citizen|n.公民；市民",
"city|n.城市",
"civil|a.公民的；民用的；有礼貌的",
"civilian|n.平民 a.平民的",
"civilization|n.文明；文化",
"claim|v.声称；索取 n.主张；索赔",
"clap|v.拍手；轻拍 n.掌声",
"clarify|v.澄清；阐明",
"clarity|n.清晰；明晰",
"clash|v./n.冲突；交锋；不协调",
"clasp|n.扣子 v.紧握；抱住",
"class|n.班级；课；阶级；类别",
"classic|n.名著 a.经典的",
"classical|a.古典的；传统的",
"classification|n.分类；分级",
"classify|v.分类；归类",
"clause|n.条款；从句",
"claw|n.爪；螯",
"clay|n.粘土；泥土",
"clean|a.干净的 v.打扫",
"clear|a.清楚的；晴朗的 v.清除"
);
