/* 词库数据 7/12 · F + G */
window.RAW_WORDS=window.RAW_WORDS||[];
window.RAW_WORDS.push(
"fable|n.寓言；神话",
"fabric|n.织物；结构",
"fabricate|v.捏造；制造",
"fabulous|a.极好的；巨大的；寓言般的",
"face|n.脸；表面 v.面对",
"facilitate|v.促进；使便利",
"facility|n.设施；设备；才能",
"fact|n.事实；实际",
"factor|n.因素；要素",
"factory|n.工厂",
"faculty|n.才能；全体教员；系",
"fade|v.褪色；逐渐消失",
"fail|v.失败；不及格；衰退",
"failure|n.失败；故障；不足",
"faint|a.微弱的 v.昏倒 n.昏厥",
"fair|a.公平的；晴朗的；相当的 n.集市",
"fairly|ad.相当；公正地",
"fairy|n.仙女；精灵",
"faith|n.信任；信仰",
"faithful|a.忠诚的；如实的",
"fake|a.假的 n.赝品 v.伪造",
"fall|v.落下；变成 n.秋天；下降",
"false|a.错误的；假的；虚伪的",
"fame|n.名声；声誉",
"familiar|a.熟悉的；亲近的",
"family|n.家庭；家人；家族",
"famous|a.著名的",
"fan|n.迷；风扇 v.扇",
"fancy|n.想象 a.花式的 v.喜欢",
"fantastic|a.极好的；奇异的",
"far|a./ad.远的（地）",
"fare|n.车费；票价 v.过活",
"farewell|n.告别 int.再会",
"farm|n.农场 v.耕种",
"farmer|n.农民；农场主",
"fascinate|v.深深吸引；迷住",
"fashion|n.时尚；方式",
"fashionable|a.时髦的；流行的",
"fast|a.快的 ad.快；紧紧地 v.禁食",
"fasten|v.系紧；扣住",
"fat|a.肥胖的 n.脂肪",
"fatal|a.致命的；灾难性的",
"fate|n.命运",
"father|n.父亲；神父",
"fatigue|n.疲劳；疲惫",
"fault|n.缺点；过错；故障",
"favor|n.恩惠；赞同 v.赞同；有利于",
"favorable|a.有利的；赞同的",
"favorite|a.最喜爱的 n.最爱",
"fear|n./v.害怕；担忧",
"fearful|a.可怕的；担忧的",
"feasible|a.可行的",
"feast|n.盛宴；节日",
"feather|n.羽毛",
"feature|n.特征；特色；容貌 v.以…为特色",
"february|n.二月",
"federal|a.联邦的",
"fee|n.费；酬金",
"feeble|a.虚弱的；无力的",
"feed|v.喂养；输入 n.饲料",
"feedback|n.反馈；反应",
"feel|v.感觉；认为；触摸",
"feeling|n.感觉；感情；看法",
"fellow|n.家伙；同伴 a.同伴的",
"female|a.雌的 n.女子",
"feminine|a.女性的；女子气的",
"fence|n.栅栏；围栏 v.击剑",
"ferry|n.渡轮 v.渡运",
"fertile|a.肥沃的；多产的",
"fertilizer|n.肥料",
"festival|n.节日；音乐节",
"fetch|v.去取来；售得",
"fever|n.发烧；狂热",
"few|a.很少的 pron.少数",
"fiber|n.纤维",
"fiction|n.小说；虚构",
"field|n.田地；领域；场地",
"fierce|a.凶猛的；激烈的",
"fifteen|num.十五",
"fifth|num.第五 n.五分之一",
"fifty|num.五十",
"fight|v./n.战斗；打架；斗争",
"figure|n.数字；人物；身材 v.认为；计算",
"file|n.文件；档案；锉刀 v.提交；归档",
"fill|v.填满；充满",
"film|n.电影；胶卷 v.拍摄",
"filter|v.过滤 n.过滤器",
"final|a.最后的 n.决赛",
"finally|ad.最后；终于",
"finance|n.财政；金融 v.提供资金",
"financial|a.财政的；金融的",
"find|v.找到；发现；认为",
"finding|n.发现；调查结果",
"fine|a.好的；纤细的；晴朗的 n.罚款",
"finger|n.手指",
"finish|v.完成 n.结束",
"fire|n.火；火灾 v.解雇；开火；点燃",
"firm|n.公司 a.坚定的",
"first|num.第一 ad.首先",
"fish|n.鱼 v.钓鱼",
"fisherman|n.渔民",
"fist|n.拳头",
"fit|v.适合；安装 a.健康的；合适的",
"five|num.五",
"fix|v.修理；固定；确定",
"flag|n.旗；旗帜",
"flame|n.火焰；热情",
"flash|v.闪光；闪现 n.闪光；一瞬间",
"flat|a.平的；扁平的 n.公寓",
"flatter|v.奉承；使高兴",
"flavor|n.味道；风味 v.加味于",
"flaw|n.缺陷；瑕疵",
"flee|v.逃走；逃离",
"fleet|n.舰队；车队",
"flesh|n.肉；果肉",
"flexible|a.灵活的；柔韧的",
"flight|n.飞行；航班；逃跑",
"float|v.漂浮；浮动",
"flock|n.一群 v.聚集",
"flood|n.洪水 v.淹没",
"floor|n.地板；楼层",
"flour|n.面粉",
"flourish|v.繁荣；茁壮成长；挥舞",
"flow|v.流动 n.流动；流量",
"flower|n.花 v.开花",
"flu|n.流感",
"fluctuate|v.波动；起伏",
"fluent|a.流利的；流畅的",
"fluid|n.流体 a.流动的",
"flush|v.冲洗；脸红 a.齐平的",
"fly|v.飞；驾驶 n.苍蝇",
"foam|n.泡沫",
"focus|v.集中 n.焦点；中心",
"fog|n.雾",
"fold|v.折叠；交叉 n.褶",
"folk|n.人们 a.民间的",
"follow|v.跟随；遵循；听懂",
"following|a.下列的 n.追随者",
"fond|a.喜爱的；深情的",
"food|n.食物",
"fool|n.傻瓜 v.愚弄",
"foolish|a.愚蠢的",
"foot|n.脚；英尺；底部",
"football|n.足球；橄榄球",
"footstep|n.脚步；脚步声",
"for|prep.为了；因为；持续 conj.因为",
"forbid|v.禁止",
"force|n.力量；武力 v.强迫",
"forecast|v./n.预测；预报",
"forehead|n.前额",
"foreign|a.外国的；陌生的",
"foreigner|n.外国人",
"foremost|a.最重要的；最前的",
"forever|ad.永远；总是",
"forget|v.忘记；忽略",
"forgive|v.原谅；宽恕",
"fork|n.叉；餐叉；分叉",
"form|n.形式；表格 v.形成",
"formal|a.正式的；形式的",
"format|n.格式；版式 v.格式化",
"former|a.以前的；前者的",
"formula|n.公式；配方；原则",
"formulate|v.制定；系统地阐述",
"forth|ad.向前；向外",
"forthcoming|a.即将到来的",
"fortnight|n.两星期",
"fortunate|a.幸运的",
"fortune|n.财富；运气",
"forty|num.四十",
"forum|n.论坛；讨论会",
"forward|ad.向前 a.向前的 v.转寄",
"fossil|n.化石",
"foster|v.促进；培养；领养",
"foul|a.污秽的；犯规的 v.犯规",
"found|v.建立；创立",
"foundation|n.基础；地基；基金会",
"fountain|n.喷泉；源泉",
"four|num.四",
"fourth|num.第四 n.四分之一",
"fox|n.狐狸",
"fraction|n.小部分；分数",
"fragile|a.易碎的；脆弱的",
"fragment|n.碎片；片段",
"frame|n.框架；体格 v.给…装框；陷害",
"framework|n.框架；结构",
"frank|a.坦率的",
"fraud|n.欺诈；骗子",
"free|a.自由的；免费的 v.释放",
"freedom|n.自由",
"freeze|v.冻结；结冰 n.冻结",
"freight|n.货物；货运",
"frequency|n.频率；频繁",
"frequent|a.频繁的；经常的",
"fresh|a.新鲜的；新颖的",
"friend|n.朋友",
"friendly|a.友好的",
"friendship|n.友谊；友情",
"fright|n.惊吓；恐怖",
"frighten|v.使惊吓",
"frog|n.蛙",
"from|prep.从；来自；由于",
"front|n.前面；前线 a.前面的",
"frontier|n.边境；前沿",
"frost|n.霜；严寒",
"frown|v./n.皱眉",
"fruit|n.水果；成果",
"fruitful|a.富有成效的；多产的",
"frustrate|v.使沮丧；挫败",
"fry|v.油煎；油炸",
"fuel|n.燃料 v.加燃料；助长",
"fulfill|v.履行；实现；满足",
"full|a.满的；完全的",
"fume|n.烟；气 v.冒烟；发怒",
"fun|n.乐趣；玩笑",
"function|n.功能；函数 v.起作用",
"fund|n.基金；资金 v.资助",
"fundamental|a.基本的；根本的 n.基本原理",
"funeral|n.葬礼",
"funny|a.有趣的；古怪的",
"fur|n.毛皮；皮子",
"furious|a.狂怒的；猛烈的",
"furnace|n.熔炉；火炉",
"furnish|v.布置；提供",
"furniture|n.家具",
"further|ad./a.进一步（的） v.促进",
"furthermore|ad.此外；而且",
"fury|n.狂怒；暴怒",
"fuse|n.保险丝；导火线 v.熔合",
"fuss|n.大惊小怪 v.忙乱",
"futile|a.无用的；徒劳的",
"future|n.将来；前景 a.将来的",
"gain|v.获得；增加 n.收益",
"galaxy|n.星系；银河",
"gallery|n.画廊；美术馆",
"gallon|n.加仑",
"gamble|v./n.赌博；冒险",
"game|n.游戏；比赛；猎物",
"gang|n.一群；帮派",
"gap|n.缺口；差距；间隙",
"garage|n.车库；汽车修理厂",
"garbage|n.垃圾；废话",
"garden|n.花园；园子",
"garlic|n.大蒜",
"garment|n.衣服；外衣",
"gas|n.气体；煤气；汽油",
"gasoline|n.汽油",
"gasp|v./n.喘气；喘息",
"gate|n.大门；登机口",
"gather|v.聚集；收集；推测",
"gauge|n.计量器 v.测量；估计",
"gay|a.快乐的；同性恋的",
"gaze|v./n.凝视；注视",
"gear|n.齿轮；排挡 v.使适合",
"gender|n.性别",
"gene|n.基因",
"general|a.一般的；总的 n.将军",
"generalize|v.概括；推广",
"generally|ad.通常；大体上",
"generate|v.产生；引起",
"generation|n.一代人；产生",
"generator|n.发电机；发生器",
"generous|a.慷慨的；大方的",
"genetic|a.遗传的；基因的",
"genius|n.天才；天赋",
"gentle|a.温柔的；温和的",
"gentleman|n.绅士；先生",
"gently|ad.轻轻地；温柔地",
"genuine|a.真诚的；真正的",
"geography|n.地理（学）",
"geology|n.地质学",
"geometry|n.几何（学）",
"germ|n.细菌；萌芽",
"gesture|n.手势；姿态 v.做手势",
"get|v.得到；变得；到达",
"ghost|n.鬼魂；幽灵",
"giant|n.巨人 a.巨大的",
"gift|n.礼物；天赋",
"gigantic|a.巨大的；庞大的",
"giggle|v./n.咯咯笑",
"girl|n.女孩",
"give|v.给；提供；举办",
"glad|a.高兴的；乐意的",
"glance|v./n.一瞥；扫视",
"glare|v./n.怒视；耀眼的光",
"glass|n.玻璃；玻璃杯；镜子",
"glide|v./n.滑行；滑动",
"glimpse|n./v.一瞥；瞥见",
"glitter|v.闪光 n.灿烂的光辉",
"global|a.全球的；全面的",
"globe|n.地球；地球仪；球体",
"gloomy|a.阴暗的；忧郁的",
"glorious|a.光荣的；壮丽的",
"glory|n.光荣；荣誉；壮丽",
"glove|n.手套",
"glow|v.发光；发红 n.光辉",
"glue|n.胶水 v.粘合",
"go|v.去；变得；进行 n.尝试",
"goal|n.目标；进球；球门",
"goat|n.山羊",
"god|n.上帝；神",
"gold|n.黄金 a.金色的",
"golden|a.金色的；黄金的；美好的",
"golf|n.高尔夫球",
"good|a.好的；擅长的 n.好处",
"goodbye|int.再见 n.告别",
"goodness|n.善良；美德 int.天哪",
"goods|n.商品；货物",
"goose|n.鹅",
"gorgeous|a.华丽的；极好的",
"gossip|n.流言蜚语；闲话 v.说闲话",
"govern|v.统治；管理；支配",
"government|n.政府；管理",
"governor|n.州长；总督；主管",
"gown|n.长袍；礼服",
"grab|v.抓住；攫取",
"grace|n.优雅；恩惠",
"graceful|a.优雅的；优美的",
"grade|n.等级；成绩；年级 v.分级",
"gradual|a.逐渐的；渐进的",
"graduate|n.毕业生 v.毕业",
"grain|n.谷物；颗粒",
"gram|n.克",
"grammar|n.语法；语法书",
"grand|a.宏伟的；重大的",
"grandfather|n.祖父；外祖父",
"grandmother|n.祖母；外祖母",
"grant|v.授予；同意 n.拨款；授予物",
"grape|n.葡萄",
"graph|n.图表；曲线图",
"grasp|v./n.抓住；理解",
"grass|n.草；草地",
"grateful|a.感激的",
"gratitude|n.感激；感恩",
"grave|n.坟墓 a.严重的；严肃的",
"gravity|n.重力；严肃；严重性",
"grease|n.油脂 v.涂油",
"great|a.伟大的；巨大的；极好的",
"greed|n.贪婪；贪心",
"greedy|a.贪婪的；贪吃的",
"green|a.绿色的；环保的 n.绿色",
"greenhouse|n.温室；暖房",
"greet|v.问候；迎接；反应",
"greeting|n.问候；招呼",
"gray|a.灰色的 n.灰色",
"grief|n.悲伤；悲痛",
"grieve|v.悲伤；使伤心",
"grim|a.冷酷的；糟糕的；坚定的",
"grin|v./n.露齿而笑",
"grind|v.磨；碾；折磨 n.苦差事",
"grip|v./n.紧握；控制",
"groan|v./n.呻吟；叹息",
"grocery|n.食品杂货店",
"gross|a.总的；粗俗的；严重的",
"ground|n.地面；场地；理由",
"group|n.组；群 v.分组",
"grow|v.生长；种植；变得",
"growth|n.增长；生长；发展",
"guarantee|n./v.保证；担保",
"guard|v.保卫；看守 n.警卫；防护",
"guess|v./n.猜测；推测",
"guest|n.客人；宾客",
"guidance|n.指导；引导",
"guide|n.导游；指南 v.引导",
"guideline|n.指导方针；准则",
"guilt|n.内疚；罪行",
"guilty|a.有罪的；内疚的",
"guitar|n.吉他",
"gulf|n.海湾；鸿沟",
"gum|n.口香糖；树胶；牙龈",
"gun|n.枪；炮",
"guy|n.家伙；人"
);
